<div class="three-col">
	<div class="column">
		<h3>Agent Address Details</h3>
		<dl>
			<dt>Trading Name</dt>
			<dd><?php echo $this->tradingName; ?></dd>
			<dt>Legal Entity Name</dt>
			<dd>*</dd>
			<dt>Address</dt>
			<dd><?php echo $this->contactAddressLine1; ?></dd>
			<dd><?php echo $this->contactAddressLine2; ?></dd>
			<dd>*</dd>
			<dt>Town/City</dt>
			<dd><?php echo $this->contactTown; ?></dd>
			<dt>Postcode</dt>
			<dd><?php echo $this->contactPostcode; ?></dd>
			<dt>Phone</dt>
			<dd>*01522 587022</dd>
			<dt>Fax</dt>
			<dd>*08707 518779</dd>
			<dt>Email</dt>
			<dd>*</dd>
			<dt>Website</dt>
			<dd>*</dd>
			<dt>Scheme Number</dt>
			<dd><?php echo $this->schemeNumber; ?></dd>
			<dt>Contact Name</dt>
			<dd>*Helen Lloyd</dd>
			<dt>H Number</dt>
			<dd>*10039</dd>
			<dt>Credit Account Status</dt>
			<dd>*</dd>
			<dt>New Agent Set Up Type</dt>
			<dd>*</dd>
			<dt>Previous Scheme Number</dt>
			<dd>*</dd>
			<div style="clear:both;"></div>
		</dl>
	</div>
	
	<div class="column">
		<h3>Correspondance Address</h3>
		<dl>
			<dt>Street Address</dt>
			<dd>*Becor House</dd>
			<dd>*Green Lane</dd>
			<dd>*</dd>
			<dt>Town/City</dt>
			<dd>*Lincoln</dd>
			<dt>Postcode</dt>
			<dd>*LN6 7DL</dd>
			<div style="clear:both;"></div>s
		</dl>
		
		<h3>Invoice Address</h3>
		<dl>
			<dt>Street Address</dt>
			<dd>*Becor House</dd>
			<dd>*Green Lane</dd>
			<dd>*</dd>
			<dt>Town/City</dt>
			<dd>*Lincoln</dd>
			<dt>Postcode</dt>
			<dd>*LN6 7DL</dd>
			<div style="clear:both;"></div>
		</dl>
		
		<h3>Correspondance Methods</h3>
		<dl>
			<dt>Referencing Reports</dt>
			<dd>*Email | <strike>Post</strike></dd>
			<dt>Premier Renewals</dt>
			<dd>*Email | <strike>Post</strike></dd>
			<dt>Referencing Invoices</dt>
			<dd>*Email | <strike>Post</strike></dd>
			<div style="clear:both;"></div>
		</dl>
	</div>
	
	<div class="column">
		<h3>Agent Details</h3>
		<dl>
			<dt>Start Date</dt>
			<dd>*24/11/2003</dd>
			<dt>Status</dt>
			<dd>*LIVE</dd>
			<dt>Type</dt>
			<dd>*Other</dd>
			<dt>Absolute Type</dt>
			<dd>*Absolute</dd>
			<dt>Group</dt>
			<dd>*None</dd>
			<dt>Written Only</dt>
			<dd>*YES</dd>
			<dt>Opt-in</dt>
			<dd>*YES</dd>
			<dt>No Mailer</dt>
			<dd>*NO</dd>
			<dt>Do Not Contact Tenant</dt>
			<dd>*Off</dd>
			<dt>Referencing Paid</dt>
			<dd>*Direct Debit</dd>
			<dt>Commission Paid</dt>
			<dd>*Cheque</dd>
			<dt>Premier Subs Fee</dt>
			<dd>*&pound;75.00</dd>
			<dt>Commission Rate</dt>
			<dd><?php echo $this->commissionRate; ?>%</dd>
			<dt>New Business Commission Rate</dt>
			<dd><?php echo $this->newBusinessCommissionRate; ?>%</dd>
			<dt>BDM Name</dt>
			<dd>*Adam Reason</dd>
			<div style="clear:both;"></div>
		</dl>
		
		<h3>FSA Information</h3>
		<dl>
			<dt>FSA Status</dt>
			<dd>*Directly Authorised</dd>
			<dt>FSA Auth. Number</dt>
			<dd>*1</dd>
			<div style="clear:both;"></div>
		</dl>
	</div>
</div>

<div class="one-col">
	<div class="column">
		<h3>Notes</h3>
	</div>
</div>