<? // xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en" />
	<meta http-equiv="x-ua-compatible" content="IE=8" />
	<meta name="robots" content="noindex,nofollow" />

	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/reset.css" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/main.css" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/2col.css" title="2col" />
	<link rel="alternate stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/1col.css" title="1col" />
	<!--[if lte IE 6]><link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/main-ie6.css" /><![endif]-->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/style.css" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/custom.css" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/vendor/cms_admin/css/jquery-ui.css" />
	<script type="text/javascript" src="/assets/cms_admin/js/jquery.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/jquery-ui.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/jquery.tablesorter.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/jquery.switcher.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/toggle.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/ui.tabs.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/ckeditor/adapters/jquery.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/editor.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/jquery.imgareaselect.js"></script>
	<title>HomeLet CMS - Admin Suite</title>
</head>

<body>
	<div id="main">
		<!-- Tray -->
		<div id="tray" class="box">
			<p class="f-left box">
				<!-- Switcher -->
				<span class="f-left" id="switcher">
					<a href="#" rel="1col" class="styleswitch ico-col1" title="Display one column"><img src="/assets/cms_admin/design/switcher-1col.gif" alt="1 Column" /></a>
					<a href="#" rel="2col" class="styleswitch ico-col2" title="Display two columns"><img src="/assets/cms_admin/design/switcher-2col.gif" alt="2 Columns" /></a>
				</span>
				Website: <strong>HomeLet.co.uk</strong>
			</p>
			<?php
			$auth = Zend_Auth::getInstance();
	        $auth->setStorage(new Zend_Auth_Storage_Session('hl_admin'));
	        $username = $auth->getStorage()->read()->username;
	        ?>
			<p class="f-right">User: <strong><?php echo $username ?></strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong><a href="/cms-admin/logout" id="logout">Log out</a></strong></p>
		</div>
		<hr class="noscreen" />

		<!-- Menu -->
		<div id="menu" class="box">
			<ul class="box f-right">
				<li><a href="/home" target="_blank"><span><strong>Visit Site &raquo;</strong></span></a></li>
			</ul>
			<ul class="box">
				<h2>Content Management System</h3> V0.3.1(beta)
			</ul>
		</div>
		<hr class="noscreen" />

		<!-- Columns -->
		<div id="cols" class="box">
			<!-- Aside (Left Column) -->
			<div id="aside" class="box">
				<div class="padding box">
					<p id="logo"><a href="#"><img src="/assets/cms_admin/img/homelet_logo.jpg" alt="Our logo" title="Visit Site" /></a></p>
				</div>
				<ul class="box">
					<li <?php if ($this->currentPage=='dashboard') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/"><span>Dashboard</span></a></li>
					<li <?php if ($this->currentPage=='pages') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/pages"><span>Pages</span></a></li>
					<ul>
						<li><a href="/cms-admin/pages/add">Add a new page</a></li>
					</ul>
					<li <?php if ($this->currentPage=='panels') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/panels"><span>Panels</span></a></li>
					<!-- <li <?php if ($this->currentPage=='menu') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/menu"><span>Site Menu</span></a></li> -->
					<li <?php if ($this->currentPage=='testimonials') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/testimonials"><span>Testimonials</span></a></li>
					<ul>
						<li><a href="/cms-admin/testimonials/add">Add a new testimonial</a></li>
					</ul>
					<li <?php if ($this->currentPage=='headerQuotes') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/header-quotes"><span>Header Quotes</span></a></li>
					<ul>
						<li><a href="/cms-admin/header-quotes/add">Add a new header quote</a></li>
					</ul>
					<li <?php if ($this->currentPage=='news') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/news"><span>News</span></a></li>
					<ul>
						<li><a href="/cms-admin/news/add">Add a news article</a></li>
					</ul>
					<!-- <li <?php if ($this->currentPage=='staff') { ?>id="submenu-active"<?php } ?>><a href="#"><span>Staff</span></a></li> -->
					<li <?php if ($this->currentPage=='jobVacancies') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/vacancies"><span>Job Vacancies</span></a></li>
					<ul>
						<li><a href="/cms-admin/vacancies/add">Add a vacancy</a></li>
					</ul>
					<!-- <li <?php if ($this->currentPage=='users') { ?>id="submenu-active"<?php } ?>><a href="#"><span>User Management</span></a></li> -->

					<!-- Connect options -->
					<li <?php if ($this->currentPage=='connect') { ?>id="submenu-active"<?php } ?>>
						<a href="/cms-admin/connect"><span>Connect</span></a>
					</li>
					<ul>
						<li <?php if ($this->currentPage=='connectMotd') { ?>id="submenu-active"<?php } ?>><a href="/cms-admin/connect/motd">Messages of the Day</a></li>
						<ul style="padding-left: 15px;">
							<li><a href="/cms-admin/connect/add-motd">Add a new MOTD</a></li>
						</ul>
						
						<li><a href="/cms-admin/connect/blog">Blog</a></li>
						<ul style="padding-left: 15px;">
							<li><a href="/cms-admin/connect/add-blog-entry">Add a new blog entry</a></li>
                        </ul>
                    </ul>
					<!-- /Connect options -->
				</ul>
			</div>
			<hr class="noscreen" />
			<!-- Content (Right Column) -->
			<div id="content" class="box">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
		<hr class="noscreen" />

		<!-- Footer -->
		<div id="footer" class="box">
			<p class="f-left">&copy; 2010-<?php echo date('Y'); ?> <a href="#">HomeLet Ltd.</a>, All Rights Reserved &reg;</p>
			<p class="f-right"></p>
		</div>
	</div>
</body>
</html>
