<? //xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en" />
	<meta name="robots" content="noindex,nofollow" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/reset.css" /> <!-- RESET -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/main.css" /> <!-- MAIN STYLE SHEET -->
	<!--[if lte IE 6]><link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/main-ie6.css" /><![endif]--> <!-- MSIE6 -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/style.css" /> <!-- GRAPHIC THEME -->
	<script type="text/javascript" src="/assets/cms_admin/js/toggle.js"></script>
	<title>HomeLet CMS - Log In</title>
</head>

<body id="login" style="background-image:url('/assets/cms_admin/img/backgrounds/rotate.php');">

<div id="main-02">
    <?php echo $this->layout()->content; ?>
</div> <!-- /main -->

</body>
</html>
