<? // xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en" />
	<meta name="robots" content="noindex,nofollow" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/reset.css" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/main.css" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/2col.css" title="2col" />
	<link rel="alternate stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/1col.css" title="1col" />
	<!--[if lte IE 6]><link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/main-ie6.css" /><![endif]-->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/style.css" /> 
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/cms_admin/css/custom.css" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/vendor/cms_admin/css/jquery-ui.css" />
	<script type="text/javascript" src="/assets/cms_admin/js/jquery.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/jquery-ui.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/jquery.tablesorter.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/jquery.switcher.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/toggle.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/ui.tabs.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/ckeditor/adapters/jquery.js"></script>
	<script type="text/javascript" src="/assets/cms_admin/js/editor.js"></script>
    <script type="text/javascript" src="/assets/cms_admin/js/jquery.imgareaselect.js"></script>
	<title>HomeLet CMS - Admin Suite</title>
</head>

<body>
	<div id="content">
        <?php
        echo $this->layout()->content;
        ?>
    </div>
</body>
</html>