<div class="wrapper two-col">
    <div class="content">
        <strong>
            We're sorry, but it would appear that we don't currently have an up to date agent
            status for you. It's important for us to work with all our agents to ensure they have the appropriate
            status for their business, and until we have resolved this we can't allow you to access our products
            and services on Connect. We'd love to help you find the right status for your business so please contact
            your account manager so that we can work together to resolve this.
        </strong>
        
        <a href="/logout">Back to login</a>
    </div>
</div>
