<div class="wrapper two-col">

    <div class="content">

        <form id="lostlogin" name="lostlogin" enctype="application/x-www-form-urlencoded" method="post" action="">

            <h2>Thank you</h2>

            <p class="clear">
                We&rsquo;ve sent an email which contains your login details. This email, which will arrive shortly, will also include a link to reset your password.
            </p>

            <p>
                If we don&rsquo;t have an email address registered for your user account, then the email will be sent to the master user associated with your account.
            </p>

            <p>
                Remember, once you&rsquo;re logged in to Connect, you can update your details in the settings section.
            </p>

            <p>
                <a href="/connect">Back</a>
            </p>

        </form>

    </div>
</div>