<div class="wrapper two-col">

    <div class="content">

        <form>
            <h2>bad code</h2>
        </form>

        <p class="clear">
            <strong><?php echo $this->error ?></strong>
        </p>

        <p>
            Click here to <a href="/lost-login">generate a new password reset link</a>.
        </p>

        <p>
            I've remembered my log in details - <a href="/connect">log in to Connect</a>.
        </p>

    </div>
</div>