<div class="wrapper two-col">

    <div class="content">

        <form id="lostlogin" name="lostlogin" enctype="application/x-www-form-urlencoded" method="post" action="">

            <h2>reset password</h2>

            <p class="clear">
                Use this form to reset <?php echo $this->realname ?>'s password.
            </p>

            <p>
                I've remembered my log in details - <a href="/connect">log in to Connect</a>.
            </p>

            <p class="messages" id="message">
                <?php
                $formLevelErrors = $this->form->getErrorMessages();
                if (count($formLevelErrors) > 0) {
                    echo "<ul class=\"errors\"><li>";
                    echo implode('</li><li>', $formLevelErrors);
                    echo "</li></ul>";
                }
                ?>
            </p>

            <div class="form_section one-col">
                <div class="alt">
                    <div>
                        <label for="agentschemeno">Agent scheme number</label>
                        <input type="text" id="agentschemeno" name="agentschemeno" value="<?php echo $this->agentschemeno; ?>" disabled="disabled" />
                    </div>
                </div>
                <div>
                    <div>
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username" value="<?php echo $this->username; ?>" disabled="disabled" />
                    </div>
                </div>
                <div class="alt">
                    <div>
                        <?php echo $this->form->getElement('password1'); ?>
                    </div>
                </div>
                <div>
                    <div>
                        <?php echo $this->form->getElement('password2'); ?>
                    </div>
                </div>
            </div>

            <input type="submit" value="save" id="next" name="Submit" />
        </form>

    </div>
</div>