<div class="wrapper two-col">

    <div class="content">

        <form id="resetpassword" name="resetpassword" enctype="application/x-www-form-urlencoded" method="post" action="/connect">

            <input type="hidden" id="agentschemeno" name="agentschemeno" value="<?php echo $this->agentschemeno; ?>" />
            <input type="hidden" id="username" name="username" value="<?php echo $this->username; ?>" />
            <input type="hidden" id="password" name="password" value="<?php echo $this->password; ?>" />

            <h2>reset password</h2>

            <p class="clear">
                I've remembered my log in details - <a href="/connect">log in to Connect</a>.
            </p>

            <p>
                <strong>Password reset, click &quot;continue&quot; to log in now.</strong>
            </p>

            <div class="form_section one-col">
                <div class="alt">
                    <div>
                        <label for="agentschemeno">Agent scheme number</label>
                        <input type="text" id="agentschemeno" name="agentschemeno" value="<?php echo $this->agentschemeno; ?>" disabled="disabled" />
                    </div>
                </div>
                <div>
                    <div>
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username" value="<?php echo $this->username; ?>" disabled="disabled" />
                    </div>
                </div>
            </div>

            <input type="submit" value="continue" id="next" name="Submit" />
        </form>

    </div>
</div>