<h1>Blog</h1>

<script type="text/javascript">
	$(function() {		
		
		$(".blog-delete").click(function(e){
			if (!confirm("Are you sure you want to delete this blog entry?\n\nThis action cannot be undone!"))
			{
				e.preventDefault();
			}
		});
		
		$( "#sortable" ).sortable({
			opacity: 0.6,
			update : function () { 
				$('#menuorder').val($('#sortable').sortable('toArray')); 
			} 
		});
		
		$( "#sortable" ).disableSelection();
		
		<?php if ($this->deleted) { ?>
			setTimeout(function() {
				$('.done').animate({opacity: "0"}, 1000).slideUp(500);
			}, 3000);    
		<?php } ?>
		
		<?php if ($this->statusChanged) { ?>
			setTimeout(function() {
				$('.statusChanged').animate({opacity: "0"}, 1000).slideUp(500);
			}, 3000);    
		<?php } ?>
		
		<?php if ($this->saved) { ?>
			setTimeout(function() {
				$('.saved').animate({opacity: "0"}, 1000).slideUp(500);
			}, 3000);    
		<?php } ?>
		
	});
</script>


<?php if ($this->deleted) { ?>
    <p class="msg done">Blog entry deleted successfully!</p>
<?php } ?>

<?php if ($this->statusChanged) { ?>
    <p class="msg statusChanged">Blog entry status changed successfully!</p>
<?php } ?>

<?php if ($this->saved) { ?>
    <p class="msg saved">Blog entry saved successfully!</p>
<?php } ?>


<h5>
	Main blog entry
	<span class="connect-info-text">The main blog entry is displayed in full on the Connect homepage</span></h5>
<table>
    <thead>
        <tr>
			<th class="connect-blog-col1">Last Updated</th>
			<th class="connect-blog-col2">Title</th>
			<th class="connect-blog-col3">Summary</th>
			<th class="connect-blog-col4">&nbsp;</th>
        </tr>
	</thead>
	
	<tbody>
        <?php echo $this->connectBlogMain; ?>
    </tbody>
</table>
<br />


<h5>
	Summary blog entries
	<span class="connect-info-text">A maximum of four summaries are allowed at any one time. Their order is as shown below</span>
</h5>
<table>
    <thead>
        <tr>
			<th class="connect-blog-col1">Last Updated</th>
			<th class="connect-blog-col2">Title</th>
			<th class="connect-blog-col3">Summary</th>
			<th class="connect-blog-col4">&nbsp;</th>
        </tr>
	</thead>
	
	<tbody>
        <?php echo $this->connectBlogSummary; ?>
    </tbody>
</table>
<br />


<h5>
	Blog entry pool
	<span class="connect-info-text">The list of blog entries that are neither summary entries nor the main entry</span>
</h5>
<table>
    <thead>
        <tr>
			<th class="connect-blog-col1">Last Updated</th>
			<th class="connect-blog-col2">Title</th>
			<th class="connect-blog-col3">Summary</th>
			<th class="connect-blog-col4">&nbsp;</th>
        </tr>
	</thead>
	
	<tbody>
        <?php echo $this->connectBlogPool; ?>
    </tbody>
</table>
<br />

<a href="/cms-admin/connect/upsert-blog-entry">Add a new blog entry</a>