<h1>Connect</h1>

<div class="connect-cms-box">
    <h5>Messages of the Day <span class="connect-info-text">Icons explained</span></h5>
    
    <br />
    
    <div>
        <img src="/assets/cms_admin/design/ico-status-online.png" title="Activate icon" alt="Activate icon" />    
        Activates the message. The message will display only between its 'Date From' till its 'Date To'.
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/ico-status-offline.png" title="Deactivate icon" alt="Deactivate icon" />    
        Deactivates the message. The message can be re-activated at any time.
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/ico-preview.png" title="Preview icon" alt="Preview icon" />    
        Preview a message of the day.
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/ico-edit.gif" title="Edit icon" alt="Edit icon" />    
        Edit a message of the day. 
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/ico-delete.gif" title="Delete icon" alt="Delete icon" />    
        Delete a message of the day. Will prompt user first. Permanently deletes the message.
    </div>
    
    
    <br />
    
    
    <div>
        <img src="/assets/cms_admin/design/user-red.png" title="Standard agent" alt="Standard agent" />    
        Identifies a standard agent
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/user-orange.png" title="Premier agent" alt="Premier agent" />    
        Identifies a premier agent
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/user-green.png" title="Premier-Plus agent" alt="Premier-Plus agent" />    
        Identifies a premier-plus agent
    </div>
    
    
    <br />
    
    
    <div>
        <img src="/assets/cms_admin/design/user-orange.png" title="Basic connect user" alt="Basic connect user" />    
        Identifies a basic Connect user
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/user-green.png" title="Basic connect user" alt="Basic connect user" />    
        Identifies a master Connect user
    </div>

</div>


<div class="connect-cms-box">
    <h5>Blog <span class="connect-info-text">Icons explained</span></h5>
    
    <br />
    
    <div>
        <img src="/assets/cms_admin/design/ico-edit.gif" title="Edit icon" alt="Edit icon" />    
        Edit a blog entry. 
    </div>
    
    <div>
        <img src="/assets/cms_admin/design/ico-delete.gif" title="Delete icon" alt="Delete icon" />    
        Delete a blog entry. Will prompt user first. Permanently deletes the entry.
    </div>

</div>