<!-- Provide styles and scripts for the MOTD popup -->
<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/vendor/facebox/css/facebox.css" />
<link rel="stylesheet" media="screen,projection" type="text/css" href="/assets/vendor/facebox/css/cms-admin-facebox.css" />
<script type="text/javascript" src="/assets/vendor/facebox/js/jquery.facebox.js"></script>
<script type="text/javascript">
	$(function() {
		
		$(".motd-delete").click(function(e){
			if (!confirm("Are you sure you want to delete this MOTD?\n\nThis action cannot be undone!"))
			{
				e.preventDefault();
			}
		});
	
		$( "#sortable" ).sortable({
			opacity: 0.6,
			update : function () { 
				$('#menuorder').val($('#sortable').sortable('toArray')); 
			} 
		});
	
		$( "#sortable" ).disableSelection();
		
		<?php if ($this->deleted) { ?>
			setTimeout(function() {
				$('.done').animate({opacity: "0"}, 1000).slideUp(500);
			}, 3000);    
		<?php } ?>
		
		<?php if ($this->activated) { ?>
			setTimeout(function() {
				$('.activated').animate({opacity: "0"}, 1000).slideUp(500);
			}, 3000);    
		<?php } ?>
		
		<?php if ($this->deactivated) { ?>
			setTimeout(function() {
				$('.deactivated').animate({opacity: "0"}, 1000).slideUp(500);
			}, 3000);    
		<?php } ?>
		
		<?php if ($this->saved) { ?>
			setTimeout(function() {
				$('.saved').animate({opacity: "0"}, 1000).slideUp(500);
			}, 3000);    
		<?php } ?>
	});
	
	
	function displayPreview(id, motdWidth) {
		
		$(document).bind('beforeReveal.facebox', function() {
			$('#facebox .body')
				.width(motdWidth + 'px')
				.click(function(e) {
					$(document).trigger('close.facebox');
				});
		});

		$.facebox(
			$('#dialog' + id).attr('title'),
			$('#dialog' + id).html()
		);
		
		//Hide default close button.
        $('.close').css('display', 'none');
	}
	
</script>

<h1>Messages of the Day</h1>

<!-- Messages -->
<?php if ($this->deleted) { ?>
    <p class="msg done">MOTD deleted successfully!</p>
<?php } ?>

<?php if ($this->activated) { ?>
    <p class="msg activated">MOTD activated successfully!</p>
<?php } ?>

<?php if ($this->deactivated) { ?>
    <p class="msg deactivated">MOTD deactivated successfully!</p>
<?php } ?>

<?php if ($this->saved) { ?>
    <p class="msg saved">MOTD saved successfully!</p>
<?php } ?>


<h5>
	Active message
	<span class="connect-info-text">MOTs displayed only between 'Display From' to 'Display To'. For long term messages, set the dates accordingly.</span>
</h5>
<table>
    <thead>
        <tr>
			<th class="connect-motd-col1">Display From</th>
			<th class="connect-motd-col2">Display To</th>
			<th class="connect-motd-col3">Agents</th>
			<th class="connect-motd-col4">Users</th>
            <th class="connect-motd-col5">Title</th>
            <th class="connect-motd-col6">&nbsp;</th>
        </tr>
	</thead>
	
	<tbody>
        <?php echo $this->connectMotdActive ?>
    </tbody>
</table>
<br />

<h5>Inactive messages</h5>
<table>
    <thead>
        <tr>
			<th class="connect-motd-col1">Display From</th>
			<th class="connect-motd-col2">Display To</th>
			<th class="connect-motd-col3">Agents</th>
			<th class="connect-motd-col4">Users</th>
            <th class="connect-motd-col5">Title</th>
            <th class="connect-motd-col6">&nbsp;</th>
        </tr>
	</thead>
	
	<tbody>
        <?php echo $this->connectMotdInactiveList ?>
    </tbody>
</table>
<br />

<a href="/cms-admin/connect/upsert-motd">Add a new message</a>