<div class="col-xs-12">
    <?php echo $this->breadcrumbs ?>
</div>

<div class="clearfix"></div>

<div class="portal-wrapper">
    <div class="primary-content col-sm-8">
        <h1>There was a problem with your activation attempt</h1>

        <p>
            The link we sent you appears to be invalid and your account could not be activated. Please
            contact us to get another activation link.
        </p>
    </div>
</div>
