
<div class="popup_form_section">
    <?php if ($this->form->getDescription()): ?>
        <ul class="errors">
            <li><?php echo $this->escape($this->form->getDescription()) ?></li>
        </ul>
    <?php endif ?>
    <?php echo $this->form ?>
</div>

<script type="text/javascript">
    (function ($) {
        $('#forgot-password').submit(function (e) {
            e.preventDefault();
            var $form = $(this);
            $.ajax({
                url: $form.attr('action')
                , type: 'post'
                , data: $form.serialize()
                , success: function (data) {
                    $('#facebox .facebox-content').html(data);
                }
            });
        });
    })(jQuery);
</script>