<div class="col-xs-12">
    <?php echo $this->breadcrumbs ?>
</div>

<div class="clearfix"></div>

<div class="portal-wrapper">
    <div class="primary-content col-sm-8">
        <h1>We’re almost there!</h1>

        <h2>Check your inbox for your validation email</h2>

        <p>
            Thank you for registering your My HomeLet account. We’ve sent you an email to verify your email address.
            This contains a secure link that you need to click to complete the registration process.
        </p>

        <p>
            Once you’ve validated your email address, you’ll be able to access the full range of features and
            benefits available to you through your My HomeLet account. You’ll be able to:
        </p>

        <ul>
            <li>View your insurance policies</li>
            <li>View and download your insurance documents</li>
            <li>Change your login details</li>
            <li>View and continue your saved insurance quotes</li>
        </ul>

        <a href="/my-homelet/login">Return to the login page</a>
    </div>
</div>
