<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2 class="form" style="clear: both;">Referencing HomeLet Verify Information</h2>

        <p>HomeLet Verify is an easy to use, innovative online solution, designed to help you more easily comply with
            Government regulations under the Immigration Act.</p>

        <p>Section 22 of the Immigration Act requires all landlords (or the agents acting on their behalf) to check the
            immigration status of all potential tenants, to ensure they have the right to live in the UK, prior to them
            taking up residence in a privately rented property.</p>

        <p>They&rsquo;re also required to ensure the documentation provided by the tenant (passports, visas etc.) is genuine
            and that the person renting the property matches the person listed on the document, before making a copy
            and storing it in a secure manner for a specified period of time.</p>

        <p>Upon logging into HomeLet Verify, you&rsquo;ll be asked five simple questions to guide you through the process of
            ascertaining whether a tenant has the legal right to rent the property.</p>

        <p>Once the checks are completed, a copy of the documentation will be stored securely on your behalf.</p>

        <p>You&rsquo;ll also be presented with a final report, which you can use as proof that you&rsquo;ve complied with the
            legislation and carried out the appropriate checks.</p>

        <p>To find out more about the right to rent checks and the Immigration Act, read our
            <a href="<?php echo $this->blogUrl; ?>">blog</a>, have a look at
            our <a href="<?php echo $this->faqsUrl; ?>">handy FAQs</a> or visit the
            <a href="<?php echo $this->homeOfficeUrl; ?>">Home Office website.</a></p>

        <p>Alternatively, if you have any problems using or accessing the HomeLet Verify service, please contact our
            dedicated helpline on <?php echo $this->phoneNumber; ?>.</p>

        <p><a class="btn button" href="<?php echo $this->checkUrl; ?>">Complete a check</a></p>
    </div>
</div>