<?php

// Grab view to show form-level errors
$view = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getResource('view');

if (count($view->errors) > 0) : ?>
    <div class="alert alert-warning">
        <ul class="errors">
            <?php foreach($view->errors as $error) : ?>
                <li><?php echo $error; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<div class="panel panel-dark">
    <div class="form_section one-col">
        <div class="form-group">
            <label for="name" class="col-md-4">
                Please enter your name
            </label>
            <div class="col-md-8">
                <?php
                echo $this->element->name
                    ->removeDecorator('label')
                    ->setAttribs(
                        array(
                            'class' => 'text form-control'
                        )
                    )->render();
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="contact_info" class="col-md-4">
                Please enter a contact number or email address
            </label>
            <div class="col-md-8">
                <?php
                echo $this->element->contact_info
                    ->removeDecorator('label')
                    ->setAttribs(
                        array(
                            'class' => 'text form-control'
                        )
                    )->render();
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="message" class="col-md-4">
                Please enter the message for the assessor
            </label>
            <div class="col-md-8">
                <?php
                echo $this->element->message
                    ->removeDecorator('label')
                    ->setAttribs(
                        array(
                            'class' => 'text form-control',
                            'required' => 'required',
                            'aria-required' => 'true'
                        )
                    )->render();
                ?>
            </div>
        </div>
    </div>

    <ul class="list-inline list-buttons pull-right">
        <li>
            <?php
            echo $this->element->back
                ->setAttribs(
                    array(
                        'class' => 'btn btn-primary'
                    )
                )->render();
            ?>
        </li>
        <li>
            <?php
            echo $this->element->next
                ->setAttribs(
                    array(
                        'class' => 'btn btn-primary'
                    )
                )->render();
            ?>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>