<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Insurance+',
                'url'   => '/assets/connect/pdf/Landlords_Insurance_Plus_Policy_Summary.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document provides a summary of the cover we provide.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Comprehensive Insurance',
                'url'   => '/assets/connect/pdf/Landlords_Comprehensive_Insurance_Policy_summary.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document provides a summary of the cover we provide.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Portfolio Insurance',
                'url'   => '/assets/connect/pdf/Portfolio_Policy_Summary.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document provides a summary of the cover we provide.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Protection',
                'url'   => '/assets/connect/pdf/HL310_Tenants_Protection_Policy_Summary-0313.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document provides a summary of the cover we provide.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Protection',
                'url'   => '/assets/connect/pdf/HL310_Tenants_Protection_Policy_Summary-0315.pdf',
                'pdf_info'  => array(
                    'description'   => 'Please use for policies incepted or invited to renew on or after 27 March 2015.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Insurance',
                'url'   => '/assets/connect/pdf/Tenants_Insurance_Policy_Summary.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document provides a summary of the cover we provide.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Insurance',
                'url'   => '/assets/connect/pdf/Tenants_Insurance_Policy_Summary_0315.pdf',
                'pdf_info'  => array(
                    'description'   => 'Please use for policies incepted or invited to renew on or after 27 March 2015.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Low Cost Buildings',
                'url'   => '/assets/connect/pdf/Low_Cost_Buildings_Policy_Summary.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document provides a summary of the cover we provide.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
        ));
        ?>
    </div>
</div>
