<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Legal Expenses',
                'url'   => '/assets/connect/pdf/Landlords_Legal_Expenses_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your landlords lets them know more about our Legal Expenses policy.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Building&rsquo;s Insurance+',
                'url'   => '/assets/connect/pdf/Landlords_Building_Insurance_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your landlords lets them know more about our specialist buildings insurance.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Content&rsquo;s Insurance+',
                'url'   => '/assets/connect/pdf/Landlords_Contents_Insurance_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your landlords lets them know more about our specialist contents insurance.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Unfurnished Contents',
                'url'   => '/assets/connect/pdf/Landlords_Contents_Unfurnished_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your landlords lets them know more about our contents insurance for unfurnished properties.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Emergency Assistance',
                'url'   => '/assets/connect/pdf/Landlords_Emergency_Assistance_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your landlords lets them know more about our Emergency Assistance service.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Prestige Rent Guarantee',
                'url'   => '/assets/connect/pdf/Landlords_Prestige_Rent_Guarantee_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your landlords lets them know more about Prestige Rent Guarantee.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Insurance',
                'url'   => '/assets/connect/pdf/Tenants_Insurance_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your tenants lets them know more about Tenant&rsquo;s Insurance.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord Insurance+',
                'url'   => '/assets/connect/pdf/Landlords_Insurance_Plus_E-flyer.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document for your landlords lets them know more about Landlord&rsquo;s Insurance+.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
        ));
        ?>

    </div>
</div>
