<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Insurance+',
                'url'   => '/assets/connect/pdf/Landlords_Insurance_Plus_Policy_Wording.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is the policy wording for Landlord&rsquo;s Insurance+.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Comprehensive',
                'url'   => '/assets/connect/pdf/Landlords_Comprehensive_Insurance_Policy_Wording.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is the policy wording for Landlord&rsquo;s Comprehensive Insurance.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Low Cost',
                'url'   => '/assets/connect/pdf/Landlords_Low_Cost_Option_Policy_Wording.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is the policy wording for our Landlord&rsquo;s Low Cost Option.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Landlord&rsquo;s Portfolio Insurance',
                'url'   => '/assets/connect/pdf/Landlords_Portfolio_Insurance_Policy_Wording.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is the policy wording for Landlord&rsquo;s Insurance+.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Insurance',
                'url'   => '/assets/connect/pdf/Tenants_Insurance_Policy_Wording.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is the policy wording for our Tenant&rsquo;s Insurance.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Insurance',
                'url'   => '/assets/connect/pdf/Tenants_Insurance_Policy_Wording_0315.pdf',
                'pdf_info'  => array(
                    'description'   => 'Please use for policies incepted or invited to renew on or after 27 March 2015.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Protection',
                'url'   => '/assets/connect/pdf/Tenants_Protection_Policy_Wording.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is the policy wording for our Tenant&rsquo;s Insurance.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Tenant&rsquo;s Protection',
                'url'   => '/assets/connect/pdf/Tenants_Protection_Policy_Wording_0315.pdf',
                'pdf_info'  => array(
                    'description'   => 'Please use for policies incepted or invited to renew on or after 27 March 2015.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )            
        ));
        ?>
    </div>
</div>
