<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
		$this->iconLayout(array(
            array(
                'icon'      => 'documents',
                'title'     => 'Useful documents to help you get started',
                'help_text' => '',
                'url'       => '/moreproducts/newcustomerdocs/welcomepack'
            ),
            array(
                'icon'      => 'documents',
                'title'     => 'Referencing documents',
                'help_text' => 'View your guides to our referencing process',
                'url'       => '/moreproducts/newcustomerdocs/referencingdocs'
            ),
            array(
                'icon'      => 'documents',
                'title'     => 'Useful compliance documents',
                'help_text' => 'Including info on Treating Customers Fairly',
                'url'       => '/moreproducts/newcustomerdocs/compliance'
            ),
            array(
                'icon'      => 'documents',
                'title'     => 'Rent Guarantee products',
                'help_text' => 'Find out more about our specialist products',
                'url'       => '/rentguarantee/products'
            )
        ));
        ?>
    </div>
</div>