<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Referencing service guidelines',
                'url'   => '/assets/connect/pdf/Referencing_Service_Guidelines.pdf',
                'pdf_info'  => array(
                    'description'   => 'This handy guide is designed to help you get the most out of being a HomeLet customer. It contains plenty of tips and explains our referencing process.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Referencing quick guide',
                'url'   => '/assets/connect/pdf/Referencing_Quick_Guide.pdf',
                'pdf_info'  => array(
                    'description'   => 'This guide provides an overview of our referencing criteria, such as what Tenancy Application Scores are acceptable, and our couple&rsquo;s criteria.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
        ));
        ?>
    </div>
</div>