<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Property Agent Professional Insurance',
                'url'   => '/assets/connect/pdf/Professional_Indemnity_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'Here&rsquo;s a bit more information on Property Agent Professional Insurance',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Application form',
                'url'   => '/assets/connect/pdf/Professional_Indemnity_Application_Form.pdf',
                'pdf_info'  => array(
                    'description'   => 'Download this form to apply or to find out more about our Professional Insurances, including Professional Indemnity, call 0845 117 6033.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
        ));
        ?>
    </div>
</div>
