<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
       <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Optimum product information',
                'url'   => '/assets/connect/pdf/Optimum_Product_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'You can pass this document to your landlords to let them know what checks are included in our award winning Optimum tenant reference.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Optimum terms &amp; conditions',
                'url'   => '/assets/connect/pdf/Optimum_Terms_And_Conditions.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document contains lots of important information about our Optimum reference, such as what our tenant eviction service is and how we gain possession of a property.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Optimum service process',
                'url'   => '/assets/connect/pdf/Optimum_Service_Process.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document outlines the service process for our award winning Optimum reference and lets you know what you need to do, should the tenant fail to pay their rent.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Optimum service request form',
                'url'   => '/assets/connect/pdf/Optimum_Service_Request_Form.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is the form you need to complete to make a service request on an Optimum reference. If you&rsquo;re unsure about our process make sure you read our Optimum service process document.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
        ));
        ?>
    </div>
</div>