<link href="/assets/connect/css/referencingProducts.css" media="screen" rel="stylesheet" type="text/css" />

<!-- IE and PIE have some rendering issues, popping the columns to a different
    width and back solves things :-/ -->
<!--[if IE]>
<script type="text/javascript">
$(function() {
    setTimeout(function() {
        var oldWidth = $('.connect_product_column').width()
        $('.connect_product_column').css('width', '30.9%');
        setTimeout(function() {
            $('.connect_product_column').css('width', oldWidth);
        }, 10);
    }, 10);
});
</script>
<![endif]-->

<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <p>We offer three types of tenant reference so whether you need a quick check on your applicants or a detailed reference with a high level of information we&rsquo;ve got a product to suit your business.</p>

        <div class="connect_product_column">
            <h2>Insight</h2>
            <div class="connect_product_header">
                <p>We&rsquo;ll ensure that your tenant is suitable for a tenancy by checking a range of credit information.</p>
            </div>
            <p><a href="/referencing/products/insight">View product documents</a></p>
            <p class="connect_product_info_header">What&rsquo;s included in an <strong>Insight</strong><br />reference?</p>
            <ul>
                <li>Bank detail check</li>
                <li>HomeLet Default Database check</li>
                <li>Financial sanctions check</li>
                <li>Adverse credit history check</li>
                <li>Bankruptcy checks</li>
                <li>CCJs and court decrees check</li>
                <li>Undisclosed address + name check</li>
            </ul>
        </div>
        <div class="connect_product_column">
            <h2>Enhance</h2>
            <div class="connect_product_header">
                <p>We&rsquo;ll get a reference from the tenant&rsquo;s current Landlord or Managing Agent and employer.</p>
            </div>
            <p><a href="/referencing/products/enhance">View product documents</a></p>
            <p class="connect_product_info_header">What&rsquo;s included in an <strong>Enhance</strong><br />reference?</p>
            <ul>
                <li>Bank detail check</li>
                <li>HomeLet Default Database check</li>
                <li>Financial sanctions check</li>
                <li>Adverse credit history check</li>
                <li>Bankruptcy checks</li>
                <li>CCJs and court decrees check</li>
                <li>Undisclosed address + name check</li>
                <li class="alt1">Full employment reference, including income information</li>
                <li class="alt1">Future employment reference if required</li>
                <li class="alt1">Current landlord or managing agent reference</li>
            </ul>
        </div>
        <div class="connect_product_column">
            <h2>Optimum</h2>
            <div class="connect_product_header">
                <p>As well as a full Enhance reference we&rsquo;ll guarantee to remove the tenant from your property if they fail to pay the rent.</p>
            </div>
            <p><a href="/referencing/products/optimum">View product documents</a></p>
            <p class="connect_product_info_header">What&rsquo;s included in an <strong>Optimum</strong><br />reference?</p>
            <ul>
                <li>Bank detail check</li>
                <li>HomeLet Default Database check</li>
                <li>Financial sanctions check</li>
                <li>Adverse credit history check</li>
                <li>Bankruptcy checks</li>
                <li>CCJs and court decrees check</li>
                <li>Undisclosed address + name check</li>
                <li class="alt1">Full employment reference, including income information</li>
                <li class="alt1">Future employment reference if required</li>
                <li class="alt1">Current landlord or managing agent reference</li>
                <li class="alt2">
                    <strong>A unique guarantee</strong><br />
                    We&rsquo;ll guarantee to remove the tenant from your property if they fail to pay the rent!
                </li>
            </ul>
        </div>
        <div class="connect_product_footer">
            <div class="info">
                <h3>What&rsquo;s special about our checks?</h3>
                <ul>
                    <li>We check that the <strong>banking details</strong> provided by your applicant are for a genuine bank account</li>
                    <li>We conduct a check against HomeLet&rsquo;s own <strong>Default Database</strong> &mdash; this may indicate whether your tenant has not been able to pay their rent in the past</li>
                    <li>We conduct a <strong>Financial Sanctions check</strong>, to make sure that your tenant isn&rsquo;t registered on any of the Government's Asset Freezing lists &mdash; because this could mean they&rsquo;re unable to pay their rent in the future</li>
                </ul>
            </div>
            <div class="more_info">
                <h4>Need more information...</h4>
                <p>If you need more information on our referencing products, why not <a href="/help">contact your account manager</a>.</p>
            </div>
        </div>
    </div>
</div>