<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
       <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Enhance product information',
                'url'   => '/assets/connect/pdf/Enhance_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'You can pass this document to your landlords to let them know what checks are included in our Enhance tenant reference.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
        ));
        ?>
    </div>
</div>