<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">

        <?php if ($this->panelShow) { echo $this->infoPanel($this->panelContent); } ?>

        <?php
        $this->iconLayout(array(
            array(
                'icon'  => 'info',
                'title' => 'Evict instruction form',
                'url'   => '/assets/connect/pdf/Evict_Instruction_Form.pdf',
                'pdf_info'  => array(
                    'description'   => 'This is form you need to complete to request one of our specialist eviction services.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Evict information',
                'url'   => '/assets/connect/pdf/Evict_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'Find out more about our eviction services.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
        ));
        ?>
    </div>
</div>