<div class="form_section">
    <div class="form-sub-section">
        <div class="form-help hidden-xs hidden-sm"></div>
        <h2 class="quaternary-colour">Data protection</h2>

        <div class="section-help">
            <p>
                HomeLet would occasionally like to let you know about our products and services that may be of interest to you.  Don&rsquo;t worry if you decide you don&rsquo;t want to receive this kind of information from us anymore, you can unsubscribe at any time.
            </p>
        </div>

        <div class="agree_statement_marketing_phone_and_post form-group form-group-checkbox">
            <div class="checkbox">
                <?php echo $this->element->dpa_phone_post; ?>
                <label for="dpa_phone_post">
                    If you don&rsquo;t want to be contacted by phone or post about our products and services or with any other information that we feel may be of interest or appropriate to you, then please tick this box.
                </label>
            </div>
        </div>

        <div class="agree_statement_marketing_sms_and_email form-group form-group-checkbox">
            <div class="checkbox">
                <?php echo $this->element->dpa_sms_email; ?>
                <label for="dpa_sms_email">
                    If you would like us to send you information by email or SMS, including the Landlord Lowdown Newsletter which gives you all of the latest news from the lettings industry, please tick this box.
                </label>
            </div>
        </div>

        <div class="agree_statement_details_resale form-group form-group-checkbox">
            <div class="checkbox">
                <?php echo $this->element->dpa_resale; ?>
                <label for="dpa_resale">
                    HomeLet occasionally passes information onto carefully selected third parties, but please be assured that we will never pass your details on without your permission.  If you&rsquo;re happy for HomeLet to pass your details on to third parties, please tick this box.
                </label>
            </div>
        </div>

        <div class="alert alert-info">
            <p>You can contact us at any time to change your preferences.</p>
        </div>
    </div>
</div>