<div class="tenants no-banner">
    <div class="content">
        <h1><span class="tenants"><?php echo $this->message; ?></span></h1>
        <p><?php echo $this->messageExtra; ?></p>
        <ul class="list-unstyled">
            <li><a href="/tenants" class="btn btn-tertiary" role="button">Tenants&rsquo; homepage</a></li>
            <li><a href="/tenants/reference-tracker/login" class="btn btn-tertiary" role="button">Track your application online</a></li>
            <li><a href="/tenants/news" class="btn btn-tertiary" role="button">Tenants&rsquo; blog</a></li>
        </ul>
    </div>
</div>