<div class="landlords">
    <div class="wrapper two-col">
        <div class="content">
    		<div class="warningpromo">
    			<span class="warningpromo-content">
	            	 We are sorry, there seems to be a problem with your card details. Please call our friendly Referencing team on 0845 117 6000 or send an email to <a href="mailto:referencing@homelet.co.uk">referencing@homelet.co.uk</a> and we will be happy to assist you. 
	        	</span>
    		</div>
        </div>
    </div>
</div>