<div class="col-xs-12">
    <div class="breadcrumb"></div>
</div>
<div class="landlords landlords-referencing col-sm-9">
    <div class="content">
        <form action="" method="post" enctype="application/x-www-form-urlencoded" class="main validate">
            <div class="form_section">
                <div class="form-sub-section">
                    <div class="form-help hidden-xs hidden-sm"></div>
                    <h2 class="quaternary-colour main-heading">
                        <span class="help-trigger"><a class="show-form-help"></a></span>
                        <span class="field-help hidden-xs hidden-sm">
                            Please enter your tenant&rsquo;s current landlord details here. If you know their
                            postcode enter it in the postcode box and click on &lsquo;Go&rsquo;, the rest of the address will then
                            auto complete.
                        </span>
                        Current Landlord
                    </h2>

                    <div class="mobile-help section-help section-help-fullwidth">
                        <div class="visible-xs visible-sm">
                            Please enter your tenant&rsquo;s current landlord details here. If you know their
                            postcode enter it in the postcode box and click on &lsquo;Go&rsquo;, the rest of the address will then
                            auto complete.
                        </div>
                    </div>

                    <?php if ($this->form->getDescription()): ?>
                        <div class="alert alert-warning">
                            <ul class="errors">
                                <li><?php echo $this->form->getDescription(); ?></li>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please select the current landlord&rsquo;s title.
                        </div>
                        <?php echo $this->form->personal_title; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter the current landlord&rsquo;s first name.
                        </div>
                        <?php echo $this->form->first_name; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter the current landlord&rsquo;s last name.
                        </div>
                        <?php echo $this->form->last_name; ?>
                    </div>

                    <div class="form-group">
                        <label for="property_postcode" class="required">Postcode</label>
                        <div class="input-group">
                            <?php echo $this->form->property_number_name; ?>
                            <?php echo $this->form->property_postcode; ?>
                            <span class="input-group-btn">
                                <input type="submit" id="postcode_lookup" value="Find address" name="lookup"
                                       onclick="getProperties($('#property_number_name').val(),
                                $('#property_postcode').val(), 'property_postcode', 'property_address'); return false;" class="btn btn-quaternary btn-postcode" />
                            </span>
                        </div>
                        <div id="ins_address_selector">
                            <?php echo $this->form->property_address; ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <?php echo $this->form->telephone_day; ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->form->fax_number; ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->form->telephone_evening; ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->form->email; ?>
                    </div>
                </div>
            </div>

            <?php echo $this->partial('partials/form-navigation.phtml', array('stepNum' => 0, 'stepMax' => 1000)); ?>
        </form>
    </div>
</div>

<div class="landlords col-sm-3">
    <?php echo $this->partial('partials/sidebar.phtml', array('page' => 'current-landlord', 'fractionComplete' => $this->fractionComplete)); ?>
</div>

<div class="clear"></div>