<div class="col-xs-12">
    <div class="breadcrumb"></div>
</div>
<div class="col-sm-9">
    <div class="content">
        <h1>Thank you</h1>
        <p>
            Thank you for completing the form, we have notified the landlord who requested this
            information.
        </p>
        <a class="btn btn-primary pull-right" href="/tenants/">Finish</a>
    </div>
</div>

<div class="col-sm-3">
    <?php echo $this->partial('partials/sidebar.phtml', array('page' => 'email-link-end', 'fractionComplete' => $this->fractionComplete)); ?>
</div>
