<div class="col-xs-12">
    <div class="breadcrumb"></div>
</div>
<div class="col-sm-9">
    <div class="content">
        <h1>Thank you</h1>
        <p>
            Thank you. Your reference number for this enquiry is <?php echo $this->externalId; ?>
            We will inform you by email when your prospective tenant has completed the
            application form.
        </p>
        <a class="btn btn-primary pull-right" href="/landlords/referencing/start">Finish</a>
    </div>
</div>

<div class="col-sm-3">
    <?php echo $this->partial('partials/sidebar.phtml', array('page' => 'email-link-start', 'fractionComplete' => $this->fractionComplete)); ?>
</div>