<div class="col-xs-12">
    <div class="breadcrumb"></div>
</div>
<div class="landlords landlords-referencing col-sm-9">
    <div class="content">
        <form action="" method="post" enctype="application/x-www-form-urlencoded" class="main validate">
            <div class="form_section">
                <div class="form-sub-section">
                    <div class="form-help hidden-xs hidden-sm"></div>
                    <h2 class="quaternary-colour">Login</h2>

                    <div class="section-help">
                        <p>Existing client? Please enter your email and password details</p>
                    </div>

                    <?php if ($this->form->getDescription()): ?>
                        <div class="alert alert-danger">
                            <ul class="errors">
                                <li><?php echo $this->form->getDescription(); ?></li>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <div class="form-group">
                        <?php echo $this->form->email->setAttribs(array('class' => 'form-control'))->render(); ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->form->password->setAttribs(array('class' => 'form-control'))->render(); ?>
                    </div>
                </div>
            </div>

            <?php echo $this->form->submit->setAttribs(array('class' => 'btn btn-quaternary pull-right'))->render(); ?>

            <h3 class="quaternary-colour">Not registered?</h3>
            <a href="/landlords/referencing/register" style="font-size: 13px;">Click here for single-page registration</a>
        </form>
    </div>

</div>

<div class="landlords col-sm-3">
    <?php echo $this->partial('partials/sidebar.phtml',
        array('page' => 'login',
            'fractionComplete' => $this->fractionComplete,
            'hideProgressBar' => true)); ?>
</div>

<div class="clear"></div>