<div class="col-xs-12">
    <div class="breadcrumb"></div>
</div>
<div class="landlords landlords-referencing col-sm-9">
    <div class="content">
        <form id="portfolioProperty" action="" method="post" enctype="application/x-www-form-urlencoded" class="main validate">
            <h2 class="quaternary-colour">Product Selection</h2>
            <p>
                Please enter each tenant's name, select the type of reference/report that you require for
                each tenant (these need not be the same) and decide whether you have the necessary information
                to complete the form now, whether you wish to email the forms to the tenant for completion or
                if you wish to print the forms for your tenant to complete and return to you click here.
            </p>

            <div class="form_section">
                <div class="form-sub-section">
                    <div class="form-help hidden-xs hidden-sm"></div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please select the tenant title.
                        </div>
                        <?php echo $this->form->personal_title; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter the tenant&rsquo;s first name.
                        </div>
                        <?php echo $this->form->first_name; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter the tenant&rsquo;s last name.
                        </div>
                        <?php echo $this->form->last_name; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter a valid email for the tenant. This is only required if you wish for the tenant to add their own details.
                        </div>
                        <?php echo $this->form->email; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter this tenant&rsquo;s share of the rent per month.
                        </div>
                        <?php echo $this->form->share_of_rent; ?>
                    </div>

                    <div class="section-help">
                        <?php if ($this->productHelp == 'rent-guarantee'): ?>
                            <p>Please check the box next to the product you wish to associate with this tenant. To find out more about the products below,
                                please click <a href="/landlords/referencing/rent-guarantee-products" target="_blank">here</a></p>
                        <?php else: ?>
                            <p>Please check the box next to the product you wish to associate with this tenant. To find out more about the products below,
                                please click <a href="/landlords/referencing/product-matrix" target="_blank" id="productMatrix">here</a></p>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="form-sub-section">
                    <h2 class="quaternary-colour">Select a Product</h2>
                    <div class="radio">
                        <?php echo $this->form->product_choice; ?>
                    </div>
                </div>

                <?php if (!empty($this->form->product_duration)): ?>
                    <div class="form-sub-section">
                        <div class="form-group">
                            <?php echo $this->form->product_duration; ?>
                        </div>
                    </div>
                <?php endif; ?>

                <div class="form-sub-section">
                    <div class="form-group">
                        <?php echo $this->form->completion_method; ?>
                    </div>
                </div>
            </div>

            <?php echo $this->partial('partials/form-navigation.phtml', array('stepNum' => 0, 'stepMax' => 1000)); ?>
        </form>
    </div>
</div>

<div class="landlords col-sm-3">
    <?php echo $this->partial('partials/sidebar.phtml', array('page' => 'product-selection', 'fractionComplete' => $this->fractionComplete)); ?>
</div>

<div class="clear"></div>