<div class="col-xs-12">
    <div class="breadcrumb"></div>
</div>
<div class="landlords landlords-referencing col-sm-9">
    <div class="content">
        <form action="" method="post" enctype="application/x-www-form-urlencoded" class="main validate">
            <div class="form_section">
                <div class="form-sub-section">
                    <div class="form-help hidden-xs hidden-sm"></div>

                    <h2 class="quaternary-colour main-heading">
                        <span class="help-trigger"><a class="show-form-help"></a></span>
                        <span class="field-help hidden-xs hidden-sm">
                            Please enter or update your details here.
                        </span>
                        Your details
                    </h2>

                    <div class="mobile-help section-help section-help-fullwidth">
                        <div class="visible-xs visible-sm">
                            Please enter or update your details here.
                        </div>
                    </div>

                    <div class="form-group form-group-checkbox">
                        <p>
                            This facility is for the use of direct landlords only and cannot be used by anyone
                            purchasing Rent Guarantee or a Tenant Reference on behalf of a landlord.
                            By ticking this box, you are confirming you are purchasing this product for your own purposes.
                        </p>
                        <div class="checkbox">
                            <?php echo $this->form->declaration; ?>
                            <label for="declaration">
                                I confirm that I am purchasing this product for my own purposes.
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please select your title.
                        </div>
                        <?php echo $this->form->personal_title; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter your first name.
                        </div>
                        <?php echo $this->form->first_name; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter your last name.
                        </div>
                        <?php echo $this->form->last_name; ?>
                    </div>

                    <div class="form-group">
                        <label for="property_postcode" class="required">Postcode</label>
                        <div class="input-group">
                            <?php echo $this->form->property_number_name; ?>
                            <?php echo $this->form->property_postcode; ?>
                            <span class="input-group-btn">
                                <input type="submit" id="postcode_lookup" value="Find address" name="lookup"
                                       onclick="getProperties($('#property_number_name').val(),
                                $('#property_postcode').val(), 'landlord_postcode', 'property_address'); return false;" class="btn btn-quaternary btn-postcode" />
                            </span>
                        </div>
                    </div>

                    <div class="form-group">
                        <div id="ins_address_selector">
                            <?php echo $this->form->property_address; ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please provide a valid daytime telephone number on which you can be contacted.
                        </div>
                        <?php echo $this->form->telephone_day; ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->form->fax_number; ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->form->telephone_evening; ?>
                    </div>

                    <div class="form-group">
                        <div class="help-trigger"><a class="show-help"></a></div>
                        <div class="field-help quaternary-colour">
                            Please enter a valid email address on which you can be contacted.
                        </div>
                        <?php echo $this->form->email; ?>
                    </div>
                </div>
            </div>

            <?php echo $this->partial('partials/form-navigation.phtml', array('stepNum' => 0, 'stepMax' => 1000)); ?>
        </form>
    </div>
</div>

<div class="landlords col-sm-3">
    <?php echo $this->partial('partials/sidebar.phtml', array('page' => 'prospective-landlord', 'fractionComplete' => $this->fractionComplete)); ?>
</div>
