<?php
if ($this->stepNum == 'dd') {
    // <input type="submit" value="Confirm" id="next" name="next">
    // <input type="submit" value="Back" id="back" name="back">
    ?>
    <input type="submit" value="Back" name="back" class="btn btn-inverse pull-left" />
    <input type="submit" value="Confirm" name="next" class="btn btn-tertiary pull-right" />
    <?php
} elseif ($this->stepNum == 'cc') {
    // <input type="submit" value="Confirm" id="next" name="next">
    // <input type="submit" value="Back" id="back" name="back">
    ?>
    <input type="submit" value="Back" name="back" class="btn btn-inverse pull-left" />
    <input type="submit" value="Confirm" name="next" class="btn btn-tertiary pull-right" />
    <?php
} else {
    if ($this->stepNum < $this->stepMax) {
        // <input type="submit" value="Next" id="next" name="next">
        ?>
        <input type="submit" value="Next" name="next" class="btn btn-tertiary pull-right" />
        <?php
    } else {
        // <input type="submit" value="Buy Me" id="next" name="next">
        ?>
        <input type="submit" value="Purchase" name="next" class="btn btn-tertiary pull-right" />
        <?php
    }
    if ($this->stepNum > 1) {
        // <input type="submit" value="Back" id="back" name="back">
        ?>
        <input type="submit" value="Back" name="back" class="btn btn-inverse pull-left" />
        <?php
    }
} ?>
<div class="clearfix"></div>