<?php echo $this->portfolioQuoteSubHeader(5); ?>
<div class="portfolio col-sm-8">
    <div class="content">
        <h1 class="quaternary-colour">Thank you for requesting cover.</h1>
        <div class="clear"></div>
        <div id="properties">
            <div class="content">
                <form id="portfolioProperty" class="validate" action="" method="post">
                    <p>Your Quote Number: <strong class="quote_number quaternary-colour"><?php echo $this->refNo;?></strong></p>
                    <p>We will endeavour to contact you within the next 2 working hours to confirm the quotation and arrange payment.<br />
                    Please note cover can only commence once payment details have been confirmed.</p>
                 </form>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-4">
    <div class="panel panel-primary">
        <h3>Need help?</h3>
        <p class="large quaternary-colour">Call: 0845 117 6000</p>
        <p>We&rsquo;re open from:</p>
        <table class="table table-condensed">
            <tr>
                <td>Weekdays</td>
                <td>8:30am - 6:30pm</td>
            </tr>
            <tr>
                <td>Saturday</td>
                <td>9:30am - 1:00pm</td>
            </tr>
        </table>
        <p>We&rsquo;re always happy to help.</p>
    </div>
</div>