Initial Disclosure
Please read the following important information before proceeding with your application. You may choose to print the information by pressing the print key. Click 'Next' to continue with the policy application

 
Which service will we provide you with?

    You will not receive advice or a recommendation from us.

    You may be asked some questions to narrow down the selection of products that we will provide details on. You will then need to make your own choice about how to proceed.

When we arrange or administer for you a contract of insurance for any of the products listed below, then our service is part of a separate contract with you. Our contract with you is separate and distinct from the contract of insurance you have with the Insurer(s).

Whose products do we offer?

We offer the following products. Please let us know if you would like to know which insurers we use. Listed below is whether we use one or more insurer for a particular product. We are not under a contractual obligation to use any specific insurer.
Retail

Tenants Contents Insurance
	

From a limited range of Insurers
Commercial
Landlords Buildings Insurance 	From a limited range of Insurers
Landlords Contents Insurance 	From a limited range of Insurers
Landlords Emergency Assistance Insurance 	From a Single Insurer
Landlords Rent Guarantee Insurance (Prestige, Xpress, Extra & Advantage) 	From a Single Insurer
Landlords Rent Guarantee Insurance (Absolute) 	From a Single Insurer
Landlords Legal Expenses Insurance 	From a Single Insurer
 
Commissions

You are entited at any time to request information regarding any commission which we or HomeLet may have received for placing your insurance business

    By writing to:

    Barbon Insurance Group Limited
    Hestia House
    Unit 2 Edgwest Road
    Lincoln
    LN6 7EL

     

Who regulates us?

Homelet is a trading name of Barbon Insurance Group Limited which is authorised and regulated by the Financial Conduct Authority for insurance mediation. Registered in England number 3135797. Registered office address: Hestia House, Edgewest Road, Lincoln, LN6 7EL. Barbon Insurance Group Limited's FCA Register number is 308724.

 
The Financial Conduct Authority (FCA)

The FCA is the independent statutory watchdog that regulates financial services.

Our permitted business is:

    Arranging general insurance contracts.


You can check this on the FCA Register by:

    Visiting the FCA's website www.fsa.gov.uk/register

    Contacting the FCA by telephone on 0845 606 1234


What will you have to pay for our services?
These fees apply to the contract you have with us to arrange and administer your insurance policies:

    If you choose to pay your premium by monthly payments, you will be charged a fee of &pound;2.99 (&pound;1.99 for Tenants insurance) each month in addition to your premium amount.

    For cancellations and mid-term adjustments we may charge an administration fee of &pound;30.00 for effecting those changes on your behalf.

    For Tenants Contents Insurance only, you will be charged a &pound;10 fee for selecting a 6 month policy.

    You will receive a quotation that will tell you about any other fees relating to any particular insurance policy.

    Our Rent Guarantee products purchased in conjunction with a tenant reference (Xpress, Extra or Advantage) cannot be paid for monthly, they are also fixed term contracts and are not subject to cancellation.


Ownership

Caley Limited owns 100% of the share capital of Barbon Insurance Group Limited and Propgen Insurance Limited.

 
Interest

We will retain any interest earned on client money held by them for their own use.

 
What to do if you have a complaint

If you wish to register a complaint, please contact us:

    By writing to:

Barbon Insurance Group Limited
Hestia House
Unit 2 Edgewest Road
Lincoln
LN6 7EL


    By telephone: 0845 117 6000


We will acknowledge your complaint within 5 working days and detail our complaints procedure to you. If we are unable to settle your complaint you may be entitled to refer it to the Financial Ombudsman Service:

    By post:

The Financial Ombudsman Service
South Quay Plaza
183 Marsh Wall
London
E14 9SR

    By telephone: 0845 080 1800


Are we covered by the Financial Services Compensation Scheme (FSCS)?

We are covered by the FSCS. You may be entitled to compensation from the scheme if we cannot meet our obligations. This depends on the type of business and the circumstances of the claim. Propgen Insurance Limited is not covered by the FSCS

Further information about compensation scheme arrangements is available from the FSCS:

    By post:

Financial Services Compensation Scheme
7th floor, Lloyds Chambers
Portsoken Street
London
E1 8BN

    By telephone: 020 7892 7300


Cancellation of your policy

If you commence one of our insurance policies and decide that it is not suitable within the first 14 days after you take out the policy then we will refund your premium in full. Please contact us by telephone, fax or post. Our Rent Guarantee products purchased in conjunction with a tenant reference (Xpress, Extra or Advantage) cannot be paid for monthly, they are fixed term contracts and are not subject to cancellation.

 
Policies paid by monthly credit card or monthly Direct Debit

You can cancel your policy by advising us by telephone, fax or post and we will cancel the policy for you. We will not refund your premium for the period between the date that you ask for the policy to be cancelled and the date that the next monthly payment is due.

Cover ceases on the date that you request cancellation.

 
Policies paid annually by cheque or credit card

You can cancel your policy by advising us by telephone, fax or post and we will cancel the policy for you subject to a cancellation fee of &pound;30.00. The refund will be calculated from the date in the month when the policy was started and will be based on 1/12 of the annual premium for each full month of cover remaining at the time of cancellation. We cannot make a refund where the policy has less than two months before expiry or where a claim has been made.

We will pay refunds to the credit card account or by BACS transfer to the bank account that you nominate at cancellation. You must provide us with these account details.

Cover ceases on the date that you request cancellation.

 
Premiums

We hold insurance money as an agent of the insurance undertaking with whom your contract of insurance is placed. This agency agreement is in respect of all premiums received from you, all refunds of premiums due to you, as well as claim payments due to you. This means that once your premium has been paid to Barbon Insurance Group Limited it is deemed to have been paid to the insurer.

Client money may for the purpose of a transaction be transferred to another person such as another broker through whom the insurance contract has been placed.

Barbon Insurance Group Limited will deduct any commission entitlements before paying premiums to insurers.

 
Disclosure of Material Facts

Insurers must be kept informed of all material facts, which change or arise after the insurance is first taken out and/or last renewed. This is important because if such facts are not disclosed your insurance cover may not protect you in the event of a claim.

Material Facts are those that are likely to influence an insurer in the assessment or acceptance of a risk and it is essential that you disclose them. If you are in doubt whether a fact is material, you should disclose it, since failure to do so could invalidate your policy.

 
Confidentiality

We are registered under the Data Protection Act 1998 and we undertake to comply with the Act in all our dealings with your personal data. Under the Act you have the right to see personal information we hold about you on your records.

We must advise you that information supplied may be held on computer and passed to other insurers for claims purposes. Insurers pass information to the Claims and Underwriting exchange (CUE) database operated by Insurance Database Services Ltd. The aim is to help them check information provided and also to prevent fraudulent claims. When you tell us about an incident (such as fire, water damage or theft) which may or may not give rise to a claim, the insurers will send information relating to it to the database.

It is a condition of renewing your Policy that you agree to this information being passed to the Insurance Database Services Ltd and that Insurance Database Services Ltd may pass to your insurer information that has been received from other insurers involving anyone insured under the policy.

 
Copies of documentation

You should keep a record of all information supplied to us for this insurance.

 
Awareness of policy terms

When a policy is issued you should read it carefully. The policy together with the schedule and any certificate of insurance forms the basis of the contract of insurance. If you are in any doubt over any of the policy terms or conditions please contact Barbon Insurance Group Limited immediately.

 
Useful contact details

Barbon Insurance Group Limited

Internet: www.homelet.co.uk

Telephone: 0845 117 6000

Financial Conduct Authority

Internet: www.fsa.gov.uk

Telephone: 0845 606 1234

Financial Ombudsman Service

Internet: www.financial-ombudsman.org.uk

Telephone: 0845 080 1800

 
Statement of Demands and Needs

If you have purchased our Buildings and/or our Contents Policy then these products meet the needs of those seeking an indemnity against loss or damage to their property and/or contents and these needs are met now and for the term of your policy.

If you have purchased a Legal Expenses, Rent Guarantee or Emergency Assistance policy then these products meet the demands and needs of those seeking an indemnity against losses arising as a result of you letting your residential property. These needs are met now and for the term of your policy.

 
Homelet - Initial Disclosure Document
V6.4 01/07/2010
