<?php echo $this->portfolioQuoteSubHeader(5); ?>
<div class="portfolio col-sm-8">
    <div class="content">
        <h1 class="quaternary-colour">Referred to Underwriting</h1>
        <div class="clear"></div>
        <div id="properties">
            <div class="content">
                <form id="portfolioProperty" class="validate" action="" method="post">
                    Your Quote Number: <?php echo $this->refNo;?><br />
                    You have been referred to our Underwriting Department and they have been notified by e-mail with details of your application.<br />
                    You will be contacted shortly as regards to your application.<br />
                    If you have any queries, please phone <strong>0845 117 6000</strong><br />
                </form>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-4">
    <div class="panel panel-primary">
        <h3>Need help?</h3>
        <p class="large quaternary-colour">Call: 0845 117 6000</p>
        <p>We&rsquo;re open from:</p>
        <table class="table table-condensed">
            <tr>
                <td>Weekdays</td>
                <td>8:30am - 6:30pm</td>
            </tr>
            <tr>
                <td>Saturday</td>
                <td>9:30am - 1:00pm</td>
            </tr>
        </table>
        <p>We&rsquo;re always happy to help.</p>
    </div>
</div>