<?php

switch($this->options['output']) {

    case 'thumbnailUrl':
        ?>http://img.youtube.com/vi/<?php echo $this->videoId; ?>/hqdefault.jpg<?php
        break;

    case 'thumbnail':
        ?>
        <div class="video thumbnail" style="width: <?php echo $this->width; ?>px; height: <?php echo $this->height; ?>px;">
            <img src="http://img.youtube.com/vi/<?php echo $this->videoId; ?>/hqdefault.jpg" alt="YouTube video thumbnail" />
            <div class="overlay">
                <img src="/assets/cms/images/play-button-overlay.png" alt="" />
            </div>
        </div>
        <?php
        break;

    case 'video':
    default:
        ?>
        <iframe class="video" title="YouTube video player" width="<?php echo $this->width; ?>" height="<?php echo $this->height; ?>" src="http://www.youtube.com/embed/<?php echo $this->videoId; ?>?<? echo (($this->options['showControls']) ? '' : 'controls=0&amp;'); ?>rel=0" frameborder="0" allowfullscreen></iframe>
        <?php
        break;

}