<?php

switch($this->options['output']) {

    case 'thumbnailUrl':
        // Solution from http://stackoverflow.com/questions/1361149/get-img-thumbnails-from-vimeo
        // TODO: Cache result
        $hash = unserialize(file_get_contents("http://vimeo.com/api/v2/video/{$this->videoId}.php"));
        $thumbnail = $hash[0]['thumbnail_large'];
        echo $thumbnail;
        break;

    case 'thumbnail':
        // Solution from http://stackoverflow.com/questions/1361149/get-img-thumbnails-from-vimeo
        // TODO: Cache result
        $hash = unserialize(file_get_contents("http://vimeo.com/api/v2/video/{$this->videoId}.php"));
        $thumbnail = $hash[0]['thumbnail_large'];
        ?>
        <div class="video thumbnail" style="width: <?php echo $this->width; ?>px; height: <?php echo $this->height; ?>px;">
            <img src="<?php echo $thumbnail; ?>" alt="Vimeo video thumbnail" />
            <div class="overlay">
                <img src="/assets/cms/images/play-button-overlay.png" alt="" />
            </div>
        </div>
        <?php
        break;

    case 'video':
    default:
        ?>
        <iframe class="video" title="Vimeo video player" src="http://player.vimeo.com/video/<?php echo $this->videoId; ?>?title=0&amp;byline=0&amp;portrait=0" width="<?php echo $this->width; ?>" height="<?php echo $this->height; ?>" frameborder="0"></iframe>
        <?php
        break;

}