<font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#0C2F6B">
    Dear [name], <br />
    <br />
    Thank you for visiting our website and requesting a quote for your tenant’s contents insurance. Protect your possessions, deposit, the things that you take out and about and those extra special items with <font color="#E60E64">Tenant’s Content’s Insurance+</font> today.<br />
    <br />
    Simply view your quote online at <a href="/tenants">homelet.co.uk/tenants</a> by logging in with your username and password.<br />
    <br />
    Then click <font color="#E60E64">BUY NOW</font> – it’s as simple as that!<br />
    <br />
    Once you’ve logged in you can view your quotes, make changes to your quotes and buy a policy.<br />
    <br />
    If you have any questions why not call one of our friendly customer services advisors on <font color="#E60E64">0845 117 6000</font> from 8.30am-8pm Monday to Friday and 9.30am-1pm Saturday.<br />
    <br />
    If you have trouble getting through to the number stated above then please call <font color="#E60E64">01522 838514.</font><br />
    <br />
    So what are you waiting for? Protect your <font color="#E60E64">contents</font> and <font color="#E60E64">deposit</font> today with HomeLet and you can be rest assured that if something unexpected happens we’ve got your covered!<br />
    <br />
    <br />
    Many thanks<br />
    <br />
    HomeLet<br />
</font>