<div class="wrapper two-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2>Advantage</h2>
        <p>
            HomeLet Advantage is an exciting lifestyle discount scheme created esecially for HomeLet Premier and PremierPlus customers. <br />
            Advantage will help set you apart as &lsquo;an employer of choice&rsquo;. It can help with staff retention and may also help you to attract more staff in a climate at no additional cost to you...
        </p>
        <p>
            It&rsquo;s a great incentive for staff and offers you access to exclusive discounts of up to 40% off thousands of products and services.
        </p>

        <div class="steel-box">
            <h3>What can Advantage benefits do for you?</h3>
            <p>Advantage will save you money on purchases like:</p>
            <ul>
                <li>Office Equipment &ndash; you&rsquo;ll be surprised what&rsquo;s on there!</li>
                <li>Office Furniture &ndash; Always check here first for the latest discount</li>
                <li>Electronic Goods &ndash; Need a new dishwasher or the latest smart TV?</li>
                <li>Staff promotions &ndash; incentivise your staff with vouchers and prizes</li>
                <li>Holidays &ndash; Family UK Cottage holidays and Thomas Cook vouchers</li>
                <li>Days out &ndash; Why not take a trip to Alton Towers or Legoland?</li>
            </ul>
        </div>

        <p>
            <strong>Get access to Advantage discounts and start saving today by call us on 0845 113 2634.</strong>
        </p>

        <div id="testimonial">
            <p>
            <span class="quote"></span>
                I saved hundreds of pounds on a weekend break I booked using Advantage discounts; even the likes of day trips out with the kids in the Summer Holidays are less expensive thanks to HomeLet Advantage.&rsquo;
            </p>
            <p class="source">John Chambers <br />Stamford Independent Property Management</p>
        </div>
    </div>
    <div class="sidebar">
        <?php echo $this->premierSideBar($this->product); ?>
    </div>
</div>
