<div class="wrapper two-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2>PremierPlus customers...</h2>
        <p>
            As a PremierPlus Customer you have access to a choice of services which are designed
            not only to protect your business, but services to help accelerate the financial growth of
            your business. With a huge range of staff benefits available for your employees too, you&rsquo;ll
            be able to ensure a happy workforce.
        </p>

        <div class="steel-box">
            <h3>Here&rsquo;s a reminder of your PremierPlus benefits:</h3>
            <ul>
                <li>Discounted Referencing and Rent Guarantee prices</li>
                <li>Zero excess on first Professional Indemnity claim</li>
                <li>Market leading rates of commission on new business and renewals</li>
                <li>Advantage benefits package</li>
                <li>Discounted NALS membership</li>
                <li>Discounted Office Insurance</li>
                <li>10% off annual subscription to Property Drum Magazine</li>
                <li>Vizzihome - Find out exactly what&rsquo;s happening in your market place</li>
                <li>BusinessCare - Free access to professional legal advice 24/7</li>
            </ul>
            <p>
                Remember, you can login to your exclusive BusinessCare, Vizzihome or
                Advantage benefits accounts by clicking in the links to the right.
            </p>
            <p>
                If you need help or advise with any of your PremierPlus benefits you can call
                us on <strong>0845 113 2634</strong> or you can contact your HomeLet representative.
            </p>
        </div>

        <div id="testimonial">
            <p>
            <span class="quote"></span>
                Not satisfied with relying on what we thought we knew about the market we operate in, we thought we&rsquo;d make use of our PremierPlus benefits and assess the market in our area to determine our market share &ndash; it turns out it was bigger than we thought!&rdquo;
            </p>
            <p class="source">Gordon Drennan<br />ME Lettings</p>
        </div>
    </div>
    <div class="sidebar">
        <?php echo $this->premierSideBar('premplus'); ?>
    </div>
</div>
