<div class="wrapper two-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2>Upgrade today, and grow your lettings business</h2>
        <p>
            To help your business grow we&rsquo;ve developed a unique, exclusive benefits package called
            PremierPlus. Find out why some of the strongest Letting Agent brands in the UK are
            HomeLet PremierPlus customers.
        </p>

        <div class="steel-box">
            <ul>
                <li>Advantage &ndash; Discounts off Office furniture, rewards for your staff, additional staff benefits and enhanced status</li>
                <li>Discounted Office Insurance</li>
                <li>Discount off Property Drum magazine subscription</li>
                <li>Zero Excess on the first claim for Professional Indemnity Insurance</li>
                <li>Market leading rates of commission on new business and renewals &ndash; a generous 25%</li>
                <li>Reductions on prices for referencing and Rent Guarantee</li>
                <li>Discounted NALS membership</li>
                <li>Access to BusinessCare &ndash; free legal advice available 24/7</li>
                <li>Vizzihome &ndash; market intelligence at your fingertips</li>
            </ul>
        </div>

        <p class="prem-bold">
            By investing in PremierPlus you&rsquo;ll be able to keep your finger on the pulse of the
            lettings industry all day every day &ndash; with information at your finger tips and
            professional advice when you need it.
        </p>

        <div id="testimonial">
            <p>
            <span class="quote"></span>
                It goes without saying that if you&rsquo;re a small business, particularly in
                such difficult economic climate, that the support BusinessCare can
                give you is unrivalled. Thank goodness we&rsquo;ve not had the need to use
                the service in full as yet, but the helpline which is available 24/7 for
                even the smallest query is brilliant!&rdquo;
            </p>
            <p class="source">Rob Murray<br />Murray Residential Lettings</p>
        </div>
    </div>
    <div class="sidebar">
        <?php echo $this->premierSideBar('standard'); ?>
    </div>
</div>
