<div class="wrapper two-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2>Premier customers...</h2>
        <p>
            As a Premier Customer you have access to a choice of services which are designed not
            only to protect your business, but services to help accelerate the financial growth of your
            business. With a huge range of staff benefits available for your employees too, you&rsquo;ll be
            able to ensure a happy workforce.
        </p>

        <div class="steel-box">
            <h3>Here&rsquo;s a reminder of your Premier benefits:</h3>
            <ul>
                <li>Discounted Referencing and Rent Guarantee prices</li>
                <li>Zero excess on first Professional Indemnity claim</li>
                <li>Market leading rates of commission on new business and renewals</li>
                <li>Advantage benefits package</li>
                <li>Discounted NALS membership</li>
                <li>Discounted Office Insurance</li>
                <li>10% off annual subscription to Property Drum Magazine</li>
            </ul>
            <h3>Make the most of PremierPlus</h3>
            <p>By upgrading your account and investing in PremierPlus you&rsquo;ll be able to
                keep your finger on the pulse of the lettings industry all day every day – with
                information at your finger tips and professional advice when you need it.
            </p>
            <p>
                As a PremierPlus customer, you&rsquo;ll receive all the benefits of our Premier
                customers, but with these additional extras:
            </p>
            <ul>
                <li>Vizzihome &ndash; Find out exactly what&rsquo;s happening in your market place</li>
                <li>BusinessCare &ndash; Free access to professional legal advice 24/7</li>
            </ul>
        </div>

        <div id="testimonial">
            <p>
            <span class="quote"></span>
                It goes without saying that if you&rsquo;re a small business, particularly in
                such difficult economic climate, that the support BusinessCare can
                give you is unrivalled. Thank goodness we&rsquo;ve not had the need to use
                the service in full as yet, but the helpline which is available 24/7 for
                even the smallest query is brilliant!
            </p>
            <p class="source">Rob Murray<br />Murray Residential Lettings</p>
        </div>
    </div>
    <div class="sidebar">
        <?php echo $this->premierSideBar('premier'); ?>
    </div>
</div>
