<div class="wrapper two-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2>BusinessCare</h2>
        <p>
            Business Care provides HomeLet <span class="prem-bold">PremierPlus</span> customers with free access to high quality and effective business information and support online and a 24/7 telephone helpline direct to legal experts and access to an online bank of the most commonly used legal documents you need.
        </p>

        <div class="steel-box">
            <p>The comprehensive online legal library gives access to sample forms, checklists and guidance on the following areas:</p>
            <ul>
                <li>Employment</li>
                <li>Health and Safety</li>
                <li>Intellectual Property</li>
                <li>Debts and Debt Recovery</li>
                <li>Property</li>
                <li>E-Commerce</li>
                <li>Employee Health Management</li>
                <li>Tax and VAT</li>
            </ul>
            <p>
                You&rsquo;ll also have access to qualified legal professionals, who act for free as &lsquo;real time&rsquo; document checkers to ensure that documents are legally binding &ndash; taking the hassle out of compliance.
            </p>
        </div>

        <p>
            <strong>Get access to BusinessCare, call us today on 0845 113 2634.</strong>
        </p>

        <div id="testimonial">
            <p>
            <span class="quote"></span>
                It goes without saying that if you&rsquo;re a small business, particularly in such difficult economic climate, that the support BusinessCare can give you is unrivalled. Thank goodness we&rsquo;ve not had the need to use the service in full as yet, but the helpline which is available 24/7 for even the smallest query is brilliant!&rdquo;
            </p>
            <p class="source">Rob Murray <br />Murray Residential Lettings</p>
        </div>
    </div>
    <div class="sidebar">
        <?php echo $this->premierSideBar($this->product); ?>
    </div>
</div>
