<div class="wrapper two-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2>Vizzihome</h2>
        <p>
            Imagine you could have access to every piece of information about what’s going on with lettings in your region, at the touch of a button?
        </p>
        <p>
            With PremierPlus from HomeLet you can have exactly that. With Vizzihome you can;
        </p>

        <ul>
            <li>View weekly data on your competitors in lettings and compare your market share</li>
            <li>Identify landlords in your area that are likely to change agents</li>
            <li>Create targeted marketing campaigns in your area</li>
            <li>Track and monitor sales and marketing campaigns</li>
        </ul>

        <div class="steel-box">
            <p>Vizzihome usually costs &pound;50 per office per month, but HomeLet PremierPlus customers have unlimited access to Vizzihome lettings included in your subscription saving you £720 a year!</p>
        </div>

        <p>
            <strong>Get access to Vizzihome, call us today on 0845 113 2634.</strong>
        </p>

        <div id="testimonial">
            <p>
            <span class="quote"></span>
                Not satisfied with relying on what we thought we knew about the market we operate in, we thought we&rsquo;d make use of our PremierPlus benefits and assess the market in our area to determine our market share &ndash; it turns out it was bigger than we thought!&rdquo;
            </p>
            <p class="source">Gordon Drennan<br />ME Lettings</p>
        </div>
    </div>
    <div class="sidebar">
        <?php echo $this->premierSideBar($this->product); ?>
    </div>
</div>
