<?php
echo $this->subHeader('global,careers,corporate', 'corporate');
?>
<div class="corporate">
    <div class="wrapper one-col">
		<div class="content">
            <?php
            if (count($this->errors)>0)
            {
                ?>
                <p class="error">Please fill in all required fields</p>
                <?php
            }
            ?>
            <p>To apply for the position of <strong><?php echo $this->title; ?></strong> please fill in the form below.</p>
            <form class="apply_form" action="" enctype="multipart/form-data" method="post">
                <input type="hidden" name="position" value="<?php echo $this->title; ?>" />
                <input type="hidden" name="job-id" value="<?php echo $this->id ?>" />
                <p>
                    <label for="name">Name *</label>
                    <input type="text" name="name" value="<?php echo $this->name; ?>" />
                    <?php if (isset($this->errors['name'])) { ?><span class="error">Please enter your name</span><?php } ?>
                </p>
                <p>
                    <label for="tel">Contact Telephone *</label>
                    <input type="text" name="tel"  value="<?php echo $this->tel; ?>"/>
                    <?php if (isset($this->errors['tel'])) { ?><span class="error">Please enter a contact number</span><?php } ?>
                </p>
                <p>
                    <label for="email">Email Address *</label>
                    <input type="text" name="email" value="<?php echo $this->email; ?>" />
                    <?php if (isset($this->errors['email'])) { ?><span class="error">Please enter a valid email address</span><?php } ?>
                </p>
                <p>
                    <label for="enquiry">Why does this position interest you? *</label>
                    <textarea name="enquiry"><?php echo $this->enquiry; ?></textarea>
                    <?php if (isset($this->errors['enquiry'])) { ?><span class="error">Please tell us why this position interests you</span><?php } ?>
                </p>
                <p>
                    <label for="cv_file">Upload your CV *</label>
                    <input type="file" name="cv_file" />
                    <?php if (isset($this->errors['cv_file'])) { ?><span class="error">Please upload a valid CV document</span><?php } ?>
                </p>
                <input type="submit" value="Submit &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;" />
                <div style="clear:both;"></div>
            </form>
            <div id="contact-message<?php echo $this->id ?>">
            </div>
		</div>
		<div class="clear"></div>
	</div>
</div>