<form action="" method="post" class="editaccount form-horizontal">
    <div class="form-group">
        <label class="col-sm-3 control-label">Email</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="<?php echo $this->element->email->getValue(); ?>" disabled />
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">Title</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="<?php echo $this->element->title->getValue(); ?>" disabled />
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">First Name</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="<?php echo $this->element->first_name->getValue(); ?>" disabled />
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">Last Name</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" value="<?php echo $this->element->last_name->getValue(); ?>" disabled />
        </div>
    </div>

    <div class="form-group">
        <label for="existing_password" class="col-sm-3 required control-label">Existing Password</label>
        <div class="col-sm-9">
            <?php echo $this->element->existing_password; ?>
        </div>
    </div>

    <div class="form-group">
        <label for="password" class="col-sm-3 optional control-label">New Password</label>
        <div class="col-sm-9">
            <?php echo $this->element->password; ?>
        </div>
    </div>

    <div class="form-group">
        <label for="confirm_password" class="col-sm-3 optional control-label">Confirm New Password</label>
        <div class="col-sm-9">
            <?php echo $this->element->confirm_password; ?>
        </div>
    </div>

    <div class="form-group">
        <label for="security_question" class="col-sm-3 required control-label">Security Question</label>
        <div class="col-sm-9">
            <?php echo $this->element->security_question; ?>
        </div>
    </div>

    <div class="form-group">
        <label for="security_answer" class="col-sm-3 required control-label">Answer</label>
        <div class="col-sm-9">
            <?php echo $this->element->security_answer; ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            <?php echo $this->element->submit; ?>
        </div>
    </div>
</form>
