<li id="<?php echo $this->id ?>">
    <span class="menu_title">
        <?php echo $this->link ?>
    </span><span class="menu_url">
        <?php echo $this->url ?>
    </span><span class="menu_controls">
        <a class="ico-edit" href="/cms-admin/edit-menu?id=<?php echo $this->id ?>"></a>&nbsp;
        <a class="ico-delete" href="/cms-admin/delete-menu?id=<?php echo $this->id ?>"></a>
    </span>
</li>