<h2 class="quaternary-colour">Your Premium</h2>

<?php if (!isset($this->premiums['totalGrossAnnualPremium'])):
    // We don't have any premiums to show - must be on a new quote at step 1
    $monthlyPremium = '-';
    $annualPremium = '-';
    $monthlyIPT = '-';
    $annualIPT = '-';
    $monthlyFees = '-';
    $annualFees = '-';
    $monthlyPayable = 'N/A';
    $annualPayable = 'N/A';
else:
    $monthlyPremium = '&pound;' . number_format($this->premiums['totalGrossMonthlyPremium'] + $this->premiums['totalGrossMonthlyIPT'], 2);
    $annualPremium = '&pound;' . number_format($this->premiums['totalGrossAnnualPremium'] + $this->premiums['totalGrossAnnualIPT'], 2);
    $monthlyIPT = '(&pound;' . number_format($this->premiums['totalGrossMonthlyIPT'], 2) . ')';
    $annualIPT = '(&pound;' . number_format($this->premiums['totalGrossAnnualIPT'], 2) . ')';
    $monthlyFees = '&pound;' . number_format($this->fees['landlords_insurance_plus_monthly_admin'], 2);
    $annualFees = '&pound;' . number_format($this->fees['landlords_insurance_plus_yearly_admin'], 2);
    $monthlyPayable = '&pound;' . number_format($this->premiums['totalGrossMonthlyPremium'] + $this->premiums['totalGrossMonthlyIPT'] + $this->fees['landlords_insurance_plus_monthly_admin'], 2);
    $annualPayable = '&pound;' . number_format($this->premiums['totalGrossAnnualPremium'] + $this->premiums['totalGrossAnnualIPT'] + $this->fees['landlords_insurance_plus_yearly_admin'], 2);
endif; ?>

<table id="premium_summary" class="table table-bordered">
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th class="number">Monthly</th>
            <th class="number">Annually</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                Your Premium
            </td>
            <td class="number">
                <span class="monthlyPremiumQuote"><?php echo $monthlyPremium; ?></span>
            </td>
            <td class="number">
                <span class="annualPremiumQuote"><?php echo $annualPremium; ?></span>
            </td>
        </tr>
        <tr class="ipt">
            <td>
                IPT Included @ 6%
            </td>
            <td class="number">
                <span class="monthlyIpt"><?php echo $monthlyIPT; ?></span>
            </td>
            <td class="number">
                <span class="annualIpt"><?php echo $annualIPT; ?></span>
            </td>
        </tr>
        <tr>
            <td>
                Monthly Admin Fee
            </td>
            <td class="number">
                <span class="monthlyAdminFee"><?php echo $monthlyFees; ?></span>
            </td>
            <td class="number">
                <span class="annualAdminFee"><?php echo $annualFees; ?></span>
            </td>
        </tr>
        <tr class="payable">
            <td>
                <strong class="quaternary-colour">Amount Payable</strong>
            </td>
            <td class="number">
                <span class="monthlyPayable quaternary-colour"><?php echo $monthlyPayable; ?></span>
            </td>
            <td class="number">
                <span class="annualPayable quaternary-colour"><?php echo $annualPayable; ?></span>
            </td>
        </tr>
    </tbody>
</table>