<?php
if (count($this->errors) > 0) {
    ?>
    <p>There<?php echo ((count($this->errors) == 1) ? '\'s' : ' are'); ?> only <?php echo count($this->errors); ?> mandatory field<?php echo ((count($this->errors) == 1) ? '' : 's'); ?> left to complete in this step:</p>
    <ul class="errorList">
        <?php
        foreach ($this->errors as $error) {
            foreach ($error as $key => $value) {
                ?>
                <li><?php echo $value; ?></li>
                <?php
            }
        }
        ?>
    </ul>
    <?php
}
?>