<style type="text/css">
    body {
        margin:0;
        padding:0;
    }

    img {
        border: none;
    }

    h1,
    *[class="reference"] {
        font-size: 26px;
        line-height: 26px;
        font-weight: normal;
    }

    h1 {
        color: #0d366c;
    }

    h2 {
        font-size: 22px;
        color: #0d366c;
        font-weight: normal;
        margin-top: 0;
    }

    h3 {
        font-size: 17px;
        font-weight: normal;
        margin: 0 0 5px 0;
    }

    a {
        color: #ff6d1b !important;
        text-decoration: underline;
    }

    a img {
        text-decoration: none !important;
    }

    ul {
        padding-left: 20px;
    }

    *[class="reference"] {
        display: block;
    }

    table {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 15px;
    }

    *[class="main-image"],
    .main-image {
        width: 560px !important;
        height: auto !important;
    }

    *[class="table"] {
        width: 600px;
    }

    *[class="faded"] {
        line-height:19px;
        font-weight:normal;
        color:#444444;
    }

    *[class="spacer"] td {
        background-color: #ffffff;
    }

    *[class="disclaimer"],
    *[class="disclaimer"] a {
        font-size: 10px !important;
        color: #808080;
        font-weight: bold;
    }

    *[class="additional"],
    *[class="additional"] a {
        font-size:10px !important;
        line-height:12px !important;
        font-weight:normal;
        color:#808080
    }

    *[class="picture-frame"],
    *[class="landlord-houses"] {
        vertical-align: bottom;
    }
    *[class="pod"] td {
        background-color: #e5eaed;
    }

    *[class="tick"] {
        float: left;
        margin-right: 10px;
    }

    *[class="right"] {
        text-align: right;
    }

    *[class="hidden-mobile"] {
        display: block;
    }

    *[class="visible-mobile"] {
        display: none;
    }

    *[class="larger"] {
        font-size: 17px;
    }

    /* sub-600px for mobile. */
    @media (max-width: 599px) {
        h1,
        *[class="reference"] {
            font-size:16px !important;
            line-height:16px;
        }

        *[class="main-image"] {
            width: 100% !important;
        }

        *[class="hidden-mobile"],
        *[class="landlord-houses"],
        *[class="picture-frame"] {
            display: none;
        }

        *[class="visible-mobile"] {
            display:block;
        }

        *[class="table"],
        *[class="content"],
        *[class="collapsed"],
        *[class="wide-mobile"],
        *[class="spacer"] {
            font-size:15px;
            width: 100% !important;
        }

        *[class="collapsed"] {
            height: auto !important;
        }
    }
</style>