<link href="/assets/cms/css/video.css" media="screen" rel="stylesheet" type="text/css" />
<?php

$thisUrl = $this->serverUrl() . Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();

echo $this->subHeader($this->pageStyling, $this->pageStyling);

?>
<script type="text/javascript">
$(function() {
    // Add popups for social links
    $('.social-share a').click(function(e) {
        e.preventDefault();
        window.open($(this).attr('href'), 'popup', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');
    });
});
</script>
<div class="<?php echo $this->pageStyling; ?>">
    <div class="wrapper one-col">
        <div class="content">

            <h1><span class="<?php echo $this->pageStyling; ?>"><?php echo $this->meta['videoTitle1']; ?></span></h1><br />

            <div class="clear"></div>

            <?php echo $this->content; ?>

            <div class="video"><?php
                echo $this->embeddedVideo(
                    $this->meta['video1'],
                    860,
                    array(
                        'showControls' => true
                    )
                );
            ?></div>

            <div class="social-share">
                <ul>
                    <li><a class="facebook" href="https://www.facebook.com/sharer/sharer.php?s=100&p[title]=<?php echo htmlentities($this->meta['videoTitle1']); ?>&p[summary]=Check out the &quot;<?php echo htmlentities($this->meta['videoTitle1']); ?>&quot; video on HomeLet.&p[url]=<?php echo $thisUrl; ?>&p[images][0]=<?php echo $this->embeddedVideo($this->meta['video1'], 860, array('output' => 'thumbnailUrl')); ?>" target="_blank" title="Share &quot;<?php echo htmlentities($this->meta['videoTitle1']); ?>&quot; on Facebook" rel="nofollow"> </a></li>

                    <li><a class="twitter" href="https://twitter.com/share?text=Check out the &quot;<?php echo htmlentities($this->meta['videoTitle1']); ?>&quot; video on @HomeLet&amp;url=<?php echo $thisUrl; ?>&amp;hashtags=HomeLet" target="_blank" title="Share &quot;<?php echo htmlentities($this->meta['videoTitle1']); ?>&quot; on Twitter" rel="nofollow"> </a></li>

                    <li><a class="googleplus" href="https://plus.google.com/share?url=<?php echo $thisUrl; ?>" target="_blank" title="Share &quot;<?php echo htmlentities($this->meta['videoTitle1']); ?>&quot; on Google+" rel="nofollow"> </a></li>
                </ul>
            </div>

            <div class="clear"></div>

            <?php echo $this->meta['promoText']; ?>

            <?php
                if (($this->meta['video2'] != '') || ($this->meta['video3'] != '') || ($this->meta['video4'] != '')) {
                ?>
                <div class="video-more">
                    <h2>View more of our videos...</h2>

                    <ul>
                        <li>
                            <h3><a href="<?php echo $this->meta['videoUrl2']; ?>"><span class="<?php echo $this->pageStyling; ?>"><?php echo $this->meta['videoTitle2']; ?></span></a></h3>
                            <a href="<?php echo $this->meta['videoUrl2']; ?>"><?php
                                echo $this->embeddedVideo(
                                    $this->meta['video2'],
                                    273,
                                    array(
                                        'output' => 'thumbnail'
                                    )
                                );
                            ?></a>
                            <p><?php echo $this->meta['promoText2']; ?></p>
                        </li>

                        <li>
                            <h3><a href="<?php echo $this->meta['videoUrl3']; ?>"><span class="<?php echo $this->pageStyling; ?>"><?php echo $this->meta['videoTitle3']; ?></span></a></h3>
                            <a href="<?php echo $this->meta['videoUrl3']; ?>"><?php
                                echo $this->embeddedVideo(
                                    $this->meta['video3'],
                                    273,
                                    array(
                                        'output' => 'thumbnail'
                                    )
                                );
                            ?></a>
                            <p><?php echo $this->meta['promoText3']; ?></p>
                        </li>

                        <li>
                            <h3><a href="<?php echo $this->meta['videoUrl4']; ?>"><span class="<?php echo $this->pageStyling; ?>"><?php echo $this->meta['videoTitle4']; ?></span></a></h3>
                            <a href="<?php echo $this->meta['videoUrl4']; ?>"><?php
                                echo $this->embeddedVideo(
                                    $this->meta['video4'],
                                    273,
                                    array(
                                        'output' => 'thumbnail'
                                    )
                                );
                            ?></a>
                            <p><?php echo $this->meta['promoText4']; ?></p>
                        </li>
                    </ul>
                </div>
                <?php
                }
            ?>

        </div>
        <div class="clear"></div>
	</div>
</div>