<link href="/assets/cms/css/video.css" media="screen" rel="stylesheet" type="text/css" />
<?php
echo $this->subHeader($this->pageStyling, $this->pageStyling);
?>
<div class="<?php echo $this->pageStyling; ?>">
    <div class="wrapper three-col">
		<div class="content">
            <?php echo $this->content ?>
		</div>
		<div class="sidebar">
            <div class="sidebar1">
                <h3 class="underline-<?php echo $this->pageStyling; ?>"><?php echo $this->meta['videoTitle1'] ?></h3>
                <div class="video"><?php echo $this->embeddedVideo($this->meta['video1'], 206); ?></div>
            </div>
            <div class="sidebar2" style="margin-top: 16px;">
                <?php echo $this->promoPanel($this->pageStyling, $this->meta['promoHeader1'], $this->meta['promoText1'], $this->meta['promoIcon1'].'_small'); ?>
            </div>
            <div class="clear"></div>
            <div class="sidebar1">
                <h3 class="underline-<?php echo $this->pageStyling; ?>"><?php echo $this->meta['videoTitle2'] ?></h3>
                <div class="video"><?php echo $this->embeddedVideo($this->meta['video2'], 206); ?></div>
            </div>
            <div class="sidebar2" style="margin-top: 16px;">
                <?php echo $this->promoPanel($this->pageStyling, $this->meta['promoHeader2'], $this->meta['promoText2'], $this->meta['promoIcon2'].'_small', $this->meta['promoUrl2']); ?>
            </div>
            <div class="clear"></div>
		</div>
        <div class="clear"></div>
	</div>
</div>
