<?php
echo $this->subHeader($this->meta['quoteTags'], 'corporate');
?>
<div class="corporate">
    <div class="wrapper three-col">
        <div class="content">
            <?php echo $this->content ?>
        </div>
        <div class="sidebar">
            <div class="sidebar1">
                <h4>@HomeLet on Twitter</h4>
                <ul class="twitter">
                    <?php echo $this->twitter(); ?>
                </ul>
            </div>
            <div class="sidebar2"> 
                <h4 class="underline-corporate">What people say</h4>
                <div class="blue">
					<div class="testyhearts">
						<div id="testimonials-holder">
							<ul>
								<?php
									echo $this->testimonials( $this->meta['testimonialTags'] );
								?>
							</ul>
							<div id="test-changer">
								<a href="#" rel="nofollow" class="prev" id="test-changer-left"></a>
								<a href="#" rel="nofollow" class="next" id="test-changer-right"></a>
							</div>
						</div>
					</div>
				</div>
            </div>
		</div>
    </div>
</div>