<?php
echo $this->subHeader('corporate', 'corporate');
?>
<div class="corporate">
    <div class="wrapper two-col">
		<div class="content">
            <script type="text/javascript">
                $(function() {
                   //wire up expander
                   $('.expanders li a.expander').click(function() {
                      $(this).toggleClass("open");
                      $(this).next().slideToggle();
                      return false;
                   })
                });
            </script>
            <h2 class="extra-padding">Terms and Conditions</h2>
            <ul class="expanders">
                <li>
                    <a rel="nofollow" href="#" class="expander">Privacy and cookie policy</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
									The Privacy Policy of HomeLet forms part of the Terms and Conditions of this website.
									We're committed to protecting your privacy. We’ll only use the information that we collect about you lawfully (in accordance with the Data Protection Act 1998).
								</p>
								<p>
									We collect information about you for several reasons; this could include the processing of a referencing application or an insurance quote. The information we collect also helps us provide you with the best possible service.
								</p>
								<p>
									Please note that we will not:
								</p>
								<ul>
									<li>Email you in the future unless you have given us your consent</li>
									<li>Pass your e-mail address to other trusted traders unless you have given us your consent</li>
								</ul>
								<p>
									Depending on the activity you carry out on our website, the type of information we may collect about you could include:
								</p>
								<ul>
									<li>Your name</li>
									<li>Address</li>
									<li>Phone number</li>
									<li>Email address</li>
									<li>Credit or debit card details</li>
								</ul>
								<p>
									We'll never collect sensitive information about you without your explicit consent. The information we hold will be accurate and up to date. You can check the information that we hold about you by emailing us. If you find any inaccuracies we'll delete or correct it promptly.
								</p>
								<p>
									The personal information which we hold will be held securely in accordance with our internal Security Policy and the law. If we intend to transfer your information outside the EEA (European Economic Area) we'll always obtain your consent first.
								</p>
								<p>
									<strong>Cookies on our website</strong>
								</p>
								<p>
									We use technology to help us understand the patterns of behaviour of visitors to our site. This includes the use of small data files call "cookies" which are stored on your browser. You can find out more about cookies and how we use them on our website by visiting our <a href="/cookies" title="View our full cookie policy">cookie policy</a> page.
								</p>
								<p>
									If you have any questions or comments about your privacy, please don’t hesitate to <a href="/contact-us" title="Contact us">contact us</a>.
								</p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Introduction and acceptance</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    Welcome to the HomeLet Web site. This is an important notice to all users. Your use of this site is subject to the following terms and conditions and by proceeding forward and using the web site you are agreeing to be legally bound by these terms and conditions. Please read them carefully. Unless you agree to these terms and conditions please do not proceed further though this site. Nothing in these terms and conditions affect your statutory rights. "HomeLet" is a trading name of Barbon Insurance Group Limited and in these terms includes any subsidiary, associated or parent company.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Disclaimer</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    HomeLet will not be liable to you for direct, indirect or consequential damage or any damage whatsoever, arising from breach of contract, misrepresentation, negligence or
                                    otherwise incurred by you as a result of your use of this site or in connection with the use of any information, materials, software or services provided on or through this site, or your inability to use this site, any error in the provision of the site or any computer virus transmitted through this site.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">"As is" clause</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    Save as is expressly provided, HomeLet does not give any warranties as to the accuracy, truth or completeness of the information available through this site. The information and services are offered "as is". Further, no warranty, guarantee or representation whether express or implied, is made as to the availability of this site, in it's current or amended form, at this or any other domain name or that it's use will be error, bug or virus free.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Viruses and compatibility</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    HomeLet does not give any warranty that this site or any information downloaded from it, is free from viruses or defects. You should ensure that you have the appropriate anti-virus software installed upon your system to detect and prevent infection from these sources. It is your responsibility to ensure that your computer system has the necessary specification to enable you to use this site.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Use of information</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    By accepting these terms and continuing to use this site you are giving authority to us, and our sub-contractors, to use the information supplied by you for the purpose of providing and supporting the services offered through this site. If you are a tenant and providing information for referencing purposes, then the information supplied by you may be passed to your prospective Landlord. We will use the information provided by you in accordance with the terms of the Data Protection Act 1998. For further information concerning your rights under this Act you can access the Data Protection Registrar website at www.dataprotection.gov.uk.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Copyright</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    The content of this site is, unless otherwise stated, the property of HomeLet and contains confidential information of HomeLet and is therefore protected by international copyright laws. All rights in respect of that copyright are reserved.
                                    You shall take all reasonable steps to protect HomeLet's copyright and confidential information in the web site. No part of the web site may be copied or reproduced by you save for the temporary copies made for the purpose of downloading the web site. You are not authorized to distribute, display, alter, modify or reproduce the web site or any part of it without the prior written consent of HomeLet.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Links</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    Sites to which you link to through this site (including without limitation, any site provided by a third party but branded as a HomeLet site) are independent of this site over which HomeLet does not exercise any control. HomeLet makes no representations as to the security or propriety of any website that may be accessed through this site. HomeLet does not accept any liability whether contractual or otherwise, in respect of your use or inability to use any linked site or in respect of the content of such sites. You may not, without the written consent of HomeLet, create a link from or to this site.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Continuity</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    HomeLet will endeavour to make available to you the web site but HomeLet cannot, and does not, guarantee the continuous operation of the web site free from interruptions or errors.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Modification of site</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    HomeLet may alter the content of the web site at any time without prior notification to you. HomeLet may also amend or vary the products and services detailed on the web site and/or the fees payable without prior notification to you.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Amendment of terms</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    HomeLet reserves the right to amend these terms and conditions. Notification of the changes to the terms and conditions will be posted on the web site. Thereafter your use of the site will be subject to the revised terms and conditions. If upon reading the revised terms and conditions you do not wish to be bound by them, then immediately discontinue your use of the web site.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Right to refuse</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    The web site and the services contained therein constitute an invitation to treat. Accordingly HomeLet reserves the right to decline applications and/or proposals submitted through the web site.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Severance of clauses</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    If any of the provisions of these terms and conditions are found to be unenforceable, invalid or illegal it shall be divisible from these terms and conditions and shall be deemed to be deleted from these terms and conditions. The remaining provisions shall continue to apply.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Jurisdiction</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    This site provides services only in respect of properties located within England, Scotland, Wales or Northern Ireland. These terms and conditions shall be governed by and construed in accordance with the laws of England whose courts shall be the courts of exclusive jurisdiction.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <a rel="nofollow" href="#" class="expander">Entire agreement</a>
                    <div class="details">
                        <div>
                            <div class="text">
                                <p>
                                    There may be other terms and conditions on pages of the web site which relate to your use of that part of the web site. These terms together with any others displayed on the web site constitute the entire agreement between the parties. No representations or warranties have been made other than those expressly provided for in this terms and conditions.
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="sidebar">
            <div id="right">
                <h4 class="underline-corporate">Resources</h4>
                <div class="white">
                    <?php $layout = $this->layout()->getView(); ?>
					<a href="<?php echo $layout->urls['contactUs']; ?>" class="nav-corporate-button">Ask us a Question</a>
					<a href="<?php echo $layout->urls['connectLogin']; ?>" class="nav-corporate-button">Login to Connect</a>
					<div style="clear:both;"></div>
                </div>
                <h4 class="underline-corporate">What people say</h4>
                <div class="blue">
                    <div class="testyhearts">
                        <div id="testimonials-holder">
                            <ul>
                                <?php
                                    echo $this->testimonials( 'corporate' );
                                ?>
                            </ul>
                            <div id="test-changer">
                                <a href="#" rel="nofollow" class="prev" id="test-changer-left"></a>
                                <a href="#" rel="nofollow" class="next" id="test-changer-right"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		<div class="clear"></div>
	</div>
</div>
