<?php
echo $this->subHeader('corporate', 'corporate');
?>
<div class="corporate">
    <div class="wrapper two-col">
		<script type="text/javascript">
			$(function() {
				$('.history ul li > a').click(function() {
					$(this).toggleClass("open");
					$(this).next().slideToggle();
					return false;
				});
				$('a.preopen').click();
			});
		</script> 
		<div class="content history">
			<h2>A track record we're really proud of</h2>
            HomeLet's been in the property industry since the birth of buy-to-let, so we've got more experience than anyone else, not to mention tried and tested referencing and insurance products designed specifically for letting agents. Here's our story...
            <ul class="history">
                <li>
                    <a class="preopen" href="#">2012</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5>Launch of Tenancy Liability</h5>
                                <p>We launched a new insurance cover called <a href="/tenants/liability-insurance">Tenancy Liability</a>, which allows tenants to cover their liability under their tenancy agreement, in case they accidentally damage their landlord&rsquo;s property, furniture, fittings and fixtures.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>Letting agents benefit from the new and improved referencing system</h5>
                                <p>We introduced a new and improved version of <a href="/letting-agents/connect">Connect</a>, our online referencing portal for letting agents.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>We bought a minibus for the Nomad Trust charity</h5>
                                <p>Through the hard work of our staff, we raised enough money to buy a minibus for our chosen charity the <a href="/about-us/charity">Nomad Trust</a>. The Nomad Trust supports homeless and vulnerable people in the Lincoln area, by helping them to stay off the streets and to change their lifestyles for the better.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2011</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>Our Optimum reference wins an award for innovation!</h5>
                                <p>We won the Innovation category for our <a href="/letting-agents/referencing/optimum">Optimum</a> reference at the Landlord and Lettings Awards! We were also shortlisted in the final for the Insurance Services and Website categories.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5>We show our support for the SAFE agent scheme</h5>
                                <p>HomeLet is one of the first UK companies to support the <a href="http://www.safeagents.co.uk/" target="_blank">SAFE agent</a> scheme – an initiative that supports the protection of landlords and tenants through client money protection schemes.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5>We updated our landlord&rsquo;s website</h5>
                                <p>We updated the <a href="/landlords">landlord</a> area of our website to make it even easier for landlords to get a quote online for our range of specialist landlords&rsquo; insurance products.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>The HomeLet Rental Index is launched</h5>
                                <p>In May we released the very first <a href="/rentalindex">HomeLet Rental Index</a>, which provides the industry with a unique insight into the private rented sector by supplying data on agreed rental prices and tenant demographics.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>The Tenant Application Tracker is launched</h5>
                                <p>We updated our <a href="/tenants">tenant</a> website and launched the new Tenant Application Tracker. This allowed tenants, who are being referenced, to view the status and progress of their reference online. This new area of our website had over 10,000 unique visits in the first month alone.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>We launched two great new products, Optimum and Evict</h5>
                                <p><a href="/letting-agents/referencing/optimum">Optimum</a> is the market&rsquo;s first tenant reference, which guarantees to remove a tenant, if they fail pay their rent in the first 12 months of their tenancy. Evict uses our in-house legal team to regain occupancy of a landlord&rsquo;s rented property and gain possession as quickly as possible, if they have a problem tenant who needs evicting.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2010</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>MyConnect is launched!</h5>
                                <p>
                                HomeLet launches MyConnect, the first suggestion portal for the lettings market.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5> HomeLet sponsors ARLA 2010</h5>
                                <p>HomeLet is once again the headline sponsor of the ARLA 2010 conference in Central London, and Internationally renowned magician Etienne woos the crowd with jaw-dropping illusions.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>HomeLet sponsors the ESTAs</h5>
                                <p>HomeLet proudly sponsors the ESTAs, hosted by Location Location Location's Phil Spencer.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5>Improvements to Tenants Contents Insurance+</h5>
                                <p>Further improvements are made to the Tenant's Contents Insurance+, now offering policy-holder the opportunity to start a policy 6 months in advance - perfect for students, teachers and doctors who often know when they are going to be moving way in advance of their studies or new jobs.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5>HomeLet launches new website!</h5>
                                <p>The company's brand new website is launched!</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2009</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>  Worst snow-fall for a decade</h5>
                                <p>The start of the year sees the worst snow-fall for a decade - with London's transport system almost ground to a halt. Sadly this combined with the ARLA 2009 conference, for which HomeLet is a headline sponsor. Fortunately the crowds are not put off, and the day is a huge success.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5>Tenants Contents Insurance+ sales growth</h5>
                                <p>HomeLet makes significant changes to its policy for tenants, and renames it Tenant's Contents Insurance+. The product now included sharers for the first time and as a result the company enjoys a doubling of sales - from 2000 in January that year, up to over 4,000 per month by the autumn.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5> HomeLet supports Shelter</h5>
                                <p>The company entertains 100 invited guests to a prestigious networking evening on the banks of the River Thames, at the same time raising money for homeless charity, Shelter.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5>Absolute Rent Guarantee is launched!</h5>
                                <p>Absolute Rent Guarantee is launched - a revolutionary solution which guarantees the rent for the whole property and can be renewed monthly.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>Launch of Landlords Insurance+ product</h5>
                                <p>The end of the year saw the launch of Landlord's Insurance+, the most comprehensive suite of solutions for landlords which offers &pound;0.5m rebuild cover as standard.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2008</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5> Barbon Insurance Group is formed</h5>
                                <p>Barbon Insurance Group is formed, with HomeLet the flagship brand in the group.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5> HomeLet appoints new CEO</h5>
                                <p>Martin Oliver joins Barbon from Kwik-Fit insurance.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5> Credit Crunch strikes</h5>
                                <p>Sparked by a financial crisis in the United States with mortgage lending, Britain enters what is known as a 'Credit Crunch'. Oil prices and unemployment rates rise; the value of houses declined and credit became increasingly tight.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>HomeLet sponsors the Negotiator Awards</h5>
                                <p>HomeLet is the proud sponsor of the Negotiator Awards, at a glitzy ceremony hosted by Rory Bremner.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2007</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5> HomeLet launches IPEX</h5>
                                <p>HomeLet launched IPEX - an online estate agency for landlords wanting to buy and sell their investment properties. IPEX was later sold to Jordan's, a north-west based Letting Agents.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2006</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>HomeLet launches Portfolio product</h5>
                                <p>In response to many landlords owning more than one property, HomeLet launched its first Portfolio Insurance product - perfect for landlords with between 2 and 10 properties.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2005</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5> HomeLet continues to grow!</h5>
                                <p>All of HomeLet's referencing and operations moved to Lincoln and an Account Management team was created to provide over the phone support for its growing base of letting agents.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5> HomeLet appoint new Sales Director!</h5>
                                <p>HomeLet brought in future Managing Director John Boyle as Sales Director from Pearl Insurance. Other recruits from Pearl included future Sales, Marketing and Operations director Heidi Abbott.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>Referencing business records growth</h5>
                                <p>HomeLet is now processing around 16,000 references a month at it's peak.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2004</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5>HomeLet teams up with Martin & Co</h5>
                                <p>HomeLet becomes a supplier to Martin & Co, one of the country's largest letting agents.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2003</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5> Erinaceous buys Credit-fax</h5>
                                <p>The Erinaceous Group bought Credit-fax and the HomeLet we know today was born.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2002</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5>Erinaceous Group buys Hanover Park</h5>
                                <p>The Erinaceous Group bought Hanover Park Services and Hanover Park Commercial - owners of HomeLet. Meanwhile, HomeLet continues to be Credit-fax's biggest customer.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2001</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5> Connect is born!</h5>
                                <p>The Erinaceous Group, a property specialist becomes a customer of Hanover Park Commercial, arranging its specialist block insurance. Meanwhile, at Credit-fax a new agent suite for ordering references was built and named Connect.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">2000</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5> HomeLet takes the market by storm!</h5>
                                <p>A Rent Guarantee solution is launched by HomeLet, and takes the market by storm!</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1999</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5> Call centre created!</h5>
                                <p>Credit-fax has really started developing well as a company, and the company creates a designated call centre. Meanwhile HomeLet which employed around eight people launched Premier offering a 24 hour turnaround for its referencing service.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1998</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>Call centre created!</h5>
                                <p>Credit-fax has really started developing well as a company, and the company creates a designated call centre. Meanwhile HomeLet which employed around eight people launched Premier offering a 24 hour turnaround for its referencing service.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1997</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5>Credit-fax moves to Becor House</h5>
                                <p>Credit-fax moves to Becor House, Lincoln - the same building where HomeLet is housed today. In this year, Credit-fax employed just 12 people - and during the year doubled the number of males employed - increasing from one to two!</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1996</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/winter.png" alt="Winter icon" />
                            <div class="text">
                                <h5>HomeLet sub-contracts it's Referencing</h5>
                                <p>HomeLet starts to sub-contract its referencing to Credit-fax.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1995</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5>HomeLet expands!</h5>
                                <p>HomeLet, at the time a small insurance provider to the lettings industry which is based in Crystal Palace joins forces with insurance provider Hanover Park, in a bid to help HomeLet expand. Meanwhile in Lincoln, Credit-fax became a limited company.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1994</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5>Recession recovery</h5>
                                <p>The UK starts to recover from the recession of the early 1990's, and thankfully unemployment starts to drop.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1993</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5>Helen Lloyd joins HomeLet</h5>
                                <p>Helen Lloyd - today's Head of Customer Care for HomeLet started working for Credit-fax as the only member of the referencing team!</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1992</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/autumn.png" alt="Autumn icon" />
                            <div class="text">
                                <h5>Credit-fax was born</h5>
                                <p>Capitalising on the Buy to let revolution, referencing operations first begin in Lincoln - under the name Credit-fax.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="" href="#">1991</a>
                    <div class="details">
                        <div>
                            <img src="/assets/cms/images/spring.png" alt="Spring icon" />
                            <div class="text">
                                <h5> Buy to Let was officially born</h5>
                                <p>Mortgages on investment properties were more readily available, and the private rented sector saw a boom.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                        <div>
                            <img src="/assets/cms/images/summer.png" alt="Summer icon" />
                            <div class="text">
                                <h5>Backdrop of global recession</h5>
                                <p>Global recession caused by the collapse of many savings and loan associations un the United States.</p>
                            </div>
                            <div style="clear:both;"></div>
                        </div>
                    </div>
                </li>
            </ul>
		</div>
		<div class="sidebar">
			 <div id="right">
				<h4 class="underline-corporate">Resources</h4>
				<div class="white">
					<?php $layout = $this->layout()->getView(); ?>
					<a href="<?php echo $layout->urls['contactUs']; ?>" class="nav-corporate-button">Ask us a <strong>Question</strong></a>
					<a href="<?php echo $layout->urls['connectLogin']; ?>" class="nav-corporate-dark-button">Login to <strong>Connect</strong></a>
					<div style="clear:both;"></div>
				</div>
				<h4 class="underline-corporate">What people say</h4>
				<div class="blue">
					<div class="testyhearts">
						<div id="testimonials-holder">
							<ul>
								<?php
									echo $this->testimonials('corporate');
								?>
							</ul>
							<div id="test-changer">
								<a href="#" rel="nofollow" class="prev" id="test-changer-left"></a>
								<a href="#" rel="nofollow" class="next" id="test-changer-right"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="clear"></div>
    </div>
</div>