<div class="form_section one-col">
    <div class="alt" style="height:70px">
        <?php echo $this->element->buildings_cover; ?>
        <div class="inline_checkbox" style="display:inline; width:100%">
            <div><?php echo $this->element->buildings_accidental_damage; ?></div>        
            <div><?php echo $this->element->buildings_nil_excess; ?></div>
        </div>
    </div>    
</div>
