
<div class="form_section one-col" id="contents-section">
        <div class="alt" style="height:100px">
        <?php echo $this->element->contents_cover; ?>
        <div class="inline_checkbox" style="display:inline; width:100%">
                <div><?php echo $this->element->contents_accidental_damage; ?></div>
                <div><?php echo $this->element->contents_nil_excess; ?></div>
                <div><?php echo $this->element->limited_contents; ?></div>
        </div>
    </div>    
</div>