<div class="form-sub-section">
    <div class="section-help">
        <p>
            <strong>Disclosure Statement</strong><br />
            Any other facts known to you which are likely to affect acceptance or assessment of the insurance cover you are
            requesting must be disclosed. Should you have any doubt about what you should disclose, do not hesitate to tell us.
            Making sure we are informed is for your own protection, as failure to disclose may mean that your policy will not
            give you the protection you require, or perhaps you may invalidate the policy altogether. For your reference, we
            recommend you keep a record of any additional information given, including copies of letters.
        </p>

        <p>
            <strong>Declaration Statement</strong><br />
            I/We declare that the foregoing statements and particulars are, to the best of my knowledge and belief, true and
            complete, and that I/We have read the note above, headed 'Disclosure'. I/We consent to information on this form
            and on any claim I/We make being supplied to IDS Ltd, the insurance industry's data collection agency, so that it
            can be made available to other insurers. I/We also agree that, in response to any searches you make in connection
            with this application or any claim, IDS Ltd may supply information it has received from other insurers about other
            claims I/We have made. I/We agree that the insurance will not be in force until this application has been accepted by
            HomeLet. I/We agree that the foregoing statements and particulars will form the basis of the contract between me/us
            and HomeLet. A copy of the completed proposal/application is automatically provided for retention at the time of
            completion.
        </p>

        <div class="checkbox">
            <label for="declaration_statement" class="required error">
                <?php echo $this->element->declaration_statement; ?>
                I accept
            </label>
        </div>
    </div>
</div>