<table>
    <tr>
        <td colspan="2"><?php echo "{$this->houseNumber} {$this->building} {$this->address1} {$this->address2} {$this->address3} {$this->address4} {$this->address5} {$this->postcode}";?>
        </td>
    </tr>
    <tr>
        <td>Bank Name</td>
        <td><?php echo "{$this->bankname}";?></td>
    </tr>
    <tr>
        <td>Address</td>
        <td><?php echo "{$this->bankaddress1}";?></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo "{$this->bankaddress2}";?></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo "{$this->bankaddress3}";?></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo "{$this->bankaddress4}";?></td>
    </tr>
        <tr>
        <td></td>
        <td><?php echo "{$this->bankbankpostcodename}";?></td>
    </tr>
    <tr>
        <td>Account Number</td>
        <td><?php echo "{$this->accountnumber}";?></td>
    </tr>
</table>
