	<tr>
		<td colspan="3">&nbsp;</td>
	</tr>				
	<tr>
		<td colspan="3"><h3>Underwriting Questions</h3></td>
	</tr>	
	<tr>
		<td>Question One</td>
		<td colspan="2"><?php echo $this->uwAnswers[0]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>Question Two</td>
		<td colspan="2"><?php echo $this->uwAnswers[1]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>Question Two B</td>
		<td colspan="2"><?php echo $this->uwAnswers[2]['answerGiven'];  ?></td>
	</tr>	
	<tr>
		<td>Question Two C</td>
		<td colspan="2"><?php echo $this->uwAnswers[3]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>Question Two D</td>
		<td colspan="2"><?php echo $this->uwAnswers[4]['answerGiven'];  ?></td>
	</tr>	
	<tr>
		<td>Question Three </td>
		<td colspan="2"><?php echo $this->uwAnswers[5]['answerGiven'];  ?></td>
	</tr>	
	<tr>
		<td>Question Four </td>
		<td colspan="2"><?php echo $this->uwAnswers[6]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>Question Five </td>
		<td colspan="2"><?php echo $this->uwAnswers[7]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>Question Six </td>
		<td colspan="2"><?php echo $this->uwAnswers[8]['answerGiven'];  ?></td>
	</tr>	
	<tr>
		<td>Question Seven </td>
		<td colspan="2"><?php echo $this->uwAnswers[9]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>
			<strong>Previous Claims</strong>
		</td>
		<td colspan="2">	
			<?php echo $this->claimsHtml;  ?>
		</td>
	</tr>	
	<tr>
		<td>Question Eight</td>
		<td colspan="2"><?php echo $this->uwAnswers[10]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>Question Nine</td>
		<td colspan="2"><?php echo $this->uwAnswers[11]['answerGiven'];  ?></td>
	</tr>
	<tr>
		<td>Bank Interest</td>
		<td colspan="2"><?php echo $this->bankInterestHtml;  ?></td>
	</tr>
