<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h3>Rent Guarantee Application Form Submitted</h3>
        <p>
            Your application has been submitted and will be processed shortly.
        </p>
        <p>
            If you have any further queries, please do not hesitate to email us at <a href="mailto:<?php echo $this->params->connect->absoluteapps->emailQueryAddress; ?>?subject=Absolute%20Application%20Rent%20Guarantee%20Query" title="<?php echo $this->params->connect->absoluteapps->emailQueryAddress; ?>"><?php echo $this->params->connect->absoluteapps->emailQueryAddress; ?></a>.
        </p>
    </div>
</div>