<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <h2 class="form">Absolute/Essential Rent Guarantee</h2>
        <p>We have now stopped selling our Absolute/Essential Rent Guarantee product and replaced it with Rent Recovery Plus (RRP).</p>
        <p>Rent Recovery Plus (including Rent Recovery Plus Nil Excess) has many of the benefits of Absolute, but with some fantastic improvements, including:</p>
        <ul>
            <li>Up to &pound;50,000 worth of legal expenses covered (as opposed to &pound;25,000 under the Absolute policy)</li>
            <li>Other &lsquo;acceptable&rsquo; references accepted, from our list of approved alternatives, as well as our own fantastic referencing services</li>
            <li>Just two rental amount structures to choose from, to make the process simpler</li>
            <li>Available for any level of property management</li>
        </ul>
        <p>RRP training is now available; contact your Account Manager to find out more about this new product and what it might mean for you.</p>
    </div>
</div>