<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
        
        $iconLayout = array(
            array(
                'icon'  => 'info',
                'title' => 'Extra Rent Guarantee',
                'url'   => '/assets/connect/pdf/Extra_Rent_Guarantee_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document contains more information about Extra Rent Guarantee.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Xpress Rent Guarantee',
                'url'   => '/assets/connect/pdf/Xpress_Rent_Guarantee_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document contains more information about Xpress Rent Guarantee.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
            array(
                'icon'  => 'info',
                'title' => 'Advantage Rent Guarantee',
                'url'   => '/assets/connect/pdf/Advantage_Rent_Guarantee_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document contains more information about Advantage Rent Guarantee.',
                    'version'       => '',
                    'release_date'  => ''
                )
            ),
/*
            array(
                'icon'  => 'info',
                'title' => 'Rent Recovery Plus',
                'url'   => '/assets/connect/pdf/Rent_Recovery_Plus_Info.pdf',
                'pdf_info'  => array(
                    'description'   => 'This document contains more information about Rent Recovery Plus.',
                    'version'       => '',
                    'release_date'  => ''
                )
            )
*/
	);

	if(! $this->canDisplayRRPI){
                foreach($iconLayout as $key => $value){
                    if ($value['title'] == 'Rent Recovery Plus') {
                        unset($iconLayout[$key]);
                        break;
                    }
                }
            }

            $this->iconLayout($iconLayout);
        ?>
    </div>
</div>
