<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        
        <h2>Problems?</h2>
        <p>
            Unfortunately this renewal could not be completed. Please contact one of our Rent Guarantee experts
            on <?php echo $this->helpLine ?> who will be able to help you.
        </p>

        <form method="get" action="/rentguarantee/renewals">
            <input type="submit" class="round-button" value="Finished"/>
        </form>
    </div>
</div>
