<div class="oc-corporate">
    <?php echo $this->breadCrumbTrail(); ?>
	<div class="two-col" style="border-top: 0px" align="center"><br/><br/>
        <div>
            <div  class="oc_textheader"><h4>Your claim has been saved</h4></div>
        </div>
		<br/>
		<div>
			Thank you! Your claim has been saved. Your claim will be available for you to complete and submit from the <br/>Claims Home Page.
			<br/><br/>
			Please note that the Claims team will not be able to start processing your claim until all information is <br/>provided and you've submitted the claim
		</div>
		<br/><br/>
		<div>
			<span>
				<input type="submit" name="exit" id="back" value=" Exit" onclick='window.location="home"' class="btn_orange">
			</span>
		</div>
    </div>
</div>