<div class="oc-corporate">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="wrapper two-col">
        <div class="content">
            <p>
                Thank you for choosing to log your HomeLet Rent Guarantee claim online. Doing this is easy - simply
                complete the fields below and provide as much information as possible so we're able to process your
                claim.
            </p>
            <p>
                Fields marked with an asterisk (*) are required.
            </p>
            <?php echo $this->form; ?>
        </div>
        <?php echo $this->sidebar; ?>
    </div>
</div>