<div class="col-xs-12">
    <?php echo $this->breadcrumbs ?>
</div>

<div class="clearfix"></div>

<div class="portal-wrapper">
    <div class="call-to-action">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <h2>Insurance claims</h2>
                <p>Find out more about making a claim on your insurance policy</p>
                <ul class="list-unstyled">
                    <li><a href="<?php echo $this->brochurewareBaseUrl; ?>tenants/help/make-a-claim/" class="arrow">Tenants Insurance claims</a></li>
                    <li><a href="<?php echo $this->brochurewareBaseUrl; ?>landlord/help/making-a-claim/" class="arrow">Landlord Insurance claims</a></li>
                </ul>
            </div>
        </div>

        <div class="col-sm-4">
            <?php echo $this->partial('partials/portal-pod-update-information.phtml') ?>
        </div>

        <div class="col-sm-4">
            <div class="panel panel-default">
                <h2>Hi <?php echo $this->firstName; ?></h2>
                <p>You can view your quotes, insurance policy documents and all of your correspondence from HomeLet right here in My HomeLet.</p>
                <p>If you do need any further help please don't hesitate to get in touch.</p>
                <a href="/logout" class="btn btn-primary">Log out</a>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="primary-content col-xs-12">
        <h1>Your HomeLet Account</h1>

        <div class="tabbed-details">
            <?php echo $this->navigation ?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <?php if ($this->accountUpdated): ?>
                        <div class="flashMessages">Your account details have been updated</div>
                    <?php endif ?>

                    <div class="row">
                        <div class="col-sm-8">
                            <?php echo $this->form ?>
                        </div>

                        <div class="col-sm-4">
                            <?php echo $this->partial('partials/portal-pod-help.phtml') ?>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
