<?php
    $this->headScript()
        ->appendFile('/assets/account/js/document-link-injector.js');
?>
<div class="col-xs-12">
    <?php echo $this->breadcrumbs ?>
</div>

<div class="clearfix"></div>

<div class="portal-wrapper content">
    <div class="call-to-action">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <h2>Insurance claims</h2>
                <p>Find out more about making a claim on your insurance policy</p>
                <ul class="list-unstyled">
                    <li><a href="<?php echo $this->brochurewareBaseUrl; ?>tenants/help/make-a-claim/" class="arrow">Tenants Insurance claims</a></li>
                    <li><a href="<?php echo $this->brochurewareBaseUrl; ?>landlord/help/making-a-claim/" class="arrow">Landlord Insurance claims</a></li>
                </ul>
            </div>
        </div>

        <div class="col-sm-4">
            <?php echo $this->partial('partials/portal-pod-update-information.phtml') ?>
        </div>

        <div class="col-sm-4">
            <div class="panel panel-default">
                <h2>Hi <?php echo $this->firstName; ?></h2>
                <p>You can view your quotes, insurance policy documents and all of your correspondence from HomeLet right here in My HomeLet.</p>
                <p>If you do need any further help please don't hesitate to get in touch.</p>
                <a href="/logout" class="btn btn-primary">Log out</a>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="primary-content col-xs-12">
        <h1>Your HomeLet Account</h1>

        <div class="tabbed-details">
            <?php echo $this->navigation ?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <?php if (($this->searchTerms != '') || ($this->searchTerms == '' && count($this->quotes) > 0)) : ?>
                        <form action="" method="get" class="search form-horizontal">
                            <fieldset class="padded-form">
                                <h2>Quotes</h2>
                                <div class="form-group">
                                    <label for="id">Quote Number</label>
                                    <div class="row">
                                        <div class="col-sm-9">
                                            <input type="text" name="id" id="id" placeholder="Enter Quote Number&hellip;" class="search-input form-control" value="<?php echo $this->searchTerms ?>" />
                                        </div>
                                        <div class="clearfix visible-xs"></div>
                                        <div class="col-sm-3">
                                            <input type="submit" class="btn btn-primary btn-small" value="Search" />
                                        </div>
                                    </div>
                                </div>
                                <?php foreach ($this->hiddenSearchFields as $_name => $_value) : ?>
                                    <input type="hidden" name="<?php echo $this->escape($_name) ?>" value="<?php echo $this->escape($_value) ?>" />
                                <?php endforeach; ?>
                            </fieldset>
                        </form>
                    <?php endif; ?>

                    <?php if ($this->searchTerms != '' && !count($this->quotes)): ?>
                        <h3>Sorry, but your search returned no results...</h3>
                        <p>We were unable to find what you&rsquo;re searching for with the information that you&rsquo;ve provided.</p>
                        <p>Please try again, if you&rsquo;re unable to find what you&rsquo;re looking for please don&rsquo;t hesitate to contact us, we&rsquo;re always happy to help.</p>
                        <p>Kind regards,<br/>
                            The HomeLet team</p>
                    <?php elseif ($this->searchTerms == '' && !count($this->quotes)): ?>
                        <h3>You currently have no saved quotes available to view</h3>
                        <p>
                            You can get a quote for <a href="/tenants" title="Get a tenant's quote">tenants</a> insurance
                            or <a href="/landlords/insurance-quote" title="Get a landlord's quote">landlords</a> insurance and any quotes that
                            you&rsquo;ve generated for HomeLet insurance products will appear here.
                        </p>

                        <p>
                            We've been one of the UK's leading providers of tenant references and insurance solutions to
                            the lettings industry for over two decades, which means we understand the potential risks that
                            landlords and tenants face. We've used our experience to design a range of specialist insurance
                            policies for <a href="/landlords/insurance-quote" title="Get a landlord's quote">landlords</a>
                            and <a href="/tenants" title="Get a tenant's quote">tenants</a>.
                        </p>
                    <?php else: ?>
                        <table class="table table-condensed table-bordered hidden-xs policy-table">
                            <thead>
                            <tr>
                                <th><?php echo $this->sortableColumn('Quote Number', 'policynumber') ?></th>
                                <th><?php echo $this->sortableColumn('Product', 'policyname') ?></th>
                                <th>Cover</th>
                                <th><?php echo $this->sortableColumn('Start date', 'startdate') ?></th>
                                <th><?php echo $this->sortableColumn('Expires', 'validuntildate') ?></th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $counter = 1; ?>
                            <?php foreach ($this->quotes as $quote): ?>
                                <?php $liabilitypolicy = false; ?>

                                <tr class="view" id="<?php echo $counter++; ?>">
                                    <td>
                                        <strong><?php echo $this->escape($quote->policyNumber) ?></strong><br />
                                        <em>(<?php echo $this->escape($quote->propertyAddress1); ?>, <?php echo $this->escape($quote->propertyPostcode); ?>)</em>
                                    </td>
                                    <td><?php echo $this->escape($quote->getPrintableProductName()) ?></td>
                                    <td>
                                        <ul>
                                            <?php if (count($quote->policyCovers) > 0): ?>
                                                <?php foreach ($quote->policyCovers as $cover): ?>
                                                    <li><?php echo $this->escape($cover['name']) ?></li>

                                                    <?php
                                                    if ($cover['cover'] == 'liabilitytp') {
                                                        $liabilitypolicy = true;
                                                    }
                                                    ?>
                                                <?php endforeach; ?>
                                            <?php else: ?>
                                                <em>None Selected</em>
                                            <?php endif; ?>
                                        </ul>
                                    </td>
                                    <td>
                                        <?php if ($quote->startDate == '0000-00-00'): ?>
                                            <em>Not Specified</em>
                                        <?php else: ?>
                                            <?php echo $this->escape($quote->getStartsAt()) ?>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <?php echo $this->escape($quote->getExpiresAt()) ?>
                                    </td>
                                    <td>
                                        <?php if ($quote->payStatus == 'Referred' || $quote->payStatus == 'ReleasedFromUnderwriting'): ?>
                                            Your quote has been referred to our Insurance team. We&rsquo;ll contact you shortly about your quote for some further information.<br/><br/>
                                            If you need to contact us you can call us on 0845 117 6000
                                        <?php elseif($liabilitypolicy === true): ?>
                                            Please call us on 0845 117 6000 to buy a Tenancy Liability quote.
                                        <?php elseif(in_array($quote->policyName, array('landlords', 'lowcostlandlords', 'tenants'))): ?>
                                            Please call us on 0845 117 6000 to buy a <?php echo $this->escape($quote->getPrintableProductName()) ?> quote.
                                        <?php else: ?>
                                            <?php if ($quote->origin == 0 || $quote->policyName !== 'landlordsp'): ?>
                                                <a href="/<?php echo $this->escape($quote->getProductName()) ?>/insurance-quote/retrieve?quote=<?php echo $this->escape($quote->policyNumber) ?>" title="" class="btn btn-<?php echo $this->policyTypeToColour($quote->policyType); ?>">Complete Your Quote</a><br/>
                                            <?php else: ?>
                                                <a href="/<?php echo $this->escape($quote->getProductName()) ?>/insurance-quote/retrieve?quote=<?php echo $this->escape($quote->policyNumber) ?>" title="" class="btn btn-<?php echo $this->policyTypeToColour($quote->policyType); ?>">Complete Your Quote</a><br/>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="visible-xs">
                            <dl>
                                <?php foreach ($this->quotes as $quote): ?>
                                    <dt><?php echo $this->sortableColumn('Quote Number', 'policynumber') ?></dt>
                                    <dd>
                                        <strong><?php echo $this->escape($quote->policyNumber) ?></strong><br />
                                        <em>(<?php echo $this->escape($quote->propertyAddress1); ?>, <?php echo $this->escape($quote->propertyPostcode); ?>)</em></strong>
                                    </dd>
                                    <dt><?php echo $this->sortableColumn('Product', 'policyname') ?></dt>
                                    <dd><?php echo $this->escape($quote->getPrintableProductName()) ?></dd>
                                    <dt><strong>Cover</strong></dt>
                                    <dd>
                                        <ul>
                                            <?php if (count($quote->policyCovers) > 0): ?>
                                                <?php foreach ($quote->policyCovers as $cover): ?>
                                                    <li><?php echo $this->escape($cover['name']) ?></li>

                                                    <?php
                                                    if ($cover['cover'] == 'liabilitytp') {
                                                        $liabilitypolicy = true;
                                                    }
                                                    ?>
                                                <?php endforeach; ?>
                                            <?php else: ?>
                                                <em>None Selected</em>
                                            <?php endif; ?>
                                        </ul>
                                    </dd>
                                    <dt><?php echo $this->sortableColumn('Start date', 'startdate') ?></dt>
                                    <dd>
                                        <?php if ($quote->startDate == '0000-00-00'): ?>
                                            <em>Not Specified</em>
                                        <?php else: ?>
                                            <?php echo $this->escape($quote->getStartsAt()) ?>
                                        <?php endif; ?>
                                    </dd>
                                    <dt><?php echo $this->sortableColumn('Expires', 'validuntildate') ?></dt>
                                    <dd>
                                        <?php echo $this->escape($quote->getExpiresAt()) ?>
                                    </dd>
                                    <dt>Action</dt>
                                    <dd>
                                        <?php if ($quote->payStatus == 'Referred' || $quote->payStatus == 'ReleasedFromUnderwriting'): ?>
                                            Your quote has been referred to our Insurance team. We&rsquo;ll contact you shortly about your quote for some further information.<br/><br/>
                                            If you need to contact us you can call us on 0845 117 6000
                                        <?php elseif($liabilitypolicy === true): ?>
                                            Please call us on 0845 117 6000 to buy a Tenancy Liability quote.
                                        <?php elseif(in_array($quote->policyName, array('landlords', 'lowcostlandlords', 'tenants'))): ?>
                                            Please call us on 0845 117 6000 to buy a <?php echo $this->escape($quote->getPrintableProductName()) ?> quote.
                                        <?php else: ?>
                                            <?php if ($quote->origin == 0 || $quote->policyName !== 'landlordsp'): ?>
                                                <a href="/<?php echo $this->escape($quote->getProductName()) ?>/insurance-quote/retrieve?quote=<?php echo $this->escape($quote->policyNumber) ?>" title="" class="btn btn-<?php echo $this->policyTypeToColour($quote->policyType); ?>">Complete Your Quote</a><br/>
                                            <?php else: ?>
                                                <a href="/<?php echo $this->escape($quote->getProductName()) ?>/insurance-quote/retrieve?quote=<?php echo $this->escape($quote->policyNumber) ?>" title="" class="btn btn-<?php echo $this->policyTypeToColour($quote->policyType); ?>">Complete Your Quote</a><br/>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <hr />
                                    </dd>
                                <?php endforeach; ?>
                            </dl>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <script type="text/javascript">

        $('.buy').click(
            function() {
            $.facebox('Please call us to complete your quote','Sorry, but we’re unable to complete this particular quote online, please call our Landlords Insurance team on 0845 117 6000 to arrange your cover. <br><br> Our lines are open: <br><br> Monday to Friday:  8:30am - 6:30pm <br> Saturday: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9:30am - 1:00pm <br><br> Alternately, you can start a new quote online ');
                return false;
        });

        </script>
    </div>

    <div class="clearfix"></div>

    <div class="col-xs-12">
        <?php echo $this->partial('partials/portal-pod-help.phtml') ?>
    </div>
    
</div>
