
<h2>My HomeLet Account Registration</h2>
<?php echo $this->helpPopup('Registering for My HomeLet', 'myhomelet-account-registration'); ?>
<div class="clear"></div>

<div class="form_section one-col">

    <div class="alt">
        <?php echo $this->element->email; ?>
    </div>

    <div>
        <?php echo $this->element->password; ?>
    </div>

    <div class="alt">
        <?php echo $this->element->confirm_password; ?>
    </div>

    <div>
        <?php echo $this->element->security_question; ?>
    </div>

    <div class="alt">
        <?php echo $this->element->security_answer; ?>
    </div>

</div>
