imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
    payment_handoff_url_route_name: barbon_paymentportal_payment_paymenttypeselection
    refund_handoff_url_route_name: barbon_paymentportal_payment_requestrefund
    repeat_handoff_url_route_name: barbon_paymentportal_payment_requestrepeat

framework:
    #esi:             { enabled: true }
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - BarbonPaymentPortalBundle:Form:form_div_layout.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ BarbonPaymentPortalBundle ]
    filters:
        lessphp:
             file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
             apply_to: "\.less$"
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# DI Extra Configuration
jms_di_extra:
    locations:
        all_bundles: true
        #directories: ["%kernel.root_dir%/../src"]

# FOS REST Configuration
fos_rest:
    view:
        view_response_listener: true

# Payment Core Configuration
jms_payment_core:
    secret: %jms_payment_core_secret%

# Barbon PayPoint Payment Configuration
barbondev_payment_pay_point_hosted:
    merchant: %paypoint_merchant%
    remote_password: %paypoint_remote_password%
    gateway_url: %paypoint_gateway_url%
    test_status: %paypoint_test_status%
    repeat: %paypoint_repeat%
    test_mpi_status: %paypoint_test_mpi_status%
    usage_type: %paypoint_usage_type%
    dups: %paypoint_dups%
    template: %paypoint_template%
    vpn_password: %paypoint_vpn_password%
    wsdl_url: %paypoint_wsdl_url%

# TWBS Configuration
braincrafted_bootstrap:
    less_filter: lessphp