<?php
// Test template file for the core emailer
?>
<h1>Just a test</h1><br />
<p>Hi <?php echo $this->metaData['name']; ?>, Today's date is <?php echo $this->metaData['date']; ?></p>
<table width="300px" cellspacing="2" border="1">
    <tr>
        <th>
            Something
        </th>
        <th>
            Something else
        </th>
    </tr>
    <tr>
        <td>
            asdsadasad
        </td>
        <td>
            uihy huhnlbk
        </td>
    </tr>
</table>