<table width="100%">
  <tr>
    <td>
      <div align="center">
        <table width="673">
          <tr>
            <td>
              <img src="http://www.homelet.co.uk/assets/email/images/email_footer_image.jpg" />
            </td>
          </tr>

          <tr>
            <td>
              <div align="left">
                <font size="1" face="arial" color="#00346D">
                  <p>This email and the information it contains may be confidential, legally privileged and protected by law. Access by the intended recipient only is authorised. Any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting, on any information contained in this email is hereby excluded.  </p>

                  <p>If this email has been sent to you for the purpose of confirming reference details it must be treated accordingly and for the limited purposes of confirming the relevant reference details.</p>

                  <p>If you are not the named addressee you should not disseminate, distribute or copy this email. Please notify us immediately, by emailing hello@homelet.com if you have received this email by mistake and delete it from your system.</p>

                  <p>If you are required to respond to this email with confidential information, whether about yourself or any other individual, please make sure you do this via a secure method.</p>

                  <p>Views and opinions expressed in this email or attachments are those of the author and are not necessarily agreed or authorised. We may monitor emails sent or received for operational or business reasons as permitted by law. </p>
                </font>
              </div>
            </td>
          </tr>
        </table>
      </div>
    </td>
  </tr>
</table>

