<?php
if ($this->stepNum == 'dd') {
    ?>
    <input type="submit" value="Confirm" id="next" name="next" class="btn btn-quaternary">
    <input type="submit" value="Back" id="back" name="back" class="btn btn-inverse">
<?php
} elseif ($this->stepNum == 'add'){
    // if we have an id we are editing
    if (isset($_GET['id'])){
        ?>
        <input type="submit" value="Update" id="next" name="next" class="btn btn-quaternary">
        <input type="submit" value="Back" id="back" name="back" class="btn btn-inverse">
    <?php
    }else {
        ?>
        <input type="submit" value="Add" id="next" name="next" class="btn btn-quaternary">
        <input type="submit" value="Cancel" id="back" name="cancel" class="btn btn-inverse">
    <?php
    }
} else {
    if ($this->stepNum < $this->stepMax) {
        ?>
        <input type="submit" value="Next" id="next" name="next" class="btn btn-quaternary">
    <?php
    } else {
        ?>
        <input type="submit" value="Buy Now" id="next" name="next" class="btn btn-quaternary">
    <?php
    }
    if ($this->stepNum > 1) {
        ?>
        <input type="submit" value="Back" id="back" name="back" class="btn btn-inverse">
    <?php
    }
}
?>
<div class="clearfix"></div>