<div id="portfolio-intro" class="section-help section-help-fullwidth">
    <p>Portfolio has been created specifically for landlords with between two and 20 properties. It gives you one policy with one renewal date irrespective on your portfolio size. You can very easily add or remove properties as your portfolio develops. Cover is available for buildings and contents and you can save up to 45% compared to individual policies.</p>

    <a class="btn btn-quaternary" href="/portfolio/insurance-quote/insured-address"><strong>Add</strong> First Property</a>
</div>
<div class="clearfix"></div>
