<br />
<br />
<p>
	<font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">
    If you've got any questions, give us a call on <font size="4" color="#ff6600">0845 117 6000</font>,
    after all we're here to help!
    </font>
</p>
<p>
	<font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">
    Kind regards
    </font>
</p>
<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">The HomeLet Team</font>
</p>