<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>HomeLet Connect - <?php echo $this->pageTitle; ?></title>
</head>
<body class="letting-agents">
    <div id="content">
        <div class="banner"><?php echo $this->pageTitle; ?></div>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>