<h2>Disclosure</h2>

<div class="form_section one-col">
    <p>
        Any other facts known to you which are likely to affect acceptance or assessment of the insurance cover you are requesting must be disclosed.
        Should you have any doubt about what you should disclose, do not hesitate to tell us.
        Making sure we are informed is for your own protection, as failure to disclose may mean that your policy will not give you the protection you require,
        or perhaps may invalidate the policy altogether.
        For your reference, we recommend that you keep a record of any additional information given, including copies of letters.
    </p>
</div>

<h2>Declaration</h2>

<div class="form_section one-col">
    <p>
        Please read the declaration below and confirm by ticking the box that the information you've provided is true. <strong>It's important you do this as we're unable to continue with your application if you do not.</strong>
        I/We declare that the foregoing statements and particulars are, to the best of my knowledge and belief, true and complete, and that I/We have read and note the above, headed 'Disclosure'.
        I/We consent to the information on this form and on any claim I/We make being supplied to IDS Ltd, the insurance industry's data collection agency, so that it can be made available to other insurers.
        I/We also agree that, in response to any searches you make in connection with this application or any claim, IDS Ltd may supply information it has received from other insurers about other claims I/We have made.
        I/We agree that the insurance will not be in force until this application has been accepted by HomeLet.
        I/We agree that the foregoing statements and particulars will form the basis of the contract between me/us and HomeLet.
        A copy of the completed proposal/application is automatically provided for retention at the time of completion.
    </p>
    <p>
        This policy will be set up on the basis that:
        <ul style="list-style-type: none;">
            <li>
                The property is let or to be let on a written Assured Shorthold Tenancy * with a minimum initial period of at least three months<br />
                * <em>(In England &amp; Wales or the equivalent in Scotland, Northern Ireland or the Isle of Man)</em>
            </li>
            <li>You are not aware of any circumstances which may give rise to a claim, or have been refused insurance or had special terms applied</li>
            <li>The property is in a good state of repair and regularly maintained</li>
            <li>All tenants have been referenced in accordance with HomeLet conditions before the policy start date</li>
            <li>All future tenants will be referenced in accordance with the conditions of this policy</li>
        </ul>
    </p>
    <div class="autoAlt">
        <?php echo $this->element->confirmation; ?>
    </div>
    <div>
        <?php echo $this->element->complete; ?>
    </div>
</div>