<h2>Product Selection</h2>

<div class="form_section one-col">
    <div class="autoAlt">
        <?php echo $this->element->product; ?>
    </div>
    <div class="autoAlt">
        <?php echo $this->element->term; ?>
    </div>
    <div class="autoAlt">
        <?php echo $this->element->type; ?><br />
        <br />
        <span class="orange">
            To purchase Absolute or Absolute Zero you must have a satisfactory reference.<br /><br />
            What is a satisfactory reference? <br /><br />
            <u>Where a nil excess applies</u> <br />
            A HomeLet Enhance (Comprehensive) reference report showing 'acceptable' or 'acceptable with condition'. We are unable to accept a HomeLet Insight (Credit Profile Plus) as a satisfactory reference for our nil excess product.<br /><br />
            <u>Where an excess applies</u> <br />
            A HomeLet Enhance (Comprehensive) reference report showing 'acceptable' or 'acceptable with condition' or a HomeLet Insight (Credit Profile Plus) reference report showing a Tenancy Assessment Score (TAS) of 710 or above where the tenant is in full time employment.
        </span>
    </div>
</div>
