<h2>Product Selection</h2>

<div class="form_section one-col">
    <div class="autoAlt" id="term">
        <?php echo $this->element->term; ?>
    </div>
    <div class="autoAlt">
        <?php echo $this->element->type; ?><br />        
    </div>
    <div class="autoAlt" id="provider_name">      
        <?php echo $this->element->provider; ?>        
    </div>
    <div class="autoAlt">
        <?php echo $this->element->excess; ?><br />
    </div>
    <div class="autoAlt">
        <?php echo $this->element->continuation; ?><br />
    </div>
    <div class="autoAlt">
        <?php echo "This product meets the demands and needs of those who wish to purchase rental protection in the event of a breach of tenancy agreement." ?><br />
    </div>  
</div>
