
<form action="<?php echo $this->formAction; ?>" method="post">
    <h2>Select Document Address</h2>
    
    <div class="form_section one-col">
        <div>
            <?php echo $this->element->cor_house_number_name; ?>
        </div>
        <div class="alt">
            <?php echo $this->element->cor_postcode; ?>
            <input type="submit" id="cor_postcode_lookup" value="Find address" name="lookup" onclick="getProperties($('#cor_house_number_name').val(), $('#cor_postcode').val(), 'cor_postcode', 'cor_address'); return false;" />
        </div>
        <div id="cor_address_selector">
            <?php echo $this->element->cor_address->setAttribs(array('style' => 'width: 320px;'))->render(); ?>
        </div>
        
        <div>
            <?php echo $this->element->formsubmit_back; ?>
            <?php echo $this->element->formsubmit_continue; ?>
        </div>
    </div>
</form>
