<div class="breadcrumb"></div>
<div class="row content">
    <div class="col-sm-8">
        <h2>404 - Page Not Found</h2>
        <p>
            <strong>We're sorry, we couldn't find the page you're looking for.<br />
            <br />
            This may be because:</strong>
        </p>

        <ul>
            <li>The link isn't working properly or the page has been moved</li>
            <li>You've typed the page address (URL) incorrectly</li>
        </ul>

        <p>
            <strong>You could try:</strong>
        </p>

        <ul>
            <li>Clicking the 'Back' button on your browser and choosing a different link</li>
            <li>Checking and re-typing the page address (URL). URLs should all be typed in lower case only</li>
            <li>Making sure that your bookmarks are up to date</li>
        </ul>

        <p>Click <a href="/home">here</a> to go back to the homepage</p>
	</div>

    <div class="col-sm-4">
        <div class="panel panel-secondary">
            <h3>Need help?</h3>
            <p class="large primary-colour">Call: 0845 117 6000</p>
            <p>We&rsquo;re open from:</p>
            <table class="table table-condensed">
                <tr>
                    <td>Weekdays</td>
                    <td>8:30am - 6:30pm</td>
                </tr>
                <tr>
                    <td>Saturday</td>
                    <td>9:30am - 1:00pm</td>
                </tr>
            </table>
            <p>We&rsquo;re always happy to help.</p>
        </div>
    </div>
</div>