<div class="container">
    <div class="breadcrumb">
        <a href="/tenants">Tenants</a> &raquo; <a href="/tenants/reference-tracker">Reference Tracker</a> &raquo; <a href="/tenants/reference-tracker/callme">Request a Callback</a> &raquo; Thank You
    </div>
</div>
<div class="tenants col-xs-12">
    <div class="content">
        <h2>HomeLet Tenant Referencing Application Tracker</h2>
        <p>
            <strong>Thank you, your email has been sent to our Campaign team.</strong>
        </p>
    </div>
    <input type="submit" name="back" id="back" value="Back" onclick="window.location='/tenants/reference-tracker';" class="btn btn-primary" />
</div>