<div class="container">
    <div class="breadcrumb">
        <a href="/tenants">Tenants</a> &raquo; <a href="/tenants/reference-tracker">Reference Tracker</a> &raquo; <a href="/tenants/reference-tracker/email">Email HomeLet</a> &raquo; Thank You
    </div>
</div>
<div class="tenants col-xs-12">
    <div class="content">
        <h2>HomeLet Tenant Referencing Application Tracker</h2>

        <p>
            Thank you for emailing us,
        </p>

        <p>
            If you&rsquo;ve sent us any additional information it will be added to your application. Please allow us some time to log and process your information, you&rsquo;ll be able to check the progress of your application on your application tracker page.
        </p>

        <p>
            We&rsquo;ll aim to respond to any other queries regarding your application within one working day.
        </p>

        <p>
            If you&rsquo;re looking to cover your contents, or your liability as a tenant under your tenancy agreement, then HomeLet may be able to help...
        </p>

        <p>
            With HomeLet Tenant&rsquo;s Insurance you can choose to cover your liability as a tenant with our Tenancy Liability Cover, or you can add contents
            cover to your policy too, with Tenant&rsquo;s Contents Insurance+.
        </p>

        <p>
            If you’d like to get an online Tenant’s Contents Insurance+ quote now please visit our quote page.
        </p>
        <a href="/tenants/" class="btn btn-primary">Get a quote</a>

        <p class="clear">
            For more information about Tenancy Liability please visit our product page.
        </p>
        <a href="/tenants/liability-insurance" class="btn btn-primary">More information</a>

        <p>
            Kind regards,
        </p>

        <p>
            The HomeLet team
        </p>
    </div>
    <input type="submit" name="back" id="back" value="Back" onclick="window.location='/tenants/reference-tracker';" class="btn btn-primary" />
</div>
