<div class="form-group">
    <?php echo $this->element->getElement('bank_name'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('account_number'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('address_line1'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('address_line2'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('town'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('postcode'); ?>
</div>