<div class="form-group">
    <?php echo $this->element->getElement('claim_type'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('claim_month'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('claim_year'); ?>
</div>

<div class="form-group">
    <?php echo $this->element->getElement('claim_value'); ?>
</div>

<input class="btn btn-quaternary" type="button" id="cor_address_add" value="Add" name="cor_address_add" onclick="addClaims(); return false;" />