<div class="form-sub-section">
    <h2 class="quaternary-colour">
        <span class="help-trigger"><a class="show-form-help"></a></span>
        <span class="field-help hidden-xs hidden-sm">
            <?php echo strip_tags($this->promoContent('landlords-insurance-quote-help-prestigerentguarantee')); ?>
        </span>
        Prestige Rent Guarantee
    </h2>

    <div class="mobile-help section-help section-help-fullwidth">
        <div class="visible-xs visible-sm">
            <?php echo $this->promoContent('landlords-insurance-quote-help-prestigerentguarantee'); ?>
        </div>
    </div>

    <div class="radio form-group">
        <?php echo $this->element->need_prestige_rent_guarantee; ?>
    </div>

    <div id="prestige_rent_guarantee_hideable" class="hideable">
        <div class="form-group">
            <?php echo $this->element->rent_amount; ?>
        </div>
    </div>
</div>