<!-- landlords' version -->
<div class="form_section">
    <div id="subform-register" class="form-sub-section">
        <div class="form-help hidden-xs hidden-sm"></div>
        <h2 class="quaternary-colour">Register for My HomeLet</h2>

        <div class="form-group">
            <div class="help-trigger"><a class="show-help"></a></div>
            <div class="field-help quaternary-colour">
                For security, passwords must have at least 8 characters and contain at least one uppercase letter and one number.
            </div>
            <?php
            echo $this->element->password
                ->setOptions(array('class' => 'form-control'))->render();
            ?>
        </div>

        <div class="form-group">
            <div class="help-trigger"><a class="show-help"></a></div>
            <div class="field-help quaternary-colour">
                Please re-enter your password to confirm it.
            </div>
            <?php
            echo $this->element->confirm_password
                ->setOptions(array('class' => 'form-control'))->render();
            ?>
        </div>
    </div>
</div>

<button type="submit" name="register" class="btn btn-quaternary pull-right">
    Next <img src="/assets/common/images/loading.gif" class="loading-indicator" alt="Loading..."/>
</button>
<div class="clearfix"></div>