<div id="sub_header_clean">
    <div class="wrapper">
        <div id="steps">
            <a<?php if (isset($this->stepNum) && $this->stepNum == 1) { echo " class=\"current\""; } ?> id="letting-agents-step1" href="/letting-agents/sign-up/step1"><span>&gt; Step 1</span>You &amp; your company</a>
            <a<?php if (isset($this->stepNum) && $this->stepNum == 2) { echo " class=\"current\""; } ?> id="letting-agents-step2" href="/letting-agents/sign-up/step2"><span>&gt; Step 2</span>Insert new Title</a>
            <a<?php if (isset($this->stepNum) && $this->stepNum == 3) { echo " class=\"current\""; } ?> id="letting-agents-step3" href="/letting-agents/sign-up/step3"><span>&gt; Step 3</span>Your company in more detail</a>
            <a<?php if (isset($this->stepNum) && $this->stepNum == 4) { echo " class=\"current\""; } ?> id="letting-agents-step4" href="/letting-agents/sign-up/step4"><span>&gt; Step 4</span>Your options and insurance</a>
            <a<?php if (isset($this->stepNum) && $this->stepNum == 5) { echo " class=\"current\""; } ?> id="letting-agents-step5" href="/letting-agents/sign-up/step5"><span>&gt; Step 5</span>Your bank details</a>
            <h2>Letting Agent - New Agent Application</h2>
        </div>
        <div class="clear"></div>
    </div>
</div>