
<form action="<?php echo $this->formAction; ?>" method="post" enctype="application/x-www-form-urlencoded">
    <h2>Referencing Daily Summary</h2>
    
    <div class="form_section one-col">
        <p style="height:30px;">
            Track the Service Level we've achieved on all your referencing applications
        </p>
        <div>
            <?php echo $this->element->overnight_producereport; ?>
        </div>
    </div>
</form>