<table width="600" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        Dear <?php echo $this->metaData['name']; ?>,
    </p>
    
    <p style="color: #EF2B93; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif; font-weight: bold;">
        Just to let you know we&rsquo;ve saved your quote for you
    </p>
    
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        Thanks for visiting our website and requesting a quote for Tenant&rsquo;s Contents Insurance+.
    </p>
    
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        As requested we&rsquo;ve saved your quote for you, so when you want to view your quote again simply pop back and visit us at
        <a href="http://homelet.co.uk/tenants">homelet.co.uk/tenants</a>.
        You&rsquo;ll then just need to log in using the username and password that you set up when you saved your quote.
    </p>
    
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        Once you&rsquo;ve logged in you can make changes to your details, including the levels of cover that you need. You can also
        choose to buy your policy by clicking <span style="color: #FF00FF; font-size: 14px; font-weight: bold;">BUY NOW</span>.
    </p>
    
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        As a reminder here are some of the key benefits of a Tenant&rsquo;s Contents Insurance+ policy:
    </p>
    
    <ul>        
        <li>
            <span style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
                Additional cover for those extra special items anywhere in the world!
            </span>
        </li>
        <li>
            <span style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
                Automatic cover for you, your partner and all members of your family permanently living in your home
            </span>
        </li>
        <li>
            <span style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
                Add up to two sharers that are also on your tenancy agreement to your policy
            </span>
        </li>
    </ul>
    
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        For more information, or of you have any queries or questions then please don&rsquo;t hesitate to contact us on 0845 117 6000 from
        8.30am-8pm Monday to Friday and 9.30am-1pm Saturday - we&rsquo;re always happy to help!
    </p>
    
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        Kind Regards
    </p>
    
    <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
        The HomeLet Team
    </p>
</table>

<!-- footer -->
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <!-- gap after main content block -->
    <tr><td style="height: 40px; font-size: 40px;">&nbsp;</td></tr>
    
    <!-- social and awards -->
    <tr>
        <td valign="top">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td>
                        <p style="color: #00007C; font-size: 14px; font-family: Verdana, Arial, Helvetica, sans-serif;">
                            Stay connected and get the latest news by following us on
                            <a href="http://www.twitter.com/lovetenants" style="color:#FF00FF; text-decoration: underline;" target="_blank"><span color="#FF00FF">Twitter</span></a>,
                            
                            visiting our 
                            <a href="http://www.facebook.com/love.tenants" style="color:#FF00FF; text-decoration: underline;" target="_blank"><span color="#FF00FF">Facebook</span></a>
                            
                            page or our
                            <a href="http://www.lovetenants.wordpress.com/" style="color:#FF00FF; text-decoration: underline;" target="_blank"><span color="#FF00FF">blog</span></a>.<br/>
                        </p>
                    </td>
                </tr>
            </table>
        </td>
        
        <td>
            
            <span style="color: #FF00FF; font-size: 14px; font-weight: bold;">P.S</span></br>
            <span style="color: #00007C; font-size: 14px; font-weight: bold;">
                At HomeLet we cover over<br/>
                &pound;550 million worth <br/>
                of tenants&rsquo; contents.
            </span>
        </td>
    </tr>
</table>
