<div id="msp_div" style="display:none;">
    <div class="alert alert-warning">
        <p class="tertiary-colour"><strong>Minimum Standard of Protection</strong></p>
        <p>Please be aware that in your postcode area, you will need a minimum standard of protection in place at your home. This is a condition of your cover but it&rsquo;s nothing to worry about because it doesn't affect your premium.</p>
        <p>Please read through the policy wording <a href="http://homelet.co.uk/assets/documents/HomeLet-Tenants-Insurance-Policy-Summary.pdf" target="_blank">here</a> to make sure that you fully understand the requirements of your Tenant's Content Insurance+ policy before buying a policy with us. If you have any questions please do not hesitate to contact us on 0845 117 6000.</p>
        <p class="tertiary-colour"><strong>What do I need to do to meet them?</strong></p>
        <p>We simply ask that you have secure locks for all of your doors. This means that all of your external doors must be fitted with a deadlock or key operated security bolts at both the top and bottom of your doors, and securely closed at night and when you&rsquo;re not at home.</p>
        <p>We also ask that all of your basement and ground level accessible* windows, skylights and fanlights, that can be opened, are also secured with window locks that have detachable keys, and are securely closed at night and when you&rsquo;re not at home.</p>
        <p>Please read through the policy wording <a href="http://homelet.co.uk/assets/documents/HomeLet-Tenants-Insurance-Policy-Summary.pdf" target="_blank">here</a> to make sure that you fully understand the requirements for your cover before buying a policy with us.  If you have any questions please do not hesitate to contact us on 0845 117 6000.</p>
        <p>* By 'accessible' we mean any windows, fanlights and skylights that could possibly be entered from the outside of your home by a person of normal physical ability, without the need to bring anything to your home or to use a ladder, step ladder or scaffolding found at your home in order to do so.</p>
        <p class="tertiary-colour"><strong>What happens if I don&rsquo;t meet the requirements?</strong></p>
        <p>If the minimum standard of protection is not met then unfortunately you will not be covered for loss or damage by Theft, Attempted Theft or Malicious Act as a consequence of Theft at your home.</p>
        <p>Please read through the policy wording <a href="http://homelet.co.uk/assets/documents/HomeLet-Tenants-Insurance-Policy-Summary.pdf" target="_blank">here</a> to make sure that you fully understand the requirements for your cover before buying a policy with us.  If you have any questions please do not hesitate to contact us on 0845 117 6000.</p>
    </div>
</div>