<div class="corporate main">
    <div class="col-sm-8">
        <div class="content">
            <h1>Application error</h1>
            <p>
                <strong>We&rsquo;re sorry, an error has occurred.</strong><br />
                <br />
                Our technical team have been notified.<br />
            </p>
            <p>
                If you wish to contact us about this error please email <a href="mailto:homeletitservicedesk@homelet.co.uk">homeletitservicedesk@homelet.co.uk</a><br />
            </p>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="panel panel-secondary">
            <h3>Need help?</h3>
            <p class="large tertiary-colour">Call: 0845 117 6000</p>
            <p>We&rsquo;re open from:</p>
            <table class="table table-condensed">
                <tr>
                    <td>Weekdays</td>
                    <td>8:30am - 6:30pm</td>
                </tr>
                <tr>
                    <td>Saturday</td>
                    <td>9:30am - 1:00pm</td>
                </tr>
            </table>
            <p>We&rsquo;re always happy to help.</p>
        </div>
    </div>
</div>