<p>Becoming a HomeLet customer couldn&rsquo;t be easier. Our online application form is short and simple so you can be up and running straight away.</p>
<p>Just before you get started you&rsquo;ll need to gather together some key information and here&rsquo;s what you&rsquo;ll need.</p>

<h3>Details about your company</h3>

<ul id="details">
	<li>The date your company was established</li>
	<li>Your company registration number, if incorporated.</li>
	<li>Your head office contact details</li>
	<li>The names and addresses of all your partners or directors</li>
	<li>If you&rsquo;re a partnership we&rsquo;ll need the date of birth of your partners</li>
	<li>If you&rsquo;re a sole trader we&rsquo;ll need your national insurance number</li>
</ul>

<p>Your Professional Indemnity (PI) insurance details including your renewal date, policy number and the name of the company you have your policy with.    Don&rsquo;t worry if you haven&rsquo;t got PI Insurance, HomeLet can set this up for you.</p>
<p>We love to reward our customers and we will pay you commission on every insurance policy you sell.  Simply let us know your bank account details and you are ready to go.</p>
<p>Because HomeLet is regulated by the Financial Conduct Authority (FCA), it&rsquo;s really important to us that you have the most appropriate FCA status for your business.   Therefore when you become a HomeLet customer, we'll automatically make you an Introducer Appointed Representative* (IAR) with us and all you need to do is complete the application form. We think this could be the best choice for your business because it means you and your customers can still buy insurance from HomeLet and you can receive commission on every insurance sale.   If you have any questions simply contact your HomeLet Representative or just give us a call on 0845 1557999.</p>
<p>*subject to satisfactorily verifying your companies identity by checking the details supplied by you within the application form against those held on a number of databases such as information from the Electoral Register and fraud prevention agencies.</p>
