<div class="letting-agents">
    <div class="wrapper two-col">
        <div class="content">
            <form action="" method="post" enctype="application/x-www-form-urlencoded">
            	<div class="form_section one-col">
					<div>
						<?php echo $this->element->homelet_admin_code; ?>
					</div>
					<div>
						<?php echo $this->element->acceptance_name; ?>
					</div>
					<div>
						<?php echo $this->element->date_of_acceptance; ?>
					</div>
					<div>
						<?php echo $this->element->confirm; ?>
					</div>
					<div>
						Download a copy of the term and conditions here 
					</div>
				</div>
                <?php echo $this->partial('partials/form-navigation.phtml', array('stepNum' => $this->stepNum, 'stepMax' => $this->stepMax)); ?>
            </form>
        </div>
        <?php  echo $this->lettingAgentsSidebar($this->errorsHtml, $this->stepNum, $this->stepMax); ?>        
    </div>
</div>