Hello,

You're almost there! We just need you to validate your email address for your My HomeLet account by copying the validation link below directly into your internet browser:

<?php echo $this->metaData['homeletWebsite']; ?>/my-homelet/activate-account?<?php echo $this->metaData['activationLink']; ?>&utm_source=Automated+email&utm_medium=Email&utm_content=Validate+account&utm_campaign=MyHomeLet


Once you've validated your email address, you'll be able to access the full range of features and benefits available to you through your My HomeLet account.

Just to let you know, this is an automated message which is unable to receive or respond to replies. If you'd like to get in touch with us please visit our
contact us page at <?php echo $this->metaData['homeletWebsite']; ?>/contact-us?utm_source=Automated+email&utm_medium=Email&utm_content=Validate+account&utm_campaign=MyHomeLet.
