
<p>Hello <?php echo $this->metaData['firstname']; ?>,</p>

<p>
    Welcome to My HomeLet, you&rsquo;re now ready to access a range of online features, which includes secure access to policy documents for all HomeLet insurance customers.
</p>

<p>
    You can also:
</p>

<ul>
    <li>manage your user details</li>
    <li>view and complete insurance quotes you&rsquo;ve completed online</li>
</ul>

<p>
    Just to let you know, this is an automated message which is unable to receive or respond to replies. If you&rsquo;d like to get in touch with us please visit our
    <a href="<?php echo $this->metaData['homeletWebsite']; ?>/contact-us?utm_source=Automated+email&utm_medium=Email&utm_content=Registration+complete&utm_campaign=MyHomeLet">contact us page</a>.
</p>
