Hello <?php echo $this->metaData['firstname']; ?>,

Welcome to My HomeLet, you're now ready to access a range of online features, which includes secure access to policy documents for all HomeLet insurance customers.

You can also:
 * manage your user details
 * view and complete insurance quotes you've completed online

Just to let you know, this is an automated message which is unable to receive or respond to replies. If you'd like to get in touch with us please visit our
contact us page at <?php echo $this->metaData['homeletWebsite']; ?>/contact-us?utm_source=Automated+email&utm_medium=Email&utm_content=Registration+complete&utm_campaign=MyHomeLet.
