<p>Hello <?php echo $this->metaData['firstname']; ?>,</p>

<p>
    Thank you for choosing HomeLet to provide your insurance cover. As a HomeLet customer you can access My HomeLet, this is a secure service that lets you view all of your policy documents online.  
</p>

<h2>What do you need to do?<h2>

<p>
    Registering your My HomeLet account is quick and easy, simply:
<p>

<?php $_activation_url = $this->metaData['homeletWebsite'] . '/my-homelet/activate-account?' . $this->metaData['activationLink'] .
    '&utm_source=Automated+email&utm_medium=Email&utm_content=Validate+account&utm_campaign=MyHomeLet' ?>

<p class="wrapped">
    <a href="<?php echo $_activation_url ?>">
        Activate My HomeLet account.
    </a>
</p>

<p>
    Once you&rsquo;ve validated your email address, you&rsquo;ll be able to access the full range of features and benefits available to you through your My HomeLet account.
</p>

<p>
    Just to let you know, this is an automated message which is unable to receive or respond to replies. If you&rsquo;d like to get in touch with us please visit our
    <a href="<?php echo $this->metaData['homeletWebsite']; ?>/contact-us?utm_source=Automated+email&utm_medium=Email&utm_content=Validate+account&utm_campaign=MyHomeLet">contact us page</a>.
</p>
