                                                            <p>
                                                                Kind regards,<br/>
                                                                The HomeLet Team
                                                            </p>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                        <!-- Grey inner footer -->
                                        <tr>
                                            <td bgcolor="#333" align="right" style="-webkit-border-bottom-right-radius: 20px; -webkit-border-bottom-left-radius: 20px; -moz-border-radius-bottomright: 20px; -moz-border-radius-bottomleft: 20px; border-bottom-right-radius: 20px; border-bottom-left-radius: 20px; padding: 15px;">
                                                <font color="white"><strong>Keep up with HomeLet on Facebook and Twitter <a href="http://www.facebook.com/pages/HomeLet/106776409363786" target="_blank"><img src="<?php echo $this->metaData['homeletWebsite']; ?>/assets/common/images/icon-facebook.png" alt="Facebook" align="absmiddle" /></a> <a href="http://twitter.com/homelet" target="_blank"><img src="<?php echo $this->metaData['homeletWebsite']; ?>/assets/common/images/icon-twitter.png" alt="Twitter" align="absmiddle" /></a></strong></font>
                                            </td>
                                        </tr>
                                        <!-- /Grey inner footer -->
                                    </table>
                                    <!-- /White bg inner -->

                                    <!-- Compliance info footer -->
                                    <p class="footer">
                                        HomeLet is a trading name of Barbon Insurance Group Limited which is authorised and regulated by the Financial Conduct Authority for insurance mediation. 
                                        Registered in England number 3135797. Registered office address: Hestia House, Edgewest Road, Lincoln, LN6 7EL.
                                        The information within this email is confidential.<br/>

                                        If you are not the named addressee you should not disseminate, distribute or copy this email. Please notify HomeLet immediately if you have received this email by mistake and delete it from your system.
                                        If you are required to respond to this email with confidential information, whether about yourself or any other individual, please make sure you do this via a secure method.<br/>

                                        This email and the information it contains may also be legally privileged and protected by law. Access by the intended recipient only is authorised. Any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting, on any information contained in this email is hereby excluded.
                                        Views and opinions expressed in this email or attachments are those of the author and are not necessarily agreed or authorised by HomeLet. HomeLet may monitor emails sent or received for operational or business reasons as permitted by law.
                                    </p>
                                    <p class="footer" style="text-align: left;"><?php echo $this->metaData['templateId']; ?></p>
                                    <!-- /Compliance info footer -->

                                </td>
                            </tr>
                        </table>
                        <!-- /E-mail content -->

                    </td>
                </tr>
            </table>
            <!-- /Grey bg outer -->

        </center>
    </body>
</html>
