Hello <?php echo $this->metaData['firstname']; ?>,

Thank you for choosing HomeLet to provide your insurance cover. As a HomeLet customer you can access My HomeLet, this is a secure service that lets you view all of your policy documents online.

What do you need to do?  

Registering your My HomeLet account is quick and easy, simply:
   .   Visit our registration page at <?php echo $this->metaData['homeletWebsite']; ?>/my-homelet/partial-registration?<?php echo $this->metaData['activationLink']; ?>
   .   Complete the short online registration process
   .   Validate your email address - and you're done!     

Once you've registered your account, we'll send you notifications by email to let you know if there are any new documents for you to view online - so you'll never miss a thing.  

Just to let you know, this is an automated message which is unable to receive or respond to replies. If you'd like to get in touch with us please visit our
contact us page at <?php echo $this->metaData['homeletWebsite']; ?>/contact-us.
