<p>Hello <?php echo $this->metaData['firstname']; ?>,</p>

<p>
    Thank you for choosing HomeLet to provide your insurance cover.
    As a HomeLet customer you can access My HomeLet, this is a secure service that lets you view all
    of your policy documents online.
</p>

<p>
   <H3>What do you need to do?</H3> 
</p>
<p>
    Registering your My HomeLet account is quick and easy, simply:
</p>
<ul>
   <li> Visit our <a href="<?php echo $this->metaData['homeletWebsite']; ?>/my-homelet/partial-registration?<?php echo $this->metaData['activationLink']; ?>">registration page </a></li>
   <li> Complete the short online registration process </li>
   <li> Validate your email address - and you&rsquo;re done! </li>
</ul>

<p>
    Once you&rsquo;ve registered your account, we&rsquo;ll send you notifications by email to let you
    know if there are any new documents for you to view online - so you&rsquo;ll never miss a thing.
</p>

<p>
    Just to let you know, this is an automated message which is unable to receive or respond to replies.
    If you&rsquo;d like to get in touch with us please visit our
    <a href="<?php echo $this->metaData['homeletWebsite']; ?>/contact-us">contact us page</a>.
</p>
