
<p>
    Dear <?php echo $this->metaData['name']; ?>,
</p>

<p>
    Following your request we&rsquo;ve reset your password and created a new temporary password for your My HomeLet account.
</p>

<p>
    Here&rsquo;s your temporary password: <strong><?php echo $this->metaData['password']; ?></strong>
</p>

<p>
    We suggest that you use this temporary password only to
    <a href="<?php echo $this->metaData['homeletWebsite']; ?>/my-homelet/login?utm_source=Automated+email&utm_medium=Email&utm_content=Password+reset&utm_campaign=MyHomeLet">login to your account</a>
    and then change it in your account settings to a password that’s more memorable for you.
</p>

<p>
    Welcome back!
</p>
