<script type="text/javascript">

$(function() {

    // Dashboard expander
    $('.foldlink').each(function() {
        $(this).next('.foldable').hide();
        $(this).click(function() {
            $(this).toggleClass('unfolded');
            if ($(this).hasClass('unfolded')) {
                $(this).next('.foldable').slideDown();
            } else {
                $(this).next('.foldable').slideUp();
            }
        });
    });

    // Stripe the nested divs
    $('.stripeMe').each(function() {
        $('div:even', this).addClass('alt');
    });

    <?php /* Set up lazy loading of user administration section. */ ?>
    <?php if ($this->functionAccess['userAdministration']) { ?>
        var userAdministrationLoaded = false;
        function loadUserAdministration(callback) {
            if (!userAdministrationLoaded) {
                $('#userAccounts').load('/ajax/settings-user-accounts', callback);
                userAdministrationLoaded = true;
            }
        }

        <?php /* When user admin is opened out, load content via AJAX. */ ?>
        $('#userAccounts').parent().prev().click(function () {
            loadUserAdministration(function() {});
        });
    <?php } ?>


    <?php
    // When this page loads, should a section be pre-opened out, eg, when a user
    //   submits any of the subforms?
    $sectionName = ''; // Used by jQuery facebox feedback for title
    if (isset($_GET['show'])) {
        $divId = '';
        switch($_GET['show']) {
            case 'emailAddresses':
                $divId = 'agentEmailAddresses';
                $sectionName = 'Email Addresses';
                break;
            case 'detailsPersonal':
                $divId = 'agentDetailsPersonal';
                $sectionName = 'My Account';
                break;
            case 'newsTicker':
                $divId = 'newsForm';
                $sectionName = 'News Ticker Settings';
                break;
            // User account is slightly more complex as we also need to open out
            //   the actual user updated as identified by user ID
            case 'userAdministration':
                $divId = 'userAccounts';
                $sectionName = 'User Administration';
                $userId = (isset($_GET['userId'])) ? preg_replace('/\D/', '', $_GET['userId']) : '';
                ?>
                loadUserAdministration(function() {
                    $('#foldable1_<?php echo $userId; ?>').hide();
                    $('#foldable2_<?php echo $userId; ?>').show();
                });
                <?php
                break;
            case 'uploadConnectLogo':
                $divId = 'modifyConnectLogo';
                $sectionName = 'Company Logo for Connect';
                break;
            case 'uploadDocumentLogo':
                $divId = 'modifyDocumentLogo';
                $sectionName = 'Company Logo for Documents';
                break;
        }
        // Open out section
        ?>
        $('#<?php echo $divId; ?>').parent().show().prev().addClass('unfolded');
        <?php
    }
    ?>
});
</script>
<div class="wrapper one-col">
    <?php echo $this->breadCrumbTrail(); ?>
    <div class="content">
        <?php
        if (isset($this->flashMessages) && count($this->flashMessages) > 0) {
            ?>
            <script type="text/javascript">
            $(window).load(function() {
                setTimeout(function() {
                    $.facebox(
                        '<?php echo $sectionName; ?>',
                        '<ul style="list-style-type: none; display: block;"><?php
                            foreach($this->flashMessages as $message) {
                                $m = addslashes($message);
                                echo "<li>{$m}</li>";
                            }
                        ?></ul>'
                    );
                }, 500);
            });
            </script>
            <?php
        }
        ?>
        <p>
            This page gives you the option to update your Connect settings<?php echo (($this->userRole == 'Master') ? ' and those of your users' : '.  If you need to update your unavailable settings, please check with your master user(s)'); ?>.
        </p>
        <p>
            You can also choose whether to display the news ticker at the bottom of the screen.  <?php echo (($this->userRole == 'Master') ? 'As a master user you may enable/disable the availability of this feature for all your users' : 'Your master user(s) may enable/disable the availability of this feature'); ?>.
        </p>

        <div class="dashboard settings">

            <?php if ($this->functionAccess['emailAddresses']) { ?>

                <div class="header foldlink">
                    <a name="emailAddresses"></a>Email Addresses
                </div>

                <div class="dashboardContent foldable" style="display: none;">

                    <h2 class="form">Email Addresses</h2>
                    <p>This section allows you to change the email addresses we use to contact you. If no email address is entered for a certain contact type we will use the general email address.</p>
                    <form name="agentEmailAddresses" id="agentEmailAddresses" method="post" action="/settings?show=emailAddresses#emailAddresses">
                        <?php echo $this->formEmailAddresses; ?>
                    </form>

                </div>

            <?php } ?>

            <div class="header foldlink">
                <a name="detailsPersonal"></a>My Account
            </div>

            <div class="dashboardContent foldable" style="display: none;">

                <h2 class="form" style="clear: both;">My Account</h2>
                <form name="agentDetailsPersonal" id="agentDetailsPersonal" method="post" action="/settings?show=detailsPersonal#detailsPersonal">
                    <?php echo $this->formMyAccount; ?>
                    <input id="next" class="nav-agents-button" type="submit" name="updateMyAccount" value="Update my details" onclick="if ($('#agentDetailsPersonal input[name=master]').length && !$('#agentDetailsPersonal input[name=master]').is(':checked')) { if(confirm('Please select OK to confirm that you\'d like to revoke your master user status')){return true;}else{return false;} }" />
                </form>

            </div>

            <?php if ($this->functionAccess['newsTickerSettings']) { ?>

                <div class="header foldlink">
                    <a name="newsTicker"></a>News Ticker Settings
                </div>

                <div class="dashboardContent foldable" style="display: none;">

                    <h2 class="form">News Ticker Settings</h2>
                    <p>This section lets you choose whether to display the news ticker at the bottom of the screen.<?php echo (($this->userRole == 'Master') ? '  You can enable/disable all your users from seeing the news ticker with the \'Allow news ticker for all users\' option.' : ''); ?></p>
                    <?php
                    if ($this->userRole != 'Master' && !$this->allowNewsTickerGlobal) {
                        echo '<p><strong>The news ticker has been disabled by your master user(s)</strong></p>';
                    }
                    ?>
                    <form id="newsForm" method="post" action="/settings?show=newsTicker#newsTicker">
                        <p>
                            <?php if ($this->userRole == 'Master') { ?>
                                <input type="checkbox"<?php echo (($this->allowNewsTickerGlobal) ? ' checked="checked"' : '');?> name="allowNewsGlobal" value="yes" /> Allow news ticker for all users<br>
                                <input type="checkbox"<?php echo (($this->allowNewsTickerMine) ? ' checked="checked"' : '');?> name="allowNewsMine" value="yes" /> Show news ticker for me<br>
                            <?php } else { ?>
                                <input type="checkbox"<?php echo (($this->allowNewsTickerMine) ? ' checked="checked"' : '');?> name="allowNewsMine" value="yes" /> Show news ticker<br>
                            <?php } ?>
                            <br />
                            News categories: (<a onclick="$('#newsForm input.categoryChoice[type=checkbox]').attr('checked', 'checked'); return false;" href="#">Select all</a> | <a onclick="$('#newsForm input.categoryChoice[type=checkbox]').removeAttr('checked'); return false;" href="#">Select none</a>)<br />
                        </p>
                        <ul id="news-categories">
                            <?php foreach($this->newsCategories as $nc) { ?>
                                <li><input type="checkbox"<?php echo ((isset($this->newsCategoryFilter[$nc->id])) ? ' checked="checked"' : ''); ?> value="yes" name="cat_<?php echo $nc->id; ?>" class="categoryChoice" /> <?php echo $nc->source; ?>: <?php echo $nc->name; ?></li>
                            <?php } ?>
                        </ul>
                        <input class="nav-agents-button" type="submit" value="Save Preferences" name="newsSubmit" id="next" />
                    </form>

                </div>

            <?php } ?>

            <?php if ($this->functionAccess['userAdministration']) { ?>

                <div class="header foldlink">
                    User Administration
                </div>

                <div class="dashboardContent foldable" style="display: none;">

                    <h2 class="form">User Administration</h2>
                    <p>
                        This section gives you the option to add a new Connect user, delete an existing user &ndash; or change the settings for an
                        existing user. Simply click in the box in the columns for the features you'd like each user to have available &ndash; remembering to press &lsquo;Update details&rsquo;
                        for each user you modify.
                    </p>

                    <?php /* Placeholder div that gets replaced via AJAX when section first opens. */ ?>
                    <div id="userAccounts">
                        <p><em>Loading user account details...</em></p>
                        <div style="text-align: center;">
                            <img src="/assets/common/images/ajax-loader.gif" alt="" />
                        </div>
                    </div>

                </div>

            <?php } ?>

            <?php if ($this->functionAccess['uploadConnectLogo']) { ?>

                <div class="header foldlink">
                    <a name="uploadConnectLogo"></a>Upload Company Logo for Connect
                </div>

                <div class="dashboardContent foldable" style="display: none;">

                    <h2 class="form">Upload Company Logo</h2>
                    <div class="warningpromo">
                    <?php
                        $messages = $this->logoMessages;
                        if (count($messages) > 0) {
                            echo "<ul class=\"errors\"><li>";
                            echo implode('</li><li>', $messages);
                            echo "</li></ul>";
                        }
                    ?>
                    </div>

                    <p>This section allows you to upload your agency logo to appear at the top of Connect - please
                        submit it as a GIF, JPEG or PNG no larger than
                        <?php echo number_format($this->params->connect->settings->logoUpload->connect->maxSize->pixels); ?>
                        pixels on each side and no larger than
                        <?php echo number_format($this->params->connect->settings->logoUpload->connect->maxSize->file / 1048576, 1); ?>
                        MB in size.</p>
                    <p>Image files will be resized to (and centred within)
                        <?php echo number_format($this->params->connect->settings->logoUpload->connect->max_x); ?>
                        by <?php echo number_format($this->params->connect->settings->logoUpload->connect->max_y); ?>
                        pixels, so logo images that are roughly this aspect ratio will look best.</p>
                    <form enctype="multipart/form-data" method="post" action="/settings?show=uploadConnectLogo#uploadConnectLogo" name="modifyConnectLogo" id="modifyConnectLogo">
                        <div>
                            <img align="left"
                                 width="<?php echo number_format($this->params->connect->settings->logoUpload->connect->max_x); ?>"
                                 height="<?php echo number_format($this->params->connect->settings->logoUpload->connect->max_y); ?>"
                                 src="<?php echo $this->connectLogoUrl;?>" />
                        </div>
                        <div style="float:right;">
                            <input type="hidden" value="<?php echo $this->params->connect->settings->logoUpload->connect->maxSize->file; ?>" name="MAX_FILE_SIZE" />
                            <input type="file" accept="<?php echo $this->params->connect->settings->logoUpload->mimeTypes->toArray(); ?>" name="logofile" /><br />  <span style="font-size: 0.75em;">(<?php echo number_format($this->params->connect->settings->logoUpload->maxSize->file / 1048576, 1); ?> MB limit of type GIF, JPEG or PNG)</span><br />
                        </div>
                        <div class="clear">
                            <input type="submit" value="Upload New Logo" name="uploadConnectLogo" id="next" />
                            <input type="submit" value="Delete Current Logo" name="deleteConnectLogo" class="next" onclick="if(confirm('Please select OK to confirm that you\'d like to delete the current logo')){return true;}else{return false;}" />
                        </div>
                    </form>

                </div>

            <?php } ?>

            <?php if ($this->functionAccess['uploadDocumentLogo']) { ?>

                <div class="header foldlink">
                    <a name="uploadDocumentLogo"></a>Upload Company Logo for Documents
                </div>

                <div class="dashboardContent foldable" style="display: none;">

                    <h2 class="form">Upload Company Logo</h2>
                    <div class="warningpromo">
                        <?php
                        $messages = $this->logoMessages;
                        if (count($messages) > 0) {
                            echo "<ul class=\"errors\"><li>";
                            echo implode('</li><li>', $messages);
                            echo "</li></ul>";
                        }
                        ?>
                    </div>

                    <p>This section allows you to upload your agency logo to appear at the top of Rent Recovery Plus
                        documents - please submit it as a JPEG or PNG between
                        <?php echo number_format($this->params->connect->settings->logoUpload->document->minSize->pixels); ?> and
                        <?php echo number_format($this->params->connect->settings->logoUpload->document->maxSize->pixels); ?>
                        pixels on each side, larger than
                        <?php echo number_format($this->params->connect->settings->logoUpload->document->maxSize->file / 1048576, 1); ?>
                        MB in size
                        <?php if (isset($this->params->connect->settings->logoUpload->document->minDPI)) {
                                 echo 'and at least ' . $this->params->connect->settings->logoUpload->document->minDPI . 'dpi';
                              } ?>
                    </p>
                    <form enctype="multipart/form-data" method="post" action="/settings?show=uploadDocumentLogo#uploadDocumentLogo" name="modifyDocumentLogo" id="modifyDocumentLogo">
                        <div>
                            <img src="<?php echo $this->documentLogoUrl;?>" />
                        </div>
                        <div style="float:right;">
                            <input type="hidden" value="<?php echo $this->params->connect->settings->logoUpload->document->maxSize->file; ?>" name="MAX_FILE_SIZE" />
                            <input type="file" accept="<?php echo $this->params->connect->settings->logoUpload->mimeTypes->toArray(); ?>" name="logofile" /><br />  <span style="font-size: 0.75em;">(<?php echo number_format($this->params->connect->settings->logoUpload->maxSize->file / 1048576, 1); ?> MB limit of type GIF, JPEG or PNG)</span><br />
                        </div>
                        <div class="clear">
                            <input type="submit" value="Upload New Logo" name="uploadDocumentLogo" id="next" />
                            <input type="submit" value="Delete Current Logo" name="deleteDocumentLogo" class="next" onclick="if(confirm('Please select OK to confirm that you\'d like to delete the current logo')){return true;}else{return false;}" />
                        </div>
                    </form>

                </div>

            <?php } ?>

        </div>
    </div>
</div>
