<font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#0C2F6B">
    Dear <?php echo $this->metaData['name']; ?>, <br />
    <br />
    Thank you for visiting our website and requesting a quote for your Landlord's insurance. Just to remind you, our landlord’s insurance can protect your building, contents and even cover your rent!<br />
    <br />
    You can easily view your quote online by clicking <a href="http://homelet.co.uk/landlords/insurance-quote/retrieve">homelet.co.uk/landlords/insurance-quote/retrieve</a> and logging in with your username and password.<br />
    <br />
    Once you've logged in you can view your quotes, make changes to your quotes and buy a policy.<br />
    <br />
    If you have any questions why not call one of our friendly customer services team on <font color="#7AC142">0845 117 6000</font> from 8.30am-8pm Monday to Friday and 9.30am-1pm Saturday.<br />
    <br />
    So what are you waiting for? Protect your <font color="#7AC142">building</font> and <font color="#7AC142">contents</font> today with HomeLet and you can be rest assured that if something unexpected happens we've got your covered!<br />
    <br />
    <br />
    Many thanks<br />
    <br />
    The HomeLet Team<br />
</font>