<style>
#product_standard {
    background: url("/assets/cms/images/letting-agents/ProductStandard.png") no-repeat scroll 0 0 transparent;
    float: left;
    height: 120px;
    margin-left: 2px;
    text-indent: -9999px;
    width: 206px;
}
#product_premier {
    background: url("/assets/cms/images/letting-agents/ProductPremier.png") no-repeat scroll 0 0 transparent;
    float: left;
    height: 120px;
    margin-left: 2px;
    text-indent: -9999px;
    width: 206px;
}
#product_premplus {
    background: url("/assets/cms/images/letting-agents/ProductPremierPlus.png") no-repeat scroll 0 0 transparent;
    float: left;
    height: 120px;
    margin-left: 2px;
    text-indent: -9999px;
    width: 206px;
}
#product_standard:hover, #product_premier:hover, #product_premplus:hover {
    background-position: center bottom;
}
#agentselect label.onactive {
    background-position: center bottom;
}
#agentselect .myradio {
    background-position: center bottom;
}

</style>
<script type="text/javascript">
$(document).ready(function($) {
	$('#product_standard').addClass("myradio").css({opacity: 100});
	
	$(".fakeoption1").click(function () {
		$(".fakeoption1").removeClass("myradio").removeClass("onactive");
		$(this).addClass("myradio").css({opacity: 100});
		var value = $(this).text();
		$("#agent_type").val(value);
		validatePage();
	}); 
	
	// Show/hide warning promo and professional indemity section
	$("#professionalIndemnityNoPromo").hide();
	$("#indemnity-section").hide();
	$("select[name='pi_cert']").change(function() {
		if($("select[name='pi_cert']").val() == "no"){
			$("#professionalIndemnityNoPromo").show();
			$("#indemnity-section").hide();
		}else if ($("select[name='pi_cert']").val() == "yes"){
			$("#professionalIndemnityNoPromo").hide();
			$("#indemnity-section").show();
		}else{
			$("#professionalIndemnityNoPromo").hide();
			$("#indemnity-section").hide();
		}
	});

	// Show/hide ico date
	$("#ico-date").hide();
	$("select[name='ico_select']").change(function() {
		if($("select[name='ico_select']").val() == "no"){
			$("#ico-date").hide();
		}else if ($("select[name='ico_select']").val() == "yes"){
			$("#ico-date").show();
		}else{
			$("#ico-date").hide();
		}
	});
	
});
</script>
 <?php echo $this->element->agent_type; ?>
<div style="height:120px;" class="col" id="agentselect">
	<label title="standard" id="product_standard" class="fakeoption1" style="opacity: 100;">standard</label>
	<label title="premier" id="product_premier" class="fakeoption1" style="opacity: 100;">premier</label>
       
</div>

<div class="form_section one-col" style="border-top: #FFF">
	<div>
		<?php echo $this->element->ico_select; ?>
	</div>
	<div id="ico-date">
		<?php echo $this->element->ico_renewal_date; ?>
	</div>	
</div> 
           	
<div class="form_section one-col" style="border-top: #FFF">
	<div>
		<?php echo $this->element->pi_cert; ?>
	</div>
</div>

<div id="professionalIndemnityNoPromo" class="warningpromo" style="display: block;">
	<span class="warningpromo-content">
		<p><strong>Professional Indemnity</strong></p>
		<p>No professional indemnity cover? Don&rsquo;t put your business at risk, it&rsquo;s easy and affordable to protect yourself against potential claims. For instant peace of mind, call us on 0845 117 6033.</p>
	</span>
</div>

