<div class="form_section one-col">
	<div>
		<?php echo $this->element->fax_number; ?>
	</div>
	<div>
		<?php echo $this->element->company_website_address; ?>
	</div>	
	<div>
		<?php echo $this->element->fax_number; ?>
	</div>
	<div>
		<?php echo $this->element->company_website_address; ?>
	</div>
	<div>
		<?php echo $this->element->fax_number; ?>
	</div>
	<div>
		<?php echo $this->element->company_website_address; ?>
	</div>
	<div>
		<?php echo $this->element->fax_number; ?>
	</div>				
</div>