<div class="form_section one-col">
	<div> 
		<?php echo $this->element->organisation_type; ?>
	</div>
	<div>
		<?php echo $this->element->date_established; ?>
	</div>
	<div>
		<?php echo $this->element->is_associated; ?>
	</div>
	<div>
		<?php echo $this->element->associated_text; ?>
	</div>
	<div>
		<?php echo $this->element->contact_name; ?>
	</div>
	<div>
		<?php echo $this->element->contact_number; ?>
	</div>			
	<div>
		<?php echo $this->element->general_email; ?>
	</div>		
</div>