<div class="form_section one-col" id="indemnity-section" style="border-top: #FFF">
	<div>
		<?php echo $this->element->current_insurer; ?>
	</div>
	<div>
		<?php echo $this->element->policy_number; ?>
	</div>	
	<div>
		<?php echo $this->element->retroactive_date; ?>
	</div>
	<div>
		<?php echo $this->element->next_renewal_date; ?>
	</div>
	<div>
		<?php echo $this->element->placing_broker; ?>
	</div>
	<div>
		<?php echo $this->element->indemnity; ?>
	</div>
	<div>
		<?php echo $this->element->excesses; ?>
	</div>				
</div>