<?php

namespace Iris\Common\Enumerations;

/**
 * Class RecommendationStatuses
 * 
 * @package Iris\Common\Enumerations
 * @author Alex Eves <alex.eves@barbon.com>
 */
final class RecommendationStatuses
{
    const ACCEPTABLE = 'ACCEPTABLE';
    const ACCEPTABLE_WITH_CONDITION = 'ACCEPTABLE_WITH_CONDITION';
    const ACCEPTABLE_WITH_GUARANTOR = 'ACCEPTABLE_WITH_GUARANTOR';
    const ACCEPTABLE_WITH_GUARANTOR_WITH_CONDITION = 'ACCEPTABLE_WITH_GUARANTOR_WITH_CONDITION';
    const NOT_ACCEPTABLE = 'NOT_ACCEPTABLE';
    const AWAITING_FURTHER_INFORMATION = 'AWAITING_FURTHER_INFORMATION';
    const ZERO_RENT_COTENANT_NOT_ACCEPTABLE = 'ZERO_RENT_COTENANT_NOT_ACCEPTABLE';
    const AWAITING_COMPLETION_OF_LEAD_TENANT = 'AWAITING_COMPLETION_OF_LEAD_TENANT';
    const ZERO_RENT_COTENANT_ACCEPTABLE = 'ZERO_RENT_COTENANT_ACCEPTABLE';
}