<?php echo $this->tenantsQuoteSubHeader(3); ?>
<div class="corporate">
    <div class="wrapper">
        <div class="content">
            <div class="form_section">
                 <div>
                     <p>
                         You have been referred to our Underwriting department and they have been notified by email with details of your application.<br />
                         You will be contacted shortly as regards your application.<br />
                         If you have any queries please phone 0845 117 6000<br />
                         Your quote number(s) are <?php echo $this->policyNumber; ?><br />
                     </p>
                 </div>
             </div>
        </div>
    </div>
</div>