<h1>Edit Header Quote</h1>
<script>
	$(function() {
	    $( "#sortable" ).disableSelection();
	    <?php if ($this->saved || $this->added) { ?>
	        setTimeout(function() {
	            $('.done').animate({opacity: "0"}, 1000).slideUp(500);
	        }, 3000);
	    <?php } ?>
	
	    var availableTags = [<?php echo $this->quoteTags; ?>];
	    function split( val ) {
	        return val.split( /,\s*/ );
	    }
	    function extractLast( term ) {
	        return split( term ).pop();
	    }
	    $( "#tags" )
	        .bind( "keydown", function( event ) {
	            if ( event.keyCode === $.ui.keyCode.TAB &&
	                    $( this ).data( "autocomplete" ).menu.active ) {
	                event.preventDefault();
	            }
	        })
	        .autocomplete({
	            minLength: 0,
	            source: function( request, response ) {
	                // delegate back to autocomplete, but extract the last term
	                response( $.ui.autocomplete.filter(
	                    availableTags, extractLast( request.term ) ) );
	            },
	            focus: function() {
	                // prevent value inserted on focus
	                return false;
	            },
	            select: function( event, ui ) {
	                var terms = split( this.value );
	                // remove the current input
	                terms.pop();
	                // add the selected item
	                terms.push( ui.item.value );
	                // add placeholder to get the comma-and-space at the end
	                terms.push( "" );
	                this.value = terms.join( ", " );
	                return false;
	            }
	        });
	});
</script>
<?php if ($this->saved) { ?>
    <p class="msg done">Changes saved successfully!</p>
<?php } ?>
<form method="post">
    <p>
        <label for="title" class="req">Title:</label><br />
        <textarea class="quoteeditor input-text" name="title" id="title" cols="100" rows="2"><?php echo $this->title ?></textarea>
    </p>
    <p>
        <label for="subtitle" class="req">Sub-Title:</label><br />
        <textarea class="header-subtitle input-text" name="subtitle" id="quote" cols="100" rows="4"><?php echo $this->subtitle ?></textarea>
    </p>
    <p>
        <label for="tags" class="req">Tags:</label><br />
        <input type="text" size="60" class="input-text" id="tags" name="tags" value="<?php echo $this->tags ?>"/>
    </p>
    <div class="box-02">
        <input type="hidden" name="id" id="id" value="<?php echo $this->id ?>" />
        <p class="nom">
            <input type="submit" value="Save" class="input-submit" />
            <input type="button" value="Cancel" class="input-button" onclick="javascript:history.go(-1)" />
        </p>
    </div>
</form>
