<h2>Declaration and Consent</h2>
<div class="form_section one-col">
    <p>
        <b>
           About your reference – the terms must be agreed to by a Company Director or Company Secretary listed on Companies House
        </b>
    </p>

    <p>
        This reference will be completed by HomeLet on behalf of your letting agent.
        HomeLet is part of the Barbon Insurance Group Limited and for the purposes of this application,
        Barbon is the Data Controller as defined in the Data Protection Act 1998 (the “Act”).
    </p>

    <p>
        In order to proceed with this application, you must have the authority to bind the company
        in your capacity to the company as either a company secretary or as a director.
	</p>

    <p>
        To complete the referencing process, HomeLet will consult with a number of sources to
        verify the information, including a licensed credit reference agency.
        As a result of the information received:
    </p>

    <ul style="list-style-type: none;">
        <li>
            HomeLet may pass on any information supplied to your landlord and/or letting agent,
            including the results of any linked verification checks.
        </li>
        <li>
            By consulting with a credit reference agency, HomeLet will share your company&rsquo;s
            information with them and the agency may record the results of this search.
            This search may show how the company conducts payments with other organisations.
            From time to time, this information may also be used for debt tracing and fraud prevention.
            You may request the name and address of the Credit Reference agency HomeLet use and you may
            also apply for a copy of the information they provided to HomeLet.
        </li>
        <li>
            If the company defaults on your rental payments, HomeLet may record this on a centrally held
            database of defaulting tenants and companies, and that such a default could affect any future
            application for tenancies, credit, and/or insurance.
        </li>
        <li>
            HomeLet may use debt collection agencies or tracing agents to trace your whereabouts
            and recover any monies owed to HomeLet.
        </li>
        <li>
            If false or inaccurate information is provided and fraud is identified, details will be passed to fraud
            prevention agencies to prevent fraud and money laundering.
        </li>
    </ul>

    <p>
        Information may be sent to you by email.  This information will only be sufficient enough to
        identify you and it won&rsquo;t be excessive; however you should be aware that information sent
        via electronic means can&rsquo;t be guaranteed to be secure.
    </p>

    <p>
        The provisions of Section 17 of the Housing Act 1996 will apply to this application.
        If any information within this application is found to be untrue it will be grounds to
        terminate the tenancy agreement.
    </p>

    <p>
        <b>
            Please read and complete the following statements carefully – it&rsquo;s important that
            you provide your consent for the checks by marking the boxes next to the text.
        </b>
    </p>

    <p>
        <?php echo $this->element->consent_information_stored; ?>

        Yes, I confirm that the information provided in this application form is true to the best
        of my knowledge, and I&rsquo;m happy with the checks which HomeLet will complete as detailed above.
        These results may be accessed again if my company applies for a tenancy in the future.
    </p>

    <p>
        I also confirm that I have the authority to bind the company in my capacity as either a
        company secretary or as a director of the company; and the information I have given is to
        the best of my knowledge true and accurate.
    </p>

    <div class="autoAlt">
        <?php echo $this->element->representive_name; ?>
    </div>
    <div class="autoAlt">
        <?php echo $this->element->representive_position; ?>
    </div>
    <div class="autoAlt">
        <?php echo $this->element->application_date; ?>
    </div>
    <div>
        <?php echo $this->element->complete; ?>
    </div>
</div>
