<?php
// Tenant Web Application Tracker - e-mail invitation
?>
<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">Dear <strong><?php echo $this->metaData['tenantName']; ?></strong></font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#ff6600" size="4">Track your tenancy application online...</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">Thank you for your recent tenancy application to rent:</font>
</p> 

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077"><strong>
        <?php echo $this->metaData['propertyAddress']; ?>
    </strong></font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">HomeLet will be acting on behalf of <strong><?php echo $this->metaData['lettingAgentName']; ?></strong> to complete your tenant referencing checks. At HomeLet we understand that moving home can be a stressful time, that's why we want to support you wherever we can and keep you updated every step of the way.</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">So we've set up an <a href="<?php echo $this->metaData['tatUrl']; ?>" target="_blank"><font color="#ff6600"><strong>online application tracker</strong></font></a> service, which allows you to see exactly how we're progressing with your referencing checks at the click of a button, just visit <a href="<?php echo $this->metaData['tatUrl']; ?>" target="_blank"><font color="#ff6600"><strong>homelet.co.uk/tenants</strong></font></a> and select 'Track your Reference'.</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">All you'll need to do is provide us with <strong><?php echo $this->metaData['lettingAgentName']; ?></strong> scheme number <strong><?php echo $this->metaData['lettingAgentAsn']; ?></strong>, your HomeLet reference number <strong><?php echo $this->metaData['tenantIrn']; ?></strong> and your date of birth to view the status and progress of your application.</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">
        If you&rsquo;re looking to cover your contents, or your liability as a tenant under your tenancy agreement, then HomeLet may be able to help...
    </font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">
        With HomeLet Tenant&rsquo;s Insurance you can choose to cover your liability as a tenant with our Tenancy Liability Cover, or you can add contents 
        cover to your policy too, with Tenant&rsquo;s Contents Insurance+.
    </font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">
        For more information about HomeLet Tenant&rsquo;s Insurance simply <a href="<?php echo $this->metaData['homeLetUrl']; ?>" target="_blank"><font color="#ff6600"><strong>click here</strong></font></a> 
        or call us on 0845 117 6000, we&rsquo;re always happy to help!
    </font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">Kind regards</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077"><strong>The HomeLet team</strong></font>
</p>
