<font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#0C2F6B">
    <p>
        Dear Agent
    </p>
    <p>
        Thank you for submitting your claim for
        '<?php echo $this->metaData['propertyAddress']; ?>' online. Your claim
        number is <b> <?php echo $this->metaData['claimNumber']; ?></b>, you
        will need this when searching and viewing your claims progress online.
        Your claim will be allocated to a Homelet Claims Handler and you will
        receive confirmation whether your claim has been accepted or declined
        within 4 days.
    </p>
    <p>
        Don't forget you can track the progress of your claim online.
    </p>
    <p>
        Regards
    </p>
    <p>
        HomeLet
    </p>
</font>
