<?php
// Tenant Web Application Tracker - e-mail invitation
?>
<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">Dear <strong><?php echo $this->metaData['tenantName']; ?></strong></font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#ff6600" size="4">Track your tenancy application online...</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">Thank you for your recent tenancy application to rent:</font>
</p> 

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077"><strong>
        <?php echo $this->metaData['propertyAddress']; ?>
    </strong></font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">HomeLet will be acting on behalf of <strong><?php echo $this->metaData['lettingAgentName']; ?></strong> to complete your tenant referencing checks.</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#ff6600" size="4">Don't worry you're in safe hands!</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">At HomeLet we understand that moving home can be a stressful time, that's why we want to support you wherever we can and keep you updated every step of the way.</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">So we've set up an <a href="<?php echo $this->metaData['tatUrl']; ?>" target="_blank"><font color="#ff6600"><strong>online application tracker</strong></font></a> service, which allows you to see exactly how we're progressing with your referencing checks at the click of a button, just visit <a href="<?php echo $this->metaData['tatUrl']; ?>" target="_blank"><font color="#ff6600"><strong>homelet.co.uk/tenants</strong></font></a> and select 'Track your Reference'.</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">All you'll need to do is provide us with <strong><?php echo $this->metaData['lettingAgentName']; ?></strong> scheme number <strong><?php echo $this->metaData['lettingAgentAsn']; ?></strong>, your HomeLet reference number <strong><?php echo $this->metaData['tenantIrn']; ?></strong> and your date of birth to view the status and progress of your application.</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">Kind regards</font>
</p>

<p>
    <font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#000077">The HomeLet Team</font>
</p>
