<?php

// Highcharts colours
//$chartCols = array('4572A7', 'AA4643', '89A54E', '80699B', '3D96AE', 'DB843D', '92A8CD', 'A47D7C', 'B5CA92');

// HL colours
$chartCols = array('FF6F1C', '0C2F6B', 'FDBB30', '7AC142', 'E60E64', '6D1074', '0041B0', '009909');

// New references graph
$yScalePadding = 1.00; // If > 1.00, adds a guaranteed margin between highest bar and top of graph
$yQuantising = 10;

$chartNewRefsData = implode(',', $this->newRefs);
$chartNewRefsAxisLabelsX = implode('|', array_keys($this->newRefs));
$chartNewRefsMaxScaleY = ceil((max($this->newRefs) * $yScalePadding) / $yQuantising) * $yQuantising;
$chartNewRefsAxisLabelsY = '0|' . ($chartNewRefsMaxScaleY / 2) . '|' . $chartNewRefsMaxScaleY;

$chartNewRefsUrl = "https://chart.googleapis.com/chart?cht=bvg&chd=t:{$chartNewRefsData}&chxt=x,y&chxl=0:|{$chartNewRefsAxisLabelsX}|1:|{$chartNewRefsAxisLabelsY}&chs=800x300&chco={$chartCols[2]}&chg=7.1428,50&chbh=47&chds=0,{$chartNewRefsMaxScaleY}&chtt=New%20References%20%28last%2014%20days%29";

// Reference types graph
$chartOpenRefTypesData = implode(',', $this->openRefTypes);
$chartOpenRefTypesLabels = implode('|', array_keys($this->openRefTypes));
$chartOpenRefTypesCols = implode(',', array_slice($chartCols, 0, min(count($chartCols), count($this->openRefTypes))));

$chartOpenRefTypesUrl = "https://chart.googleapis.com/chart?cht=p3&chd=t:{$chartOpenRefTypesData}&chs=407x300&chdl={$chartOpenRefTypesLabels}&chco={$chartOpenRefTypesCols}&chtt=Open%20Reference%20Types%20for%20Referencing%20Estates";

// Reference progress graph
$chartOpenRefProgressData = implode(',', $this->openRefProgress);
$chartOpenRefProgressLabels = implode('|', array_keys($this->openRefProgress));
$chartOpenRefProgressCols = implode(',', array_slice($chartCols, 0, min(count($chartCols), count($this->openRefProgress))));

$chartOpenRefProgressUrl = "https://chart.googleapis.com/chart?cht=p3&chd=t:{$chartOpenRefProgressData}&chs=407x300&chdl={$chartOpenRefProgressLabels}&chco={$chartOpenRefProgressCols}&chtt=Open%20Reference%20Progress%20for%20Referencing%20Estates";

?>
<div class="graphNew">
    <div class="title">New References:</div>
    <img src="<?php echo $chartNewRefsUrl; ?>" />
</div>
<div class="graphType">
    <div class="title">Open Reference Types:</div>
    <img src="<?php echo $chartOpenRefTypesUrl; ?>" />
</div>
<div class="graphProgress">
    <div class="title">Open Reference Progress:</div>
    <img src="<?php echo $chartOpenRefProgressUrl; ?>" />
</div>