<li class="pdf_icon<?php echo (($this->lineEnd) ? ' line_end' : ''); ?>">
    <div class="connect_pdf">

        <div class="pdf_info">
            <a href="#" onclick="deedOfGuarantee(); return false;"><img src="/assets/connect/doc/deedOfGuarantee.thumb.jpg" alt="Deed Of Guarantee" /></a>
            <h4>Deed of Guarantee</h4>
            <a href="#" class="connect_pdf_download" onclick="deedOfGuarantee(); return false;">Download</a>
            <p class="pdf_description">This is a draft Deed of Guarantee that you may wish to use. You&rsquo;ll need to accept our disclaimer, which will pop up when you click on the document, if you do wish to use it.</p>
        </div>

    </div>
</li>