<table>
    <tr>
        <td><strong>API Access Details For</strong></td>
        <td><?php echo htmlentities($this->agentRealName); ?></td>
    </tr>
    <tr>
        <td><strong>Consumer Key</strong></td>
        <td><pre><?php echo htmlentities($this->agentKey); ?></pre></td>
    </tr>
    <tr>
        <td><strong>Consumer Secret</strong></td>
        <td><pre><?php echo htmlentities($this->agentSecret); ?></pre></td>
    </tr>
    <tr>
        <td><strong>Branch UUID</strong></td>
        <td><pre><?php echo htmlentities($this->agentBranch); ?></pre></td>
    </tr>
</table>