<div id="homelet_rentalindex">
    <a href="<?php echo $this->url; ?>" target="_blank" style="text-align: center; display: block; width: 180px; margin: 10px 30px 30px 10px; text-decoration: none;">
        <img src="/assets/connect/images/hri_map.gif" width="200px" /><br />
    </a>
    <p>Find out what&rsquo;s happening to rents in your region.</p>
    <a href="<?php echo $this->url; ?>" target="_blank">View the latest HRI</a>
</div>