<div class="form-sub-section">
    <h2 class="tertiary-colour">
        <span class="help-trigger"><a class="show-form-help"></a></span>
        <span class="field-help hidden-xs hidden-sm">
            <?php echo strip_tags($this->promoContent('tenants-insurance-quote-help-correspondencedetails')); ?>
        </span>
        Your Correspondence Details
    </h2>

    <div class="mobile-help section-help section-help-fullwidth">
        <div class="visible-xs visible-sm">
            <?php echo $this->promoContent('tenants-insurance-quote-help-correspondencedetails'); ?>
        </div>
    </div>

    <div id="same-address-selection">
        <div class="radio form-group">
            <?php echo $this->element->cor_same_address; ?>
        </div>
    </div>

    <?php echo $this->element->cor_house_number_name; ?>

    <div class="form-group">
        <label for="cor_postcode" class="required">Postcode</label>
        <div class="input-group">
            <?php echo $this->element->cor_postcode; ?>
            <span class="input-group-btn">
                <input type="submit" id="cor_postcode_lookup" value="Find address" name="lookup" onclick="getProperties($('#cor_house_number_name').val(), $('#cor_postcode').val(), 'cor_postcode', 'cor_address'); return false;" class="btn btn-tertiary" />
            </span>
        </div>
    </div>

    <div id="cor_address_selector" class="address-selector">
        <div class="form-group">
            <?php echo $this->element->cor_address; ?>
        </div>
    </div>

    <div id="cor_address_details">
        <p>You have selected the following address:</p>
        <dl class="dl-horizontal">
            <dt>Address:</dt>
            <dd>
                <?php echo $this->element->cor_address_line1; ?><br />
                <?php echo $this->element->cor_address_line2; ?><br />
                <?php echo $this->element->cor_address_line3; ?>
            </dd>
            <dt>Postcode:</dt>
            <dd>
                <?php echo $this->element->cor_address_postcode; ?>
            </dd>
        </dl>
        <p>If this is incorrect, please search for a new postcode above.</p>
    </div>
</div>