<div class="section-help">
    <p><a data-target="dpa_additional" class="tertiary-colour">Please click here to read about how we&rsquo;ll use your information.</a></p>
</div>

<div class="form-sub-section">
    <div id="dpa_additional" class="section-help" style="display: none;">
        <p>By providing us with your contact details you consent to being contacted by post, email, text and telephone in relation to your quote for tenants insurance.</p>
        <p>We would also like to keep in contact with you about Barbon Insurance Group offers, products and services, which we feel may be relevant to you as a tenant.</p>
        <p>We won&rsquo;t pass your information on to any third parties without your consent.</p>

        <h3 class="tertiary-colour">Keeping your information secure</h3>
        <p>We&rsquo;re committed to protecting your privacy. We&rsquo;ll only use the information we collect about you lawfully, in accordance with the Data Protection Act 1998.</p>
        <p>If you&rsquo;d like to know more about how we protect your data, please <a href="/terms-of-use" target="_blank" class="tertiary-colour">read our privacy policy</a>.</p>

        <h3 class="tertiary-colour">Changing your contact preferences</h3>
        <p><strong>You can contact us at any time to change your preferences.</strong></p>
        <div class="agree_statement_marketing_sms_and_email">
            <div class="checkbox form-group">
                <label for="dpa_sms_email">
                    <?php echo $this->element->dpa_sms_email; ?>
                    If you&rsquo;d prefer HomeLet do not contact you with any further information by email or SMS please tick this box.
                </label>
            </div>
        </div>
        <div class="agree_statement_marketing_phone_and_post">
            <div class="checkbox form-group">
                <label for="dpa_phone_post">
                    <?php echo $this->element->dpa_phone_post; ?>
                    If you&rsquo;d prefer HomeLet do not contact you with any further information by phone or post please tick this box.
                </label>
            </div>
        </div>
        <div class="agree_statement_details_resale">
            <p>Please tick this box if you&rsquo;re happy for HomeLet to share your information with our trusted partners, for offers, information and products that we think might be of interest to you as a landlord.</p>
            <div class="checkbox form-group">
                <label for="dpa_resale" class="optional">
                    <?php echo $this->element->dpa_resale; ?>
                    I am happy for HomeLet to share my information with trusted partners.
                </label>
            </div>
        </div>
    </div>
</div>