<?php echo $this->headLink(); echo $this->headScript();?>
<img src="/assets/connect/images/homelet-logo.png"/>
<br/><br/>
<div class="reportHeading">Rent Guarantee Renewals Suite</div>
<div class="separator"></div>
<div class="box" style="width:50%">
	<div class="box_title">Email Renewal Documents</div>
	<div class="box_content">
		<?php echo $this->mailDeliveryMsg; ?>
		<div class="separator"></div>
		<input type="button" class="round-button" onclick="location.href='/connect/rentguarantee-renewal'" value=" Return to Renewals Suite "/>&nbsp;
	</div>
</div>