<?php
$imageBaseUrl = $this->metaData['imageBaseUrl'] . 'assets/tenant_mailer/images/';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <!-- Facebook sharing information tags -->
    <meta property="og:title" content="<?php echo $this->metaData['heading']; ?>" />

    <title><?php echo $this->metaData['heading']; ?></title>
    <style type="text/css">
            /* MS-proof specific style, see http://www.campaignmonitor.com/blog/post/3192/add-a-background-image-to-individual-table-cells/ */
        v:* { behavior: url(#default#VML); display: inline-block; }

            /* Client-specific Styles */
        #outlook a{padding:0;} /* Force Outlook to provide a "view in browser" button. */
        body{width:100% !important;} .ReadMsgBody{width:100%;} .ExternalClass{width:100%;} /* Force Hotmail to display emails at full width */
        body{-webkit-text-size-adjust:none;} /* Prevent Webkit platforms from changing default text sizes. */

            /* Reset Styles */
        body{margin:0; padding:0;}
        img{border:0; height:auto; line-height:100%; outline:none; text-decoration:none;}
        table td{border-collapse:collapse;}
        #backgroundTable{height:100% !important; margin:0; padding:0; width:100% !important;}

            /* Template Styles */
        body {
            color: #00346d;
            font-family: 'Trebuchet MS', Helvetica, Arial, sans-serif;
            text-align: left;
            font-size: 12px;
        }
        h1 {
            /*@editable*/ color: #ff6f1c;
            display:block;
            /*@editable*/ font-family: 'Trebuchet MS', Helvetica, Arial, sans-serif;
            /*@editable*/ font-size: 24px;
            /*@editable*/ font-weight: bold;
            /*@editable*/ line-height: 100%;
            margin: 0;
        }
        h1.emailhead {
            /*@editable*/ color: #ffffff !important;
        }
        h2 {
            /*@editable*/ color: #00346d;
            display: block;
            /*@editable*/ font-family: 'Trebuchet MS', Helvetica, Arial, sans-serif;
            /*@editable*/ font-size: 18px;
            /*@editable*/ font-weight: bold;
            /*@editable*/ line-height: 100%;
            margin: 0;
        }
        h3 {
            /*@editable*/ color: #ff6f1c;
            display:block;
            /*@editable*/ font-family: 'Trebuchet MS', Helvetica, Arial, sans-serif;
            /*@editable*/ font-size: 14px;
            /*@editable*/ font-weight: bold;
            /*@editable*/ line-height: 100%;
            margin: 0;
        }
        a {
            font-weight: bold;
            color: #ff6f1c !important;
        }
        p {
            font-size: 13px;
            margin: 1em 0;
        }
        ul li{
            font-size: 13px;
        }
        hr {
            border: 1px solid #9a9a9a;
            margin: 15px 0;
        }
        .highlight,
        a.highlight {
            font-weight: bold;
            color: #ff6f1c;
        }
        .footer {
            font-size: 10px;
            text-align: left;
        }
        .alignContainer {
            position: relative;
        }
            /* Bottom-right alignment for those clients that can see it */
        .alignContainer .alignRightBottom {
            position: absolute;
            right: 0;
            bottom: 0;
            margin: 5px;
        }
        .limargin {
            margin-bottom: 10px;
        }
        p.wrapped {
            word-wrap: break-word;

            /* ms word break */
            -ms-word-break: break-all;
            word-break: break-all;
            word-break: break-word;

            /* webkit hyphens */
            -webkit-hyphens: auto;
            -moz-hyphens: auto;
            hyphens: auto;
        }
    </style>
</head>
<body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
<center>

    <!-- Grey bg outer -->
    <table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" bgcolor="#f2f2f2">
        <tr>
            <td align="center">

                <!-- E-mail contents starts here, keep to 600px as most user read in the preview pane -->
                <table border="0" cellpadding="0" cellspacing="0" width="600" align="center">
                    <tr>
                        <td>
                            <br/><a href="<?php echo $this->metaData['homeletWebsite']; ?>" target="_blank"><img src="<?php echo $imageBaseUrl; ?>homelet-logo.png" alt="HomeLet - Taking the Risk out of Property Rental" width="188" height="81" /></a><br /><br /><br />

                            <!-- White bg inner -->
                            <table width="100%" border="1" bgcolor="white" cellpadding="0" cellspacing="0" style="border: 1px solid #9a9a9a; -webkit-border-bottom-right-radius: 20px; -webkit-border-bottom-left-radius: 20px; -moz-border-radius-bottomright: 20px; -moz-border-radius-bottomleft: 20px; border-bottom-right-radius: 20px; border-bottom-left-radius: 20px;">
                                <tr>
                                    <td>
                                        <table border="0" cellpadding="0" cellspacing="15" width="100%" bgcolor="#00346d">
                                            <tr>
                                                <td><h1 class="emailhead" style="color:#ffffff !important;"><?php echo $this->metaData['heading']; ?></h1></td>
                                            </tr>
                                        </table>

                                        <table width="100%" cellpadding="15">
                                            <tr>
                                                <td>

