<?php
/*
if ($this->stepNum == 'dd') {
    ?>
    <input type="submit" value="Confirm" id="next" name="next">
    <input type="submit" value="Back" id="back" name="back">
    <?php
} elseif ($this->stepNum == 'cc') {
    ?>
    <input type="submit" value="Confirm" id="next" name="next">
    <input type="submit" value="Back" id="back" name="back">
    <?php
} else {
    if ($this->stepNum < $this->stepMax) {
        ?>
        <input type="submit" value="Next" id="next" name="next">
        <?php
    } else {
        ?>
        <input type="submit" value="Buy Me" id="next" name="next">
        <?php
    }
    if ($this->stepNum > 1) {
        ?>
        <input type="submit" value="Back" id="back" name="back">
        <?php
    }
}
*/
?>

<input type="submit" value="Next" name="next" class="btn btn-quaternary pull-right" />
<div class="clearfix"></div>