<?php
    $agentName    = $this->metaData['lettingAgent'];
    $surveyLink   = $this->metaData['surveyLink'];
    $landlordName = $this->metaData['landlordName'];
?>
<?php echo $landlordName; ?>,

You should have received an Acknowledgment of Interest to confirm that <?php echo $agentName; ?> has taken out a Rent Recovery Plus Policy in their own name
through HomeLet, and have noted that you have an "Interest In" the policy.  This means that if your tenant is in breach of their tenancy agreement and <?php echo $agentName; ?>
makes a successful claim under the policy, any sums recovered that are due to you under your agreement will be passed onto you by them.

HomeLet would like to ensure that you have a complete understanding of this product, as it is HomeLet that provide the cover to your letting agent.

Please click on the link below for a brief explanation of your Interest In this policy, and just one question that we would like you to answer regarding this
product. We expect it to take no more than 2 minutes of your time to answer the question and would really appreciate your feedback.

<?php echo $surveyLink ?>

If you have any queries regarding the service you have entered into with <?php echo $agentName; ?>, please contact <?php echo $agentName; ?> directly.

Kind regards

The HomeLet Team
