<?php echo $this->landlordsQuoteSubHeader($this->stepNum); ?>
<div class="landlords col-sm-9">
    <div class="content">
        <h2 class="quaternary-colour">We need some further information to complete your quote</h2>

        <p>
            Thank you for choosing HomeLet to get a Landlord Insurance quote for your property.
        </p>

        <p>
            We&rsquo;re currently unable to provide a quote for your property; this might be because your property is a new build.  We&rsquo;re sorry for any inconvenience this causes, but we&rsquo;ll be in touch shortly to arrange a quote for your property.
        </p>

        <h3 class="quaternary-colour">We&rsquo;ll contact you to complete your quote</h3>

        <p>
            The details that you&rsquo;ve entered have been passed to our expert Landlord Insurance team. We&rsquo;ll be in contact shortly to discuss your needs and provide a quote for your property.
        </p>

        <h3 class="quaternary-colour">Contacting us</h3>

        <p>
            Alternately, you can call our Landlord Insurance team on <strong>0330 333 7190</strong>.
        </p>

        <p>
            Calls to this number cost the same as calls to local numbers (i.e. 01 and 02 area codes) from both landlines and mobiles. You can also reach the team by calling 01522 838603.
        </p>

        <p>
            Our lines are open:<br />
            Monday to Friday from 8:30am - 6:30pm<br />
            Saturday 9:30am - 1pm
        </p>

        <h3 class="quaternary-colour">Five star cover that&rsquo;s worth the wait</h3>

        <p>
            We offer independently rated 5* star cover for landlords, our Buildings Insurance includes:
            <ul>
                <li>Emergency Assistance to get accidents and incidents sorted ASAP.</li>
                <li>Loss of rent or re-letting costs you may be faced with after insured damage.</li>
                <li>&pound;5m property owner&rsquo;s liability and &pound;10m employer&rsquo;s liability for extra reassurance.</li>
            </ul>
        </p>

        <p>
            Once again thank you for your patience,<br />
            The HomeLet team
        </p>
    </div>
</div>
<?php echo $this->landlordsQuoteSidebar($this->premiums, $this->fees, $this->errorsHtml, $this->stepNum, $this->stepMax); ?>