<?php echo $this->landlordsQuoteSubHeader($this->stepNum); ?>
<div class="corporate">
    <div class="wrapper">
        <div class="content">
           <div class="form_section">
              <div>
                  <p>Thank you for your application. We need to gather a few more details from you before we provide a quote, therefore one of our specialist landlord team members will be contacting you shortly.</p>
                  <p>If you have any queries please phone 0845 117 6000. We're open from 8:30am - 6:30pm Monday to Friday and 9:30am – 1:00pm Saturday.</p>
                  <p>Your quote number(s) are <?php echo $this->policyNumber; ?></p>
              </div>
            </div>
        </div>
    </div>
</div>
