<?php echo $this->subHeader('landlords', 'landlords'); ?>
<div class="landlords">
    <div class="wrapper two-col">
        <div class="content">
            <h1><span class="landlords">Retrieve a quote</span></h1>
            <br />
            <p>To retrieve a quote that you have already been given please enter your details below</p>
            <p>If you have forgotten your password please enter your email address and click the forgotten password button. A new password will be emailed to you.</p>
            <?php if ($this->form->getDescription()): ?>
                <ul class="errors">
                    <li><?php echo $this->form->getDescription(); ?></li>
                </ul>
            <?php endif; ?>
            <?php echo $this->form; ?>
        </div>
        <div class="sidebar">
            <h4>What people say</h4>
            <div class="blue landlords">
                <div class="testyhearts">
                    <div id="testimonials-holder">
                        <ul>
                            <?php echo $this->testimonials( 'landlords' ); ?>
                        </ul>
                        <div id="test-changer">
                            <a href="#" rel="nofollow" class="prev" id="test-changer-left"></a>
                            <a href="#" rel="nofollow" class="next" id="test-changer-right"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $('.form_section > div:even')
            .not($('.form_section > div input.noalt').parent())
            .addClass('alt');
    });
</script>
<?php //print_r($this->form);?>