<h2>Additional Information</h2>
<div class="form_section two-col">
	<div class="autoAlt">
		<?php echo $this->element->additional_information; ?>
	</div>
	<div class="autoAlt">
		I can confirm that I have received permission from the named individual(s) to provide their contact details to HomeLet, for the purposes of being provided with a telephone quote for insurance
		<?php echo $this->element->confirmation_statement; ?>
	</div>
	<div class="autoAlt">
		Please be aware the earliest we can call your clients for an insurance quotation is the next working day.
	</div>
</div>
