services:
    barbon.hosted_api.agent.debug.controller_debug:
        class: Barbon\HostedApi\Agent\DebugBundle\Controller\DebugController
        calls:
            - [ setContainer,[ @service_container ] ]