<font face="Trebuchet MS, Hevetica, Arial, sans-serif" color="#0C2F6B">
    Dear <?php echo $this->metaData['name']; ?>, <br />
    <br />
    You recently visited our website and requested to reset your account password.<br />
    <br />
    Your new password is <font color="#E60E64"><?php echo $this->metaData['password']; ?></font><br />
    <br />
    You can login using this and your registered email address of <font color="#E60E64"><?php echo $this->metaData['email']; ?></font><br />
    <br />
    If you didn't request to reset your password or you have any questions please call one of our friendly customer services advisors on <font color="#E60E64">0845 117 6000</font> from 8.30am-8pm Monday to Friday and 9.30am-1pm Saturday.<br />
    <br />
    If you have trouble getting through to the number stated above then please call <font color="#E60E64">01522 838514.</font><br />
    <br />
    Many thanks<br />
    <br />
    HomeLet<br />
</font>